/* 航空コード辞典：追加の航空会社（2026-09）
   運航中の主な航空会社。運航停止・合併した会社は除外（★変わることがある）
   形式：[IATA, ICAO, 英語名, 国, 日本語名, 한국어명] */
window.AL_EXTRA=[
["3X","JAC","Japan Air Commuter","JP","日本エアコミューター","일본에어커뮤터"],["XM","JLJ","J-AIR","JP","ジェイエア","제이에어"],["EH","AKX","ANA Wings","JP","ANAウイングス","ANA 윙스"],["MZ","AHX","Amakusa Airlines","JP","天草エアライン","아마쿠사항공"],
["GS","GCR","Tianjin Airlines","CN","天津航空","톈진항공"],["JD","CBJ","Beijing Capital Airlines","CN","北京首都航空","베이징수도항공"],["8L","LKE","Lucky Air","CN","祥鵬航空","럭키항공"],["KN","CUA","China United Airlines","CN","中国聯合航空","차이나유나이티드항공"],["GJ","CDC","Loong Air","CN","長龍航空","룽에어"],["PN","CHB","West Air","CN","西部航空","웨스트에어"],["EU","UEA","Chengdu Airlines","CN","成都航空","청두항공"],["G5","HXA","China Express Airlines","CN","華夏航空","화샤항공"],["DZ","EPA","Donghai Airlines","CN","東海航空","둥하이항공"],["TV","TBA","Tibet Airlines","CN","西蔵航空","티베트항공"],["BK","OKA","Okay Airways","CN","奥凱航空","오케이항공"],["NS","HBH","Hebei Airlines","CN","河北航空","허베이항공"],["QW","QDA","Qingdao Airlines","CN","青島航空","칭다오항공"],["AQ","JYH","9 Air","CN","九元航空","지우위안항공"],["GX","CBG","GX Airlines","CN","北部湾航空","베이부완항공"],["KY","KNA","Kunming Airlines","CN","昆明航空","쿤밍항공"],["OQ","CQN","Chongqing Airlines","CN","重慶航空","충칭항공"],["UQ","CUH","Urumqi Air","CN","烏魯木斉航空","우루무치항공"],["FU","FZA","Fuzhou Airlines","CN","福州航空","푸저우항공"],["CK","CKK","China Cargo Airlines","CN","中国貨運航空","중국화물항공"],["O3","CSS","SF Airlines","CN","順豊航空","순펑항공"],["YG","HYT","YTO Cargo Airlines","CN","圓通航空","위안퉁항공"],
["HB","HGB","Greater Bay Airlines","HK","大湾区航空","그레이터베이항공"],["AE","MDA","Mandarin Airlines","TW","華信航空","만다린항공"],["B7","UIA","UNI Air","TW","立栄航空","유니에어"],
["OD","MXD","Batik Air Malaysia","MY","バティック・エア・マレーシア","바틱에어 말레이시아"],["ID","BTK","Batik Air","ID","バティック・エア","바틱에어"],["JT","LNI","Lion Air","ID","ライオン・エア","라이온에어"],["QZ","AWQ","Indonesia AirAsia","ID","インドネシア・エアアジア","인도네시아 에어아시아"],["IU","SJV","Super Air Jet","ID","スーパー・エア・ジェット","슈퍼에어젯"],["QG","CTV","Citilink","ID","シティリンク","시티링크"],["SJ","SJY","Sriwijaya Air","ID","スリウィジャヤ航空","스리위자야항공"],["8M","MMA","Myanmar Airways International","MM","ミャンマー国際航空","미얀마국제항공"],["UB","UBA","Myanmar National Airlines","MM","ミャンマー・ナショナル航空","미얀마내셔널항공"],["QV","LAO","Lao Airlines","LA","ラオ航空","라오항공"],["K6","KHV","Cambodia Angkor Air","KH","カンボジア・アンコール航空","캄보디아앙코르항공"],["BI","RBA","Royal Brunei Airlines","BN","ロイヤルブルネイ航空","로열브루나이항공"],["PG","BKP","Bangkok Airways","TH","バンコク・エアウェイズ","방콕에어웨이즈"],["SL","TLM","Thai Lion Air","TH","タイ・ライオン・エア","타이 라이온에어"],["DD","NOK","Nok Air","TH","ノックエア","녹에어"],["BL","PIC","Pacific Airlines","VN","パシフィック航空","퍼시픽항공"],["VU","VAG","Vietravel Airlines","VN","ベトラベル航空","비엣트래블항공"],["2P","GAP","PAL Express","PH","PALエクスプレス","PAL 익스프레스"],
["IX","AXB","Air India Express","IN","エア・インディア・エクスプレス","에어인디아 익스프레스"],["SG","SEJ","SpiceJet","IN","スパイスジェット","스파이스젯"],["QP","AKJ","Akasa Air","IN","アカサ・エア","아카사에어"],["PK","PIA","Pakistan International Airlines","PK","パキスタン航空","파키스탄항공"],["BG","BBC","Biman Bangladesh Airlines","BD","ビマン・バングラデシュ航空","비만방글라데시항공"],["BS","UBG","US-Bangla Airlines","BD","USバングラ航空","US-방글라항공"],["RA","RNA","Nepal Airlines","NP","ネパール航空","네팔항공"],["KB","DRK","Drukair","BT","ドルク航空","드루크에어"],["Q2","DQA","Maldivian","MV","モルディブ航空","몰디브항공"],
["J2","AHY","Azerbaijan Airlines","AZ","アゼルバイジャン航空","아제르바이잔항공"],["A9","TGZ","Georgian Airways","GE","ジョージア航空","조지아항공"],["SZ","SMR","Somon Air","TJ","ソモン航空","소몬에어"],
["FZ","FDB","flydubai","AE","フライドバイ","플라이두바이"],["G9","ABY","Air Arabia","AE","エアアラビア","에어아라비아"],["WY","OMA","Oman Air","OM","オマーン航空","오만항공"],["GF","GFA","Gulf Air","BH","ガルフ・エア","걸프에어"],["KU","KAC","Kuwait Airways","KW","クウェート航空","쿠웨이트항공"],["J9","JZR","Jazeera Airways","KW","ジャジーラ航空","자지라항공"],["XY","KNE","flynas","SA","フライナス","플라이나스"],["RJ","RJA","Royal Jordanian","JO","ロイヤル・ヨルダン航空","로열요르단항공"],["ME","MEA","Middle East Airlines","LB","ミドルイースト航空","중동항공"],["LY","ELY","El Al","IL","エル・アル航空","엘알항공"],["PC","PGT","Pegasus Airlines","TR","ペガサス航空","페가수스항공"],["XQ","SXS","SunExpress","TR","サンエクスプレス","썬익스프레스"],["IR","IRA","Iran Air","IR","イラン航空","이란항공"],
["SN","BEL","Brussels Airlines","BE","ブリュッセル航空","브뤼셀항공"],["EW","EWG","Eurowings","DE","ユーロウイングス","유로윙스"],["DE","CFG","Condor","DE","コンドル航空","콘도르항공"],["EN","DLA","Air Dolomiti","IT","エアドロミティ","에어돌로미티"],["TP","TAP","TAP Air Portugal","PT","TAPポルトガル航空","TAP 포르투갈항공"],["UX","AEA","Air Europa","ES","エアヨーロッパ","에어유로파"],["VY","VLG","Vueling","ES","ブエリング航空","부엘링항공"],["V7","VOE","Volotea","ES","ボロテア","볼로테아"],["EI","EIN","Aer Lingus","IE","エアリンガス","에어링거스"],["A3","AEE","Aegean Airlines","GR","エーゲ海航空","에게안항공"],["OU","CTN","Croatia Airlines","HR","クロアチア航空","크로아티아항공"],["RO","ROT","TAROM","RO","タロム航空","타롬항공"],["JU","ASL","Air Serbia","RS","エアセルビア","에어세르비아"],["FB","LZB","Bulgaria Air","BG","ブルガリア航空","불가리아항공"],["BT","BTI","airBaltic","LV","エアバルト","에어발틱"],["OK","CSA","Czech Airlines","CZ","チェコ航空","체코항공"],["DY","NOZ","Norwegian","NO","ノルウェージアン","노르웨이전"],["WF","WIF","Widerøe","NO","ヴィデロー航空","비데로에항공"],["FI","ICE","Icelandair","IS","アイスランド航空","아이슬란드항공"],["LG","LGL","Luxair","LU","ルクスエア","룩스에어"],["LS","EXS","Jet2","GB","ジェット2","젯2"],["BY","TOM","TUI Airways","GB","TUIエアウェイズ","TUI 에어웨이즈"],["HV","TRA","Transavia","NL","トランサビア","트랜사비아"],["TO","TVF","Transavia France","FR","トランサビア・フランス","트랜사비아 프랑스"],["SU","AFL","Aeroflot","RU","アエロフロート","아에로플로트"],["S7","SBI","S7 Airlines","RU","S7航空","S7 항공"],
["F9","FFT","Frontier Airlines","US","フロンティア航空","프론티어항공"],["NK","NKS","Spirit Airlines","US","スピリット航空","스피릿항공"],["G4","AAY","Allegiant Air","US","アレジアント航空","얼리전트항공"],["SY","SCX","Sun Country Airlines","US","サンカントリー航空","썬컨트리항공"],["MX","MXY","Breeze Airways","US","ブリーズ・エアウェイズ","브리즈항공"],["QX","QXE","Horizon Air","US","ホライゾン航空","호라이즌항공"],["OO","SKW","SkyWest Airlines","US","スカイウェスト航空","스카이웨스트항공"],["YX","RPA","Republic Airways","US","リパブリック航空","리퍼블릭항공"],["9E","EDV","Endeavor Air","US","エンデバー航空","엔데버항공"],["5Y","GTI","Atlas Air","US","アトラス航空","아틀라스항공"],["K4","CKS","Kalitta Air","US","カリッタ航空","칼리타항공"],["PO","PAC","Polar Air Cargo","US","ポーラー航空","폴라항공"],["WS","WJA","WestJet","CA","ウエストジェット","웨스트젯"],["TS","TSC","Air Transat","CA","エアトランザット","에어트랜사트"],["PD","POE","Porter Airlines","CA","ポーター航空","포터항공"],["F8","FLE","Flair Airlines","CA","フレア航空","플레어항공"],["Y4","VOI","Volaris","MX","ボラリス","볼라리스"],["VB","VIV","Viva Aerobus","MX","ビバ・アエロバス","비바에어로버스"],["CM","CMP","Copa Airlines","PA","コパ航空","코파항공"],["AV","AVA","Avianca","CO","アビアンカ航空","아비앙카항공"],["G3","GLO","GOL","BR","ゴル航空","골항공"],["AD","AZU","Azul","BR","アズール航空","아줄항공"],["AR","ARG","Aerolíneas Argentinas","AR","アルゼンチン航空","아르헨티나항공"],["H2","SKU","Sky Airline","CL","スカイエアライン","스카이에어라인"],["JA","JAT","JetSMART","CL","ジェットスマート","젯스마트"],["UP","BHS","Bahamasair","BS","バハマス航空","바하마스항공"],["BW","BWA","Caribbean Airlines","TT","カリブ航空","카리브항공"],
["FJ","FJI","Fiji Airways","FJ","フィジー航空","피지항공"],["PX","ANG","Air Niugini","PG","ニューギニア航空","에어뉴기니"],["TN","THT","Air Tahiti Nui","PF","エアタヒチヌイ","에어타히티누이"],["SB","ACI","Aircalin","NC","エアカラン","에어칼린"],
["KQ","KQA","Kenya Airways","KE","ケニア航空","케냐항공"],["AT","RAM","Royal Air Maroc","MA","ロイヤル・エア・モロッコ","로열에어모로코"],["WB","RWD","RwandAir","RW","ルワンダ航空","르완다항공"],["TU","TAR","Tunisair","TN","チュニス航空","튀니지항공"],["AH","DAH","Air Algérie","DZ","アルジェリア航空","알제리항공"],["MK","MAU","Air Mauritius","MU","モーリシャス航空","모리셔스항공"],["HM","SEY","Air Seychelles","SC","セーシェル航空","세이셸항공"],["FA","SFR","FlySafair","ZA","フライセーフエア","플라이세이프에어"],["P4","APK","Air Peace","NG","エアピース","에어피스"],["TC","ATC","Air Tanzania","TZ","タンザニア航空","탄자니아항공"],["KP","SKK","ASKY Airlines","TG","アスキー航空","아스키항공"],
["CV","CLX","Cargolux","LU","カーゴルクス","카고룩스"],["QY","BCS","European Air Transport (DHL)","DE","ヨーロピアン・エア・トランスポート（DHL）","유러피안 에어 트랜스포트(DHL)"]
];
