/* 航空コード辞典：航空券番号・航空貨物運送状番号の頭3桁（2026-09）
   出典：IATA「Current Airline Members」の3 digit code（2026年9月28日取得、IATA加盟378社のうち番号が掲載されている354社）
   形式：[頭3桁, 2レター(IATA), 3レター(ICAO), 航空会社（英）, 国, 貨物専用=1]
   ＊付きの2レターは「管理された重複」（別の会社と同じ2レターを分けて使う）。加盟していない航空会社も番号を持つことがある ★ */
window.TKT2=[["001","AA","AAL","American Airlines","US",0],
["002","B0","DJT","La Compagnie","FR",0],
["006","DL","DAL","Delta Air Lines","US",0],
["010","PQ","SQP","SkyUp Airlines","UA",0],
["014","AC","ACA","Air Canada","CA",0],
["016","UA","UAL","United Airlines","US",0],
["017","IF","FBA","Fly Baghdad","IQ",0],
["018","HO","DKH","Juneyao Airlines","CN",0],
["020","LH","GEC","Lufthansa Cargo","DE",1],
["021","V3","KRP","Carpatair","RO",0],
["023","FX","FDX","FedEx Express","US",1],
["027","AS","ASA","Alaska Airlines","US",0],
["030","VY","VLG","Vueling","ES",0],
["031","PW","PRF","Precision Air","TZ",0],
["032","KP","SKK","ASKY","TG",0],
["034","U8","CYF","TUS Airways","CY",0],
["035","4C","ARE","LATAM Airlines Colombia","CO",0],
["036","Y4","VOI","Volaris","MX",0],
["040","QC","CRC","Camair-Co","CM",0],
["044","AR","ARG","Aerolineas Argentinas","AR",0],
["045","LA","LAN","LATAM Airlines Group","CL",0],
["047","TP","TAP","TAP Air Portugal","PT",0],
["050","OA","OAL","Olympic Air","GR",0],
["053","EI","EIN","Aer Lingus","IE",0],
["055","AZ","ITY","ITA Airways","IT",0],
["057","AF","AFR","Air France","FR",0],
["059","GW*","GJT","GetJet Airlines","LT",0],
["061","HM","SEY","Air Seychelles","SC",0],
["063","SB","ACI","Aircalin","NC",0],
["065","SV","SVA","Saudi Arabian Airlines","SA",0],
["068","TM","LAM","LAM","MZ",0],
["070","RB","SYR","Syrianair","SY",0],
["071","ET","ETH","Ethiopian Airlines","ET",0],
["072","GF","GFA","Gulf Air","BH",0],
["074","KL","KLM","KLM","NL",0],
["075","IB","IBE","IBERIA","ES",0],
["076","ME","MEA","MEA","LB",0],
["077","MS","MSR","Egyptair","EG",0],
["078","CY","CYP","Cyprus Airways","CY",0],
["079","PR","PAL","Philippine Airlines","PH",0],
["080","LO","LOT","LOT Polish Airlines","PL",0],
["081","QF","QFA","Qantas","AU",0],
["082","SN","BEL","Brussels Airlines","BE",0],
["083","SA","SAA","South African Airways","ZA",0],
["086","NZ","ANZ","Air New Zealand","NZ",0],
["088","TV","TBA","Xizang Airlines","CN",0],
["096","IR","IRA","Iran Air","IR",0],
["097","WI","WHT","White coloured by you","PT",0],
["098","AI","AIC","Air India","IN",0],
["101","EN","DLA","Air Dolomiti","IT",0],
["104","EW","EWG","Eurowings","DE",0],
["105","AY","FIN","Finnair","FI",0],
["106","BW","BWA","Caribbean Airlines","TT",0],
["108","FI","ICE","Icelandair","IS",0],
["110","UJ","LMU","AlMasria Universal Airlines","EG",0],
["111","UP","BHS","Bahamasair","BS",0],
["112","CK","CKK","China Cargo Airlines","CN",1],
["114","LY","ELY","EL AL","IL",0],
["115","JU","ASL","Air Serbia","RS",0],
["117","SK","SAS","SAS","SE",0],
["118","DT","DTA","TAAG Angola Airlines","AO",0],
["120","JS","KOR","Air Koryo","KP",0],
["122","RX","RXI","Riyadh Air","SA",0],
["123","ON","RON","Nauru Airlines","AU",0],
["124","AH","DAH","Air Algérie","DZ",0],
["125","BA","BAW","British Airways","GB",0],
["126","GA","GIA","Garuda Indonesia","ID",0],
["127","G3","GLO","GOL Linhas Aereas","BR",0],
["128","UO","HKE","Hong Kong Express Airways","HK",0],
["129","MP","MPH","Martinair Cargo","NL",1],
["130","5F","FIA","FLYONE","MD",0],
["131","JL","JAL","Japan Airlines","JP",0],
["133","LR","LRC","Avianca Costa Rica","CR",0],
["134","AV","AVA","Avianca","CO",0],
["135","VT","VTA","Air Tahiti","PF",0],
["136","CU","CUB","Cubana","CU",0],
["139","AM","AMX","Aeromexico","MX",0],
["141","FZ","FDB","flydubai","AE",0],
["145","UC","LCO","LATAM Cargo Chile","CL",1],
["146","XK","CCM","Air Corsica","FR",0],
["147","AT","RAM","Royal Air Maroc","MA",0],
["149","LG","LGL","Luxair","LU",0],
["151","R5","JAV","Jordan Aviation","JO",0],
["155","ES*","DHX","DHL Air (Bahrain)","BH",1],
["157","QR","QTR","Qatar Airways","QA",0],
["160","CX","CPA","Cathay Pacific","HK",0],
["169","HR*","HHN","Hahnair","DE",0],
["172","CV","CLX","Cargolux","LU",1],
["173","HA","HAL","Hawaiian Airlines","US",0],
["176","EK","UAE","Emirates","AE",0],
["180","KE","KAL","Korean Air","KR",0],
["181","DM","DWI","Arajet","DO",0],
["182","6O","OBS","Iberojet","PT",0],
["188","K6","KHV","Air Cambodia","KH",0],
["189","JX","SJX","STARLUX Airlines","TW",0],
["190","TY","TPC","Air Caledonie","NC",0],
["193","IE","SOL","Solomon Airlines","SB",0],
["195","FV","SDM","Rossiya Airlines","RU",0],
["197","TC","ATC","Air Tanzania","TZ",0],
["199","TU","TAR","Tunisair","TN",0],
["202","TA","TAI","TACA","SV",0],
["203","5J","CEB","Cebu Pacific","PH",0],
["204","VF","TKJ","AJet","TR",0],
["205","NH","ANA","ANA","JP",0],
["211","2P","GAP","PAL Express","PH",0],
["214","PK","PIA","Pakistan International Airlines","PK",0],
["216","N4","NWS","Nordwind Airlines","RU",0],
["217","TG","THA","Thai Airways International","TH",0],
["220","LH","DLH","Lufthansa","DE",0],
["221","WT","SWT","Swiftair","ES",0],
["225","5Z","KEM","CemAir","ZA",0],
["229","KU","KAC","Kuwait Airways","KW",0],
["230","CM","CMP","COPA Airlines","PA",0],
["232","MH","MAS","Malaysia Airlines","MY",0],
["235","TK","THY","Turkish Airlines","TR",0],
["236","IX","AXB","Air India Express","IN",0],
["238","IZ","AIZ","Arkia Israeli Airlines","IL",0],
["239","MK","MAU","Air Mauritius","MU",0],
["244","TN","THT","Air Tahiti Nui","PF",0],
["245","0B","BBL","BBN Airlines Indonesia","ID",0],
["246","VE","EFY","Clic Air","CO",0],
["250","HY","UZB","Uzbekistan Airways","UZ",0],
["257","OS","AUA","Austrian","AT",0],
["258","MD","MGY","Madagascar Airlines","MG",0],
["260","FJ","FJI","Fiji Airways","FJ",0],
["262","U6","SVR","Ural Airlines","RU",0],
["263","2S","STW","Southwind Airlines","TR",0],
["264","NF","AVN","Air Vanuatu","VU",0],
["275","GP","RIV","APG Airlines","FR",0],
["276","TF*","BRX","Braathens Regional Airways","SE",0],
["277","J7","ABS","FlyGabon","GA",0],
["279","B6","JBU","JetBlue","US",0],
["281","RO","ROT","TAROM","RO",0],
["283","HB","HGB","Greater Bay Airlines","HK",0],
["288","LD","AHK","Air Hong Kong","HK",1],
["289","OM","MGL","MIAT Mongolian Airlines","MN",0],
["297","CI","CAL","China Airlines","TW",0],
["298","UT","UTA","UTair","RU",0],
["299","DR","RLH","Ruili Airlines","CN",0],
["310","SL","TLM","Thai Lion Air","TH",0],
["312","6E","IGO","IndiGo","IN",0],
["316","5N","AUL","Smartavia","RU",0],
["318","CC","ABD","Air Atlanta Icelandic","IS",0],
["324","SC","CDG","Shandong Airlines","CN",0],
["325","NP","NIA","Nile Air","EG",0],
["330","D4","GEL","Airline GEO SKY","GE",0],
["331","S4","RZO","Azores Airlines","PT",0],
["334","FN","FJW","Fastjet Zimbabwe","ZW",0],
["337","SY","SCX","Sun Country Airlines","US",0],
["350","YP","APZ","Air Premia","KR",0],
["353","NU","JTA","Japan Transocean Air","JP",0],
["355","E7","ESF","Estafeta Cargo","MX",1],
["362","7R","RLU","RusLine","RU",0],
["365","W2","FXT","FlexFlight","DK",0],
["367","J4","BDR","Badr Airlines","SD",0],
["369","5Y","GTI","Atlas Air","US",1],
["381","SM","MSC","Air Cairo","EG",0],
["384","RQ","KMF","Kam Air","AF",0],
["386","B5","BBT","BBN Airlines","TR",0],
["390","A3","AEE","Aegean Airlines","GR",0],
["394","AW","AFW","Africa World Airlines","GH",0],
["395","XC","CAI","Corendon Airlines","TR",0],
["396","BF","FBU","French Bee","FR",0],
["400","4O","MNE","Air Montenegro","ME",0],
["402","G6","GXA","GlobalX","US",0],
["403","PO","PAC","Polar Air Cargo","US",1],
["404","BZ","BBG","Blue Bird Airways","GR",0],
["406","5X","UPS","UPS Airlines","US",1],
["408","M4","MSA","Poste Air Cargo","IT",1],
["411","5U","TGU","TAG Airlines","GT",0],
["413","SZ","SMR","Somon Air","TJ",0],
["415","HP","APF","PopulAir","SE",0],
["416","N8","NCR","National Airlines","US",0],
["419","XZ","AEZ","Aeroitalia","IT",0],
["421","S7","SBI","S7 Airlines","RU",0],
["422","F9","FFT","Frontier Airlines","US",0],
["427","TX","FWI","Air Caraibes","GP",0],
["433","P6","PVG","Privilege Style","ES",0],
["441","FC","","Link Airways","AU",0],
["444","GO*","KZU","ULS Airlines Cargo","TR",1],
["445","ZP","AZP","Paranair","PY",0],
["448","VL","LHX","Lufthansa City Airlines","DE",0],
["451","PD","POE","Porter Airlines","CA",0],
["459","WB","RWD","RwandAir","RW",0],
["460","EB","PLM","Wamos Air","ES",0],
["462","XL","LNE","LATAM Airlines Ecuador","EC",0],
["465","KC","KZR","Air Astana","KZ",0],
["474","NT","IBB","Binter Canarias","ES",0],
["476","Y7","TYA","NordStar","RU",0],
["477","NE","NMA","Nesma Airlines","EG",0],
["479","ZH","CSZ","Shenzhen Airlines","CN",0],
["486","J9","JZR","Jazeera Airways","KW",0],
["489","W8","CJT","Cargojet Airways","CA",1],
["490","HC","SZN","Air Senegal","SN",0],
["491","B9","IRB","Iran Airtour Airline","IR",0],
["495","L6","MAI","Mauritania Airlines International","MR",0],
["500","O8","MTO","Marathon Airlines","GR",0],
["501","7L","AZG","Silk Way West Airlines","AZ",1],
["505","UF","PER","PAS","EG",0],
["512","RJ","RJA","Royal Jordanian","JO",0],
["514","G9","ABY","Air Arabia","AE",0],
["515","SF","DTH","Domestic Airlines","DZ",0],
["516","QP","AKJ","Akasa Air","IN",0],
["521","RE","GJM","Airhub Airlines","MT",0],
["525","B7","UIA","UNI AIR","TW",0],
["526","WN","SWA","Southwest Airlines","US",0],
["544","LP","LPE","LATAM Airlines Peru","PE",0],
["547","2K","GLG","Avianca Ecuador","EC",0],
["549","M3","LTG","LATAM Cargo Brasil","BR",1],
["551","YU","MMZ","EuroAtlantic Airways","PT",0],
["555","SU","AFL","Aeroflot","RU",0],
["558","5O","FPO","ASL Airlines France","FR",0],
["559","OF","OLA","Overland Airways","NG",0],
["560","F3","FAD","flyadeal","SA",0],
["564","XQ","SXS","SunExpress","TR",0],
["577","AD","AZU","Azul Brazilian Airlines","BR",0],
["581","CS","CSW","Chair Airlines","CH",0],
["593","XY","KNE","Flynas","SA",0],
["596","DD","NOK","Nok Air","TH",0],
["599","8M","MMA","Myanmar Airways International","MM",0],
["603","UL","ALK","SriLankan Airlines","LK",0],
["605","H2","SKU","SKY Airline","CL",0],
["606","A9","TGZ","Georgian Airways","GE",0],
["607","EY","ETD","Etihad Airways","AE",0],
["610","2A","AWA","Air Astra","BD",0],
["615","QY","BCS","European Air Transport","DE",1],
["617","X3","TUI","TUIfly","DE",0],
["618","SQ","SIA","Singapore Airlines","SG",0],
["619","JG","JDL","JD Airlines","CN",0],
["623","FB","LZB","Bulgaria Air","BG",0],
["624","PC","PGT","Pegasus Airlines","TR",0],
["627","QV","LAO","Lao Airlines","LA",0],
["629","QG","CTV","Citilink","ID",0],
["631","GL","GRL","Air Greenland","GL",0],
["633","GQ","SEH","Sky express","GR",0],
["636","BP","BOT","Air Botswana","BW",0],
["640","FA","SFR","Safair","ZA",0],
["643","KM","KMM","KM Malta Airlines","MT",0],
["649","TS","TSC","Air Transat","CA",0],
["655","DV","VSV","SCAT Airlines","KZ",0],
["656","PX","ANG","Air Niugini","PG",0],
["657","BT","BTI","Air Baltic","LV",0],
["659","P0","PFZ","Proflight Zambia","ZM",0],
["663","PU","PUE","Plus Ultra","ES",0],
["665","UB","UBA","Myanmar National Airlines","MM",0],
["666","FU","FZA","Fuzhou Airlines","CN",0],
["668","TR","TGW","Scoot","SG",0],
["672","BI","RBA","Royal Brunei","BN",0],
["675","NX","AMU","Air Macau","MO",0],
["682","LM","LOG","Loganair","GB",0],
["683","CL","CLH","Lufthansa CityLine","DE",0],
["689","WX","BCY","CityJet","IE",0],
["692","PZ","LAP","LATAM Airlines Paraguay","PY",0],
["693","4Y","OCN","Discover Airlines","DE",0],
["694","YW","ANE","Air Nostrum","ES",0],
["695","BR","EVA","EVA Air","TW",0],
["698","GE","GBB","Global Airways and Lift","ZA",0],
["700","5C","ICL","Challenge Airlines (IL)","IL",1],
["701","WF","WIF","Wideroe","NO",0],
["703","NO","NOS","Neos","IT",0],
["704","QI","IAN","Ibom Air","NG",0],
["706","KQ","KQA","Kenya Airways","KE",0],
["710","P4","APK","Air Peace","NG",0],
["712","V7","VOE","Volotea","ES",0],
["716","MB","MNB","MNG Airlines","TR",1],
["718","LJ","JNA","Jin Air","KR",0],
["722","TW","TWB","Trinity Airways","KR",0],
["724","LX","SWR","SWISS","CH",0],
["730","GT","CGH","Air Guilin","CN",0],
["731","MF","CXA","Xiamen Airlines","CN",0],
["734","4M","MGH","Mavi Gök Airlines (MGA)","TR",0],
["737","SP","SAT","SATA Air Acores","PT",0],
["738","VN","HVN","Vietnam Airlines","VN",0],
["744","X7","CHG","Challenge Airlines (BE)","BE",1],
["749","4Z","LNK","Airlink","ZA",0],
["756","3V","TAY","ASL Airlines Belgium","BE",1],
["760","UU","REU","Air Austral","FR",0],
["767","RC","FLI","Atlantic Airways","FO",0],
["768","TI*","TWI","Tailwind Airlines","TR",0],
["769","H9","HIM","Himalaya Airlines","NP",0],
["770","EO","KAR","Ikar","RU",0],
["771","J2","AHY","Azerbaijan Airlines","AZ",0],
["774","FM","CSH","Shanghai Airlines","CN",0],
["775","SG","SEJ","SpiceJet","IN",0],
["779","BS","UBG","US-Bangla Airlines","BD",0],
["781","MU","CES","China Eastern","CN",0],
["783","E9","EVE","Iberojet Airlines","ES",0],
["784","CZ","CSN","China Southern Airlines","CN",0],
["795","VA","VAU","Virgin Australia","AU",0],
["796","BJ","LBT","Nouvelair","TN",0],
["797","QS","TVS","Smartwings","CZ",0],
["803","AE","MDA","Mandarin Airlines","TW",0],
["804","CF","CYZ","China Postal Airlines","CN",1],
["806","7C","JJA","Jeju Air","KR",0],
["811","EU","UEA","Chengdu Airlines","CN",0],
["815","EP","IRC","Iran Aseman Airlines","IR",0],
["816","OD","MXD","Batik Air Malaysia","MY",0],
["818","6H","ISR","Israir","IL",0],
["822","KN","CUA","China United Airlines","CN",0],
["825","2W","WFL","World2Fly","ES",0],
["826","GS","GCR","Tianjin Airlines","CN",0],
["828","RH","HKC","Hong Kong Air Cargo","HK",1],
["829","PG","BKP","Bangkok Airways","TH",0],
["831","OU","CTN","Croatia Airlines","HR",0],
["832","GB","ABX","ABX Air","US",1],
["833","KY","KNA","Kunming Airlines","CN",0],
["836","NS","HBH","Hebei Airlines","CN",0],
["838","WS","WJA","WestJet","CA",0],
["839","ZE","ESR","Eastar Jet","KR",0],
["847","PN","CHB","West Air","CN",0],
["851","HX","CRK","Hong Kong Airlines","HK",0],
["856","9H","CGN","Air Changan","CN",0],
["859","8L","LKE","Lucky Air","CN",0],
["860","YG","HYT","YTO Cargo Airlines","CN",1],
["865","M7","MAA","MasAir","MX",1],
["866","BK","OKA","Okay Airways","CN",0],
["871","Y8","YZR","Suparna Airlines","CN",0],
["872","GX","CBG","GX Airlines","CN",0],
["876","3U","CSC","Sichuan Airlines","CN",0],
["880","HU","CHH","Hainan Airlines","CN",0],
["881","DE","CFG","Condor","DE",0],
["886","UQ","CUH","Urumqi Air","CN",0],
["891","GJ","CDC","Loong Air","CN",0],
["898","JD","CBJ","Capital Airlines","CN",0],
["910","WY","OMA","Oman Air","OM",0],
["912","QW","QDA","Qingdao Airlines","CN",0],
["914","5H","ABR","ASL Airlines Ireland","IE",1],
["921","O3","CSS","SF Airlines","CN",1],
["923","SS","CRL","Corsair International","FR",0],
["926","QH","BAV","Bamboo Airways","VN",0],
["930","OB","BOV","BoA Boliviana de Aviacion","BO",0],
["932","VS","VIR","Virgin Atlantic","GB",0],
["933","KZ","NCA","Nippon Cargo Airlines","JP",1],
["936","D0","DHK","DHL Air","GB",1],
["938","ID","BTK","Batik Air","ID",0],
["944","ZQ","GER","German Airways","DE",0],
["945","WK","EDW","Edelweiss Air","CH",0],
["948","8R","AIA","Amelia","FR",0],
["957","JJ","TAM","LATAM Airlines Brasil","BR",0],
["960","OV","OMS","Salam Air","OM",0],
["970","M0","MNG","Aero Mongolia","MN",0],
["973","JA","JAT","JetSMART Chile","CL",0],
["974","WJ","JES","JetSMART Argentina","AR",0],
["978","VJ","VJC","Vietjet","VN",0],
["980","CE","CLG","Chalair","FR",0],
["981","JZ","JAP","JetSMART Peru","PE",0],
["984","J6","JEC","JetSMART Colombia","CO",0],
["987","G5","HXA","China Express Airlines","CN",0],
["988","OZ","AAR","Asiana Airlines","KR",0],
["990","JT","LNI","Lion Air","ID",0],
["994","KJ","AIH","AIRZETA","KR",1],
["996","UX","AEA","Air Europa","ES",0],
["997","BG","BBC","Biman Bangladesh Airlines","BD",0],
["999","CA","CCA","Air China","CN",0]];
