/* 航空コード辞典：追加データ（2026-09）
   CTRY_ADD：国・地域名の日本語・韓国語
   CITY2：IATAの複数空港都市（決議011c 付属A、2022年10月1日発効）[都市コード, 空港, 国, 名称[ja,ko,en], 注]
   PFX2：ICAOの地点略号の頭文字（ICAO Doc 7910の構成）[記号, 国, 注]
   REG：機体の国籍記号（ICAO第7附属書 補遺「Aircraft Nationality Marks」2025年6月版）[記号, 国, 注]
   ★変わることがある */
window.CTRY_ADD={"AF":["Afghanistan","アフガニスタン","아프가니스탄"],"AG":["Antigua and Barbuda","アンティグア・バーブーダ","앤티가 바부다"],"AI":["Anguilla","アンギラ","앵귈라"],"AL":["Albania","アルバニア","알바니아"],"AM":["Armenia","アルメニア","아르메니아"],"AO":["Angola","アンゴラ","앙골라"],"AS":["American Samoa","米領サモア","아메리칸사모아"],"AW":["Aruba","アルバ","아루바"],"AZ":["Azerbaijan","アゼルバイジャン","아제르바이잔"],"BA":["Bosnia and Herzegovina","ボスニア・ヘルツェゴビナ","보스니아 헤르체고비나"],"BB":["Barbados","バルバドス","바베이도스"],"BF":["Burkina Faso","ブルキナファソ","부르키나파소"],"BG":["Bulgaria","ブルガリア","불가리아"],"BI":["Burundi","ブルンジ","부룬디"],"BJ":["Benin","ベナン","베냉"],"BL":["Saint Barthélemy","サン・バルテルミー","생바르텔레미"],"BM":["Bermuda","バミューダ","버뮤다"],"BO":["Bolivia","ボリビア","볼리비아"],"BQ":["Caribbean Netherlands","カリブ・オランダ","카리브 네덜란드"],"BS":["Bahamas","バハマ","바하마"],"BT":["Bhutan","ブータン","부탄"],"BW":["Botswana","ボツワナ","보츠와나"],"BY":["Belarus","ベラルーシ","벨라루스"],"BZ":["Belize","ベリーズ","벨리즈"],"CC":["Cocos (Keeling) Islands","ココス（キーリング）諸島","코코스 제도"],"CD":["Democratic Republic of the Congo","コンゴ民主共和国","콩고민주공화국"],"CF":["Central African Republic","中央アフリカ","중앙아프리카공화국"],"CG":["Republic of the Congo","コンゴ共和国","콩고공화국"],"CI":["Côte d'Ivoire","コートジボワール","코트디부아르"],"CK":["Cook Islands","クック諸島","쿡 제도"],"CM":["Cameroon","カメルーン","카메룬"],"CO":["Colombia","コロンビア","콜롬비아"],"CR":["Costa Rica","コスタリカ","코스타리카"],"CU":["Cuba","キューバ","쿠바"],"CV":["Cape Verde","カーボベルデ","카보베르데"],"CW":["Curaçao","キュラソー","퀴라소"],"CX":["Christmas Island","クリスマス島","크리스마스섬"],"CY":["Cyprus","キプロス","키프로스"],"DJ":["Djibouti","ジブチ","지부티"],"DM":["Dominica","ドミニカ国","도미니카연방"],"DO":["Dominican Republic","ドミニカ共和国","도미니카공화국"],"DZ":["Algeria","アルジェリア","알제리"],"EC":["Ecuador","エクアドル","에콰도르"],"EE":["Estonia","エストニア","에스토니아"],"EH":["Western Sahara (disputed territory)","西サハラ","서사하라"],"ER":["Eritrea","エリトリア","에리트레아"],"FK":["Falkland Islands","フォークランド諸島","포클랜드 제도"],"FM":["Micronesia","ミクロネシア連邦","미크로네시아 연방"],"FO":["Faroe Islands","フェロー諸島","페로 제도"],"GA":["Gabon","ガボン","가봉"],"GD":["Grenada","グレナダ","그레나다"],"GE":["Georgia","ジョージア","조지아"],"GF":["French Guiana","仏領ギアナ","프랑스령 기아나"],"GG":["Guernsey","ガーンジー","건지"],"GH":["Ghana","ガーナ","가나"],"GI":["Gibraltar","ジブラルタル","지브롤터"],"GL":["Greenland","グリーンランド","그린란드"],"GM":["Gambia","ガンビア","감비아"],"GN":["Guinea","ギニア","기니"],"GP":["Guadeloupe","グアドループ","과들루프"],"GQ":["Equatorial Guinea","赤道ギニア","적도기니"],"GT":["Guatemala","グアテマラ","과테말라"],"GW":["Guinea-Bissau","ギニアビサウ","기니비사우"],"GY":["Guyana","ガイアナ","가이아나"],"HN":["Honduras","ホンジュラス","온두라스"],"HT":["Haiti","ハイチ","아이티"],"IM":["Isle of Man","マン島","맨섬"],"IQ":["Iraq","イラク","이라크"],"IR":["Iran","イラン","이란"],"JE":["Jersey","ジャージー","저지"],"JM":["Jamaica","ジャマイカ","자메이카"],"KI":["Kiribati","キリバス","키리바시"],"KM":["Comoros","コモロ","코모로"],"KN":["Saint Kitts and Nevis","セントクリストファー・ネービス","세인트키츠 네비스"],"KP":["North Korea","北朝鮮","북한"],"KY":["Cayman Islands","ケイマン諸島","케이맨 제도"],"LB":["Lebanon","レバノン","레바논"],"LC":["Saint Lucia","セントルシア","세인트루시아"],"LR":["Liberia","リベリア","라이베리아"],"LS":["Lesotho","レソト","레소토"],"LT":["Lithuania","リトアニア","리투아니아"],"LU":["Luxembourg","ルクセンブルク","룩셈부르크"],"LV":["Latvia","ラトビア","라트비아"],"LY":["Libya","リビア","리비아"],"MD":["Moldova","モルドバ","몰도바"],"ME":["Montenegro","モンテネグロ","몬테네그로"],"MF":["Saint Martin","サン・マルタン","생마르탱"],"MG":["Madagascar","マダガスカル","마다가스카르"],"MH":["Marshall Islands","マーシャル諸島","마셜 제도"],"MK":["North Macedonia","北マケドニア","북마케도니아"],"ML":["Mali","マリ","말리"],"MQ":["Martinique","マルティニーク","마르티니크"],"MR":["Mauritania","モーリタニア","모리타니"],"MS":["Montserrat","モントセラト","몬트세랫"],"MT":["Malta","マルタ","몰타"],"MU":["Mauritius","モーリシャス","모리셔스"],"MW":["Malawi","マラウイ","말라위"],"MZ":["Mozambique","モザンビーク","모잠비크"],"NA":["Namibia","ナミビア","나미비아"],"NC":["New Caledonia","ニューカレドニア","뉴칼레도니아"],"NE":["Niger","ニジェール","니제르"],"NF":["Norfolk Island","ノーフォーク島","노퍽섬"],"NG":["Nigeria","ナイジェリア","나이지리아"],"NI":["Nicaragua","ニカラグア","니카라과"],"NR":["Nauru","ナウル","나우루"],"NU":["Niue","ニウエ","니우에"],"PA":["Panama","パナマ","파나마"],"PF":["French Polynesia","仏領ポリネシア","프랑스령 폴리네시아"],"PG":["Papua New Guinea","パプアニューギニア","파푸아뉴기니"],"PM":["Saint Pierre and Miquelon","サンピエール島・ミクロン島","생피에르 미클롱"],"PR":["Puerto Rico","プエルトリコ","푸에르토리코"],"PY":["Paraguay","パラグアイ","파라과이"],"RE":["Réunion","レユニオン","레위니옹"],"RO":["Romania","ルーマニア","루마니아"],"RS":["Serbia","セルビア","세르비아"],"RW":["Rwanda","ルワンダ","르완다"],"SB":["Solomon Islands","ソロモン諸島","솔로몬 제도"],"SC":["Seychelles","セーシェル","세이셸"],"SD":["Sudan","スーダン","수단"],"SH":["Saint Helena, Ascension and Tristan da Cunha","セントヘレナ・アセンション・トリスタンダクーニャ","세인트헬레나·어센션·트리스탄다쿠냐"],"SI":["Slovenia","スロベニア","슬로베니아"],"SK":["Slovakia","スロバキア","슬로바키아"],"SL":["Sierra Leone","シエラレオネ","시에라리온"],"SN":["Senegal","セネガル","세네갈"],"SO":["Somalia","ソマリア","소말리아"],"SR":["Suriname","スリナム","수리남"],"SS":["South Sudan","南スーダン","남수단"],"ST":["São Tomé and Principe","サントメ・プリンシペ","상투메 프린시페"],"SV":["El Salvador","エルサルバドル","엘살바도르"],"SX":["Sint Maarten","シント・マールテン","신트마르턴"],"SY":["Syria","シリア","시리아"],"SZ":["Eswatini","エスワティニ","에스와티니"],"TC":["Turks and Caicos Islands","タークス・カイコス諸島","터크스 케이커스 제도"],"TD":["Chad","チャド","차드"],"TG":["Togo","トーゴ","토고"],"TJ":["Tajikistan","タジキスタン","타지키스탄"],"TL":["Timor-Leste","東ティモール","동티모르"],"TM":["Turkmenistan","トルクメニスタン","투르크메니스탄"],"TN":["Tunisia","チュニジア","튀니지"],"TO":["Tonga","トンガ","통가"],"TT":["Trinidad and Tobago","トリニダード・トバゴ","트리니다드 토바고"],"TV":["Tuvalu","ツバル","투발루"],"TZ":["Tanzania","タンザニア","탄자니아"],"UG":["Uganda","ウガンダ","우간다"],"UM":["United States Minor Outlying Islands","米領有小離島","미국령 군소 제도"],"UY":["Uruguay","ウルグアイ","우루과이"],"VC":["Saint Vincent and the Grenadines","セントビンセント及びグレナディーン諸島","세인트빈센트 그레나딘"],"VE":["Venezuela","ベネズエラ","베네수엘라"],"VG":["British Virgin Islands","英領バージン諸島","영국령 버진아일랜드"],"VI":["U.S. Virgin Islands","米領バージン諸島","미국령 버진아일랜드"],"VU":["Vanuatu","バヌアツ","바누아투"],"WF":["Wallis and Futuna","ウォリス・フツナ","왈리스 푸투나"],"WS":["Samoa","サモア","사모아"],"XK":["Kosovo","コソボ","코소보"],"YE":["Yemen","イエメン","예멘"],"YT":["Mayotte","マヨット","마요트"],"ZM":["Zambia","ザンビア","잠비아"],"ZW":["Zimbabwe","ジンバブエ","짐바브웨"],"SM":["San Marino","サンマリノ","산마리노"],"MC":["Monaco","モナコ","모나코"],"LI":["Liechtenstein","リヒテンシュタイン","리히텐슈타인"],"PS":["Palestine","パレスチナ","팔레스타인"],"IO":["British Indian Ocean Territory","英領インド洋地域","영국령 인도양 지역"],"AD":["Andorra","アンドラ","안도라"],"AQ":["Antarctica","南極","남극"],"UA":["Ukraine","ウクライナ","우크라이나"]};
window.CITY2=[["DXB",["DXB","DWC"],"AE",["ドバイ","두바이","Dubai"],null],["BUE",["EZE","AEP"],"AR",["ブエノスアイレス","부에노스아이레스","Buenos Aires"],null],["MEL",["MEL","AVV"],"AU",["メルボルン","멜버른","Melbourne"],null],["BRU",["BRU","CRL"],"BE",["ブリュッセル","브뤼셀","Brussels"],null],["BHZ",["CNF","PLU"],"BR",["ベロオリゾンテ","벨루오리존치","Belo Horizonte"],null],["RIO",["GIG","SDU"],"BR",["リオデジャネイロ","리우데자네이루","Rio de Janeiro"],null],["SAO",["GRU","CGH","VCP"],"BR",["サンパウロ","상파울루","São Paulo"],null],["YTO",["YYZ","YTZ"],"CA",["トロント","토론토","Toronto"],null],["BJS",["PEK","PKX"],"CN",["北京","베이징","Beijing"],null],["SHA",["PVG","SHA"],"CN",["上海","상하이","Shanghai"],null],["TCI",["TFS","TFN"],"ES",["テネリフェ","테네리페","Tenerife"],null],["PAR",["CDG","ORY"],"FR",["パリ","파리","Paris"],null],["BFS",["BFS","BHD"],"GB",["ベルファスト","벨파스트","Belfast"],null],["LON",["LHR","LGW","STN","LTN","LCY"],"GB",["ロンドン","런던","London"],null],["JKT",["CGK","HLP"],"ID",["ジャカルタ","자카르타","Jakarta"],null],["JOG",["YIA","JOG"],"ID",["ジョグジャカルタ","족자카르타","Yogyakarta"],null],["THR",["IKA","THR"],"IR",["テヘラン","테헤란","Tehran"],null],["REK",["KEF","RKV"],"IS",["レイキャビク","레이캬비크","Reykjavík"],null],["MIL",["MXP","LIN","BGY"],"IT",["ミラノ","밀라노","Milan"],null],["ROM",["FCO","CIA"],"IT",["ローマ","로마","Rome"],null],["NGO",["NGO","NKM"],"JP",["名古屋","나고야","Nagoya"],["都市コードと中部国際空港のコードが同じ","도시 코드와 주부국제공항 코드가 같음","City code is the same as Chubu Centrair’s code"]],["OSA",["KIX","ITM","UKB"],"JP",["大阪","오사카","Osaka"],null],["SPK",["CTS","OKD"],"JP",["札幌","삿포로","Sapporo"],null],["TYO",["HND","NRT"],"JP",["東京","도쿄","Tokyo"],null],["SEL",["ICN","GMP"],"KR",["ソウル","서울","Seoul"],null],["SLU",["UVF","SLU"],"LC",["セントルシア","세인트루시아","Saint Lucia"],null],["OSL",["OSL","TRF"],"NO",["オスロ","오슬로","Oslo"],null],["MOW",["SVO","DME","VKO"],"RU",["モスクワ","모스크바","Moscow"],null],["STO",["ARN","BMA"],"SE",["ストックホルム","스톡홀름","Stockholm"],null],["DKR",["DSS","DKR"],"SN",["ダカール","다카르","Dakar"],null],["BKK",["BKK","DMK"],"TH",["バンコク","방콕","Bangkok"],null],["ANK",["ESB","ANK"],"TR",["アンカラ","앙카라","Ankara"],null],["IST",["IST","SAW","ISL"],"TR",["イスタンブール","이스탄불","Istanbul"],["ISLは旧アタテュルク空港","ISL은 구 아타튀르크 공항","ISL is the former Atatürk Airport"]],["TPE",["TPE","TSA"],"TW",["台北","타이베이","Taipei"],null],["IEV",["KBP","IEV"],"UA",["キーウ","키이우","Kyiv"],null],["CHI",["ORD","MDW"],"US",["シカゴ","시카고","Chicago"],null],["DFW",["DFW","DAL"],"US",["ダラス","댈러스","Dallas"],["都市コードはDFW（空港と同じ）","도시 코드는 DFW(공항과 같음)","City code DFW (same as the airport)"]],["HOU",["IAH","HOU"],"US",["ヒューストン","휴스턴","Houston"],["都市コードはHOU（ホビー空港と同じ）","도시 코드는 HOU(호비 공항과 같음)","City code HOU (same as Hobby)"]],["NYC",["JFK","LGA"],"US",["ニューヨーク","뉴욕","New York"],["ニューアーク（EWR）は2022年10月1日から運賃計算上のNYCに含まれない","뉴어크(EWR)는 2022년 10월 1일부터 운임 계산상 NYC에 포함되지 않음","Newark (EWR) is not part of NYC for pricing from 1 Oct 2022"]],["WAS",["IAD","DCA"],"US",["ワシントン","워싱턴","Washington"],["ボルチモア（BWI）は含まれない","볼티모어(BWI)는 포함되지 않음","Baltimore (BWI) is not included"]],["JNB",["JNB","HLA"],"ZA",["ヨハネスブルグ","요하네스버그","Johannesburg"],null]];
window.PFX_RG={"A":["南太平洋西部","남태평양 서부","Western South Pacific"],"B":["グリーンランド・アイスランド・コソボ","그린란드·아이슬란드·코소보","Greenland, Iceland, Kosovo"],"C":["カナダ","캐나다","Canada"],"D":["西アフリカ東部・マグレブ","서아프리카 동부·마그레브","Eastern West Africa and Maghreb"],"E":["北ヨーロッパ","북유럽","Northern Europe"],"F":["中部・南部アフリカ、インド洋","중부·남부 아프리카, 인도양","Central and Southern Africa, Indian Ocean"],"G":["西アフリカ西部・マグレブ","서아프리카 서부·마그레브","Western West Africa and Maghreb"],"H":["東アフリカ・北東アフリカ","동아프리카·북동아프리카","East and Northeast Africa"],"K":["アメリカ本土","미국 본토","Contiguous United States"],"L":["南ヨーロッパ・イスラエル・パレスチナ","남유럽·이스라엘·팔레스타인","Southern Europe, Israel, Palestine"],"M":["中米・メキシコ・カリブ海北西部","중미·멕시코·카리브해 북서부","Central America, Mexico, NW Caribbean"],"N":["南太平洋・ニュージーランド","남태평양·뉴질랜드","South Pacific and New Zealand"],"O":["中東・パキスタン","중동·파키스탄","Middle East and Pakistan"],"P":["北太平洋","북태평양","North Pacific"],"R":["日本・韓国・台湾・フィリピン","일본·한국·대만·필리핀","Japan, Korea, Taiwan, Philippines"],"S":["南アメリカ","남아메리카","South America"],"T":["カリブ海東部・南部","카리브해 동부·남부","Eastern and Southern Caribbean"],"U":["旧ソ連（バルト三国・モルドバを除く）","구소련(발트 3국·몰도바 제외)","Former USSR (excl. Baltics, Moldova)"],"V":["南アジア・東南アジア大陸部・香港・マカオ","남아시아·동남아 대륙부·홍콩·마카오","South Asia, mainland SE Asia, Hong Kong, Macau"],"W":["東南アジア島しょ部","동남아 도서부","Maritime Southeast Asia"],"Y":["オーストラリア","호주","Australia"],"Z":["中国・北朝鮮・モンゴル","중국·북한·몽골","China, North Korea, Mongolia"]};
window.PFX2=[["AG",["SB"],null],
["AN",["NR"],null],
["AY",["PG"],null],
["BG",["GL"],null],
["BI",["IS"],null],
["BK",["XK"],null],
["C",["CA"],null],
["DA",["DZ"],null],
["DB",["BJ"],null],
["DF",["BF"],null],
["DG",["GH"],null],
["DI",["CI"],null],
["DN",["NG"],null],
["DR",["NE"],null],
["DT",["TN"],null],
["DX",["TG"],null],
["EB",["BE"],null],
["ED",["DE"],
["民間","민간","civil"]],
["EE",["EE"],null],
["EF",["FI"],null],
["EG",["GB"],
["王室属領を含む","왕실 속령 포함","incl. Crown Dependencies"]],
["EH",["NL"],null],
["EI",["IE"],null],
["EK",["DK","FO"],null],
["EL",["LU"],null],
["EN",["NO"],null],
["EP",["PL"],null],
["ES",["SE"],null],
["ET",["DE"],
["軍用","군용","military"]],
["EV",["LV"],null],
["EY",["LT"],null],
["FA",["ZA"],null],
["FB",["BW"],null],
["FC",["CG"],null],
["FD",["SZ"],null],
["FE",["CF"],null],
["FG",["GQ"],null],
["FH",["SH"],null],
["FI",["MU"],null],
["FJ",["IO"],null],
["FK",["CM"],null],
["FL",["ZM"],null],
["FM",["MG","KM","RE","YT"],null],
["FN",["AO"],null],
["FO",["GA"],null],
["FP",["ST"],null],
["FQ",["MZ"],null],
["FS",["SC"],null],
["FT",["TD"],null],
["FV",["ZW"],null],
["FW",["MW"],null],
["FX",["LS"],null],
["FY",["NA"],null],
["FZ",["CD"],null],
["GA",["ML"],null],
["GB",["GM"],null],
["GC",["ES"],
["カナリア諸島","카나리아 제도","Canary Islands"]],
["GE",["ES"],
["セウタ・メリリャ","세우타·멜리야","Ceuta and Melilla"]],
["GF",["SL"],null],
["GG",["GW"],null],
["GL",["LR"],null],
["GM",["MA"],null],
["GO",["SN"],null],
["GQ",["MR"],null],
["GS",["EH"],null],
["GU",["GN"],null],
["GV",["CV"],null],
["HA",["ET"],null],
["HB",["BI"],null],
["HC",["SO"],null],
["HD",["DJ"],null],
["HE",["EG"],null],
["HH",["ER"],null],
["HJ",["SS"],null],
["HK",["KE"],null],
["HL",["LY"],null],
["HR",["RW"],null],
["HS",["SD"],null],
["HT",["TZ"],null],
["HU",["UG"],null],
["K",["US"],
["本土48州（KJFKのように3レターの前にKを付けることが多い）","본토 48개 주(KJFK처럼 3레터 앞에 K를 붙이는 경우가 많음)","contiguous 48 states (often K + IATA code, e.g. KJFK)"]],
["LA",["AL"],null],
["LB",["BG"],null],
["LC",["CY"],
["英国のアクロティリ・デケリアを含む","영국령 아크로티리·데켈리아 포함","incl. UK Akrotiri and Dhekelia"]],
["LD",["HR"],null],
["LE",["ES"],
["本土・バレアレス諸島","본토·발레아레스 제도","mainland and Balearic Islands"]],
["LF",["FR","PM"],
["本土・サンピエール島・ミクロン島","본토·생피에르 미클롱","mainland and Saint Pierre and Miquelon"]],
["LG",["GR"],null],
["LH",["HU"],null],
["LI",["IT","SM"],null],
["LJ",["SI"],null],
["LK",["CZ"],null],
["LL",["IL"],null],
["LM",["MT"],null],
["LN",["MC"],null],
["LO",["AT"],null],
["LP",["PT"],
["アゾレス・マデイラを含む","아조레스·마데이라 포함","incl. Azores and Madeira"]],
["LQ",["BA"],null],
["LR",["RO"],null],
["LS",["CH","LI"],null],
["LT",["TR"],null],
["LU",["MD"],null],
["LV",["PS"],null],
["LW",["MK"],null],
["LX",["GI"],null],
["LY",["RS","ME"],null],
["LZ",["SK"],null],
["MB",["TC"],null],
["MD",["DO"],null],
["MG",["GT"],null],
["MH",["HN"],null],
["MK",["JM"],null],
["MM",["MX"],null],
["MN",["NI"],null],
["MP",["PA"],null],
["MR",["CR"],null],
["MS",["SV"],null],
["MT",["HT"],null],
["MU",["CU"],null],
["MW",["KY"],null],
["MY",["BS"],null],
["MZ",["BZ"],null],
["NC",["CK"],null],
["NF",["FJ","TO"],null],
["NG",["KI","TV"],
["キリバスはギルバート諸島","키리바시는 길버트 제도","Kiribati: Gilbert Islands"]],
["NI",["NU"],null],
["NL",["WF"],null],
["NS",["WS","AS"],null],
["NT",["PF"],null],
["NV",["VU"],null],
["NW",["NC"],null],
["NZ",["NZ"],
["南極の一部を含む","남극 일부 포함","incl. parts of Antarctica"]],
["OA",["AF"],null],
["OB",["BH"],null],
["OE",["SA"],null],
["OI",["IR"],null],
["OJ",["JO"],
["ヨルダン川西岸を含む","요르단강 서안 포함","incl. the West Bank"]],
["OK",["KW"],null],
["OL",["LB"],null],
["OM",["AE"],null],
["OO",["OM"],null],
["OP",["PK"],null],
["OR",["IQ"],null],
["OS",["SY"],null],
["OT",["QA"],null],
["OY",["YE"],null],
["PA",["US"],
["アラスカ（PA・PF・PO・PP）","알래스카(PA·PF·PO·PP)","Alaska (PA, PF, PO, PP)"]],
["PB",["UM"],
["ベーカー島","베이커섬","Baker Island"]],
["PC",["KI"],
["カントン島（フェニックス諸島）","캔턴섬(피닉스 제도)","Canton Island (Phoenix Islands)"]],
["PF",["US"],
["アラスカ（PA・PF・PO・PP）","알래스카(PA·PF·PO·PP)","Alaska (PA, PF, PO, PP)"]],
["PG",["GU","MP"],null],
["PH",["US"],
["ハワイ","하와이","Hawaii"]],
["PJ",["UM"],
["ジョンストン島","존스턴섬","Johnston Atoll"]],
["PK",["MH"],null],
["PL",["KI"],
["ライン諸島","라인 제도","Line Islands"]],
["PM",["UM"],
["ミッドウェー島","미드웨이섬","Midway Atoll"]],
["PO",["US"],
["アラスカ（PA・PF・PO・PP）","알래스카(PA·PF·PO·PP)","Alaska (PA, PF, PO, PP)"]],
["PP",["US"],
["アラスカ（PA・PF・PO・PP）","알래스카(PA·PF·PO·PP)","Alaska (PA, PF, PO, PP)"]],
["PT",["FM","PW"],null],
["PW",["UM"],
["ウェーク島","웨이크섬","Wake Island"]],
["RC",["TW"],null],
["RJ",["JP"],
["本土（RJTT＝羽田、RJAA＝成田）","본토(RJTT=하네다, RJAA=나리타)","mainland (RJTT Haneda, RJAA Narita)"]],
["RK",["KR"],
["RKSI＝仁川、RKSS＝金浦","RKSI=인천, RKSS=김포","RKSI Incheon, RKSS Gimpo"]],
["RO",["JP"],
["沖縄（ROAH＝那覇）","오키나와(ROAH=나하)","Okinawa (ROAH Naha)"]],
["RP",["PH"],null],
["SA",["AR"],
["南極の一部を含む","남극 일부 포함","incl. parts of Antarctica"]],
["SB",["BR"],
["※SB・SD・SI・SJ・SN・SS・SWもブラジル","※SB·SD·SI·SJ·SN·SS·SW 모두 브라질","Brazil also uses SB, SD, SI, SJ, SN, SS, SW"]],
["SC",["CL"],
["イースター島・南極の一部を含む ※SHもチリ","이스터섬·남극 일부 포함 ※SH도 칠레","incl. Easter Island and parts of Antarctica; also SH"]],
["SD",["BR"],
["※SB・SD・SI・SJ・SN・SS・SWもブラジル","※SB·SD·SI·SJ·SN·SS·SW 모두 브라질","Brazil also uses SB, SD, SI, SJ, SN, SS, SW"]],
["SE",["EC"],null],
["SF",["FK"],null],
["SG",["PY"],null],
["SH",["CL"],null],
["SI",["BR"],
["※SB・SD・SI・SJ・SN・SS・SWもブラジル","※SB·SD·SI·SJ·SN·SS·SW 모두 브라질","Brazil also uses SB, SD, SI, SJ, SN, SS, SW"]],
["SJ",["BR"],
["※SB・SD・SI・SJ・SN・SS・SWもブラジル","※SB·SD·SI·SJ·SN·SS·SW 모두 브라질","Brazil also uses SB, SD, SI, SJ, SN, SS, SW"]],
["SK",["CO"],null],
["SL",["BO"],null],
["SM",["SR"],null],
["SN",["BR"],
["※SB・SD・SI・SJ・SN・SS・SWもブラジル","※SB·SD·SI·SJ·SN·SS·SW 모두 브라질","Brazil also uses SB, SD, SI, SJ, SN, SS, SW"]],
["SO",["GF"],null],
["SP",["PE"],null],
["SS",["BR"],
["※SB・SD・SI・SJ・SN・SS・SWもブラジル","※SB·SD·SI·SJ·SN·SS·SW 모두 브라질","Brazil also uses SB, SD, SI, SJ, SN, SS, SW"]],
["SU",["UY"],null],
["SV",["VE"],null],
["SW",["BR"],
["※SB・SD・SI・SJ・SN・SS・SWもブラジル","※SB·SD·SI·SJ·SN·SS·SW 모두 브라질","Brazil also uses SB, SD, SI, SJ, SN, SS, SW"]],
["SY",["GY"],null],
["TA",["AG"],null],
["TB",["BB"],null],
["TD",["DM"],null],
["TF",["GP","MQ","BL","MF"],null],
["TG",["GD"],null],
["TI",["VI"],null],
["TJ",["PR"],null],
["TK",["KN"],null],
["TL",["LC"],null],
["TN",["BQ","AW","CW","SX"],null],
["TQ",["AI"],null],
["TR",["MS"],null],
["TT",["TT"],null],
["TU",["VG"],null],
["TV",["VC"],null],
["TX",["BM"],null],
["UA",["KZ"],null],
["UB",["AZ"],null],
["UC",["KG"],null],
["UD",["AM"],null],
["UE",["RU"],
["サハ共和国（ヤクーチア）","사하 공화국(야쿠티야)","Yakutia"]],
["UG",["GE"],null],
["UH",["RU"],
["極東","극동","Far East"]],
["UI",["RU"],
["東シベリア","동시베리아","Eastern Siberia"]],
["UK",["UA"],null],
["UL",["RU"],
["北西部","북서부","Northwest"]],
["UM",["BY","RU"],
["ロシアはカリーニングラード","러시아는 칼리닌그라드","Russia: Kaliningrad"]],
["UN",["RU"],
["西シベリア","서시베리아","Western Siberia"]],
["UO",["RU"],
["中部シベリア","중부 시베리아","Central Siberia"]],
["UR",["RU"],
["南部","남부","South"]],
["US",["RU"],
["ウラル","우랄","Urals"]],
["UT",["TJ","TM"],null],
["UU",["RU"],
["中部","중부","Central"]],
["UW",["RU"],
["ヴォルガ","볼가","Volga"]],
["UZ",["UZ"],
["2025年10月2日にUTからUZへ変更","2025년 10월 2일 UT에서 UZ로 변경","changed from UT to UZ on 2 October 2025"]],
["VA",["IN"],
["西部","서부","West"]],
["VC",["LK"],null],
["VD",["KH"],null],
["VE",["IN"],
["東部","동부","East"]],
["VG",["BD"],null],
["VH",["HK"],null],
["VI",["IN"],
["北部","북부","North"]],
["VL",["LA"],null],
["VM",["MO"],null],
["VN",["NP"],null],
["VO",["IN"],
["南部","남부","South"]],
["VQ",["BT"],null],
["VR",["MV"],null],
["VT",["TH"],null],
["VV",["VN"],null],
["VY",["MM"],null],
["WA",["ID"],
["※WA・WI・WQ・WRもインドネシア","※WA·WI·WQ·WR 모두 인도네시아","Indonesia also uses WA, WI, WQ, WR"]],
["WB",["BN","MY"],
["マレーシアはサバ・サラワク","말레이시아는 사바·사라왁","Malaysia: Sabah and Sarawak"]],
["WI",["ID"],
["※WA・WI・WQ・WRもインドネシア","※WA·WI·WQ·WR 모두 인도네시아","Indonesia also uses WA, WI, WQ, WR"]],
["WM",["MY"],
["マレー半島","말레이반도","Peninsular Malaysia"]],
["WP",["TL"],null],
["WQ",["ID"],
["※WA・WI・WQ・WRもインドネシア","※WA·WI·WQ·WR 모두 인도네시아","Indonesia also uses WA, WI, WQ, WR"]],
["WR",["ID"],
["※WA・WI・WQ・WRもインドネシア","※WA·WI·WQ·WR 모두 인도네시아","Indonesia also uses WA, WI, WQ, WR"]],
["WS",["SG"],null],
["Y",["AU"],
["ノーフォーク島・クリスマス島・ココス諸島などを含む","노퍽섬·크리스마스섬·코코스 제도 등 포함","incl. Norfolk, Christmas and Cocos Islands"]],
["ZB",["CN"],
["華北（ZBAA＝北京首都）","화북(ZBAA=베이징 서우두)","North (ZBAA Beijing Capital)"]],
["ZG",["CN"],
["華南","화남","South"]],
["ZH",["CN"],
["華中","화중","Central"]],
["ZJ",["CN"],
["海南","하이난","Hainan"]],
["ZK",["KP"],null],
["ZL",["CN"],
["西北","서북","Northwest"]],
["ZM",["MN"],null],
["ZP",["CN"],
["雲南","윈난","Yunnan"]],
["ZS",["CN"],
["華東（ZSPD＝上海浦東）","화동(ZSPD=상하이 푸둥)","East (ZSPD Shanghai Pudong)"]],
["ZU",["CN"],
["西南","서남","Southwest"]],
["ZW",["CN"],
["新疆","신장","Xinjiang"]],
["ZY",["CN"],
["東北","동북","Northeast"]]];
window.REG=[["YA",["AF"],null],
["ZA",["AL"],null],
["7T",["DZ"],null],
["C3",["AD"],null],
["D2",["AO"],null],
["VP-A",["AI"],null],
["V2",["AG"],null],
["LV",["AR"],null],
["EK",["AM"],null],
["P4",["AW"],null],
["VH",["AU"],
["例：VH-OQA","예: VH-OQA","e.g. VH-OQA"]],
["OE",["AT"],null],
["4K",["AZ"],null],
["C6",["BS"],null],
["A9C",["BH"],null],
["S2",["BD"],null],
["8P",["BB"],null],
["EW",["BY"],null],
["OO",["BE"],null],
["V3",["BZ"],null],
["TY",["BJ"],null],
["VP-B・VQ-B",["BM"],
["リースの旅客機が多く登録される","리스 여객기가 많이 등록됨","widely used for leased airliners"]],
["A5",["BT"],null],
["CP",["BO"],null],
["E7",["BA"],null],
["A2",["BW"],null],
["PP・PR・PS・PT・PU",["BR"],
["PUは超軽量機など","PU는 초경량기 등","PU: ultralights etc."]],
["VP-L",["VG"],null],
["V8",["BN"],null],
["LZ",["BG"],null],
["XT",["BF"],null],
["9U",["BI"],null],
["XU",["KH"],null],
["TJ",["CM"],null],
["C",["CA"],
["C-F・C-G・C-Iと英字3文字","C-F·C-G·C-I와 영문자 3글자","C-F, C-G or C-I + 3 letters"]],
["D4",["CV"],null],
["VP-C・VQ-C",["KY"],null],
["TL",["CF"],null],
["TT",["TD"],null],
["CC",["CL"],null],
["B",["CN"],
["中国本土：B-と4文字（数字、2018年から英字も）","중국 본토: B-와 4글자(숫자, 2018년부터 영문자도)","mainland China: B- + 4 characters (digits; letters allowed since 2018)"]],
["HK・HJ",["CO"],
["HJは超軽量機","HJ는 초경량기","HJ: microlights"]],
["D6",["KM"],null],
["TN",["CG"],null],
["9S",["CD"],null],
["E5",["CK"],null],
["TI",["CR"],null],
["9A",["HR"],null],
["CU",["CU"],null],
["5B",["CY"],null],
["OK",["CZ"],null],
["OY",["DK"],null],
["J2",["DJ"],null],
["J7",["DM"],null],
["HI",["DO"],null],
["4W",["TL"],null],
["HC",["EC"],null],
["SU",["EG"],null],
["YS",["SV"],null],
["3C",["GQ"],null],
["E3",["ER"],null],
["ES",["EE"],null],
["3DC",["SZ"],null],
["ET",["ET"],null],
["VP-F",["FK"],null],
["DQ",["FJ"],null],
["OH",["FI"],null],
["F",["FR"],
["海外領土の拠点機はF-O","해외 영토 거점 기체는 F-O","F-O for aircraft based overseas"]],
["TR",["GA"],null],
["C5",["GM"],null],
["4L",["GE"],null],
["D",["DE"],
["2文字目で重さの区分（D-A＝20t超）","두 번째 글자로 무게 구분(D-A=20t 초과)","second letter shows weight class (D-A: over 20 t)"]],
["9G",["GH"],null],
["VP-G",["GI"],null],
["SX",["GR"],null],
["J3",["GD"],null],
["TG",["GT"],null],
["2",["GG"],null],
["3X",["GN"],null],
["J5",["GW"],null],
["8R",["GY"],null],
["HH",["HT"],null],
["HR",["HN"],null],
["B-H・B-K・B-L",["HK"],
["B-H・B-K・B-Lと英字2文字","B-H·B-K·B-L과 영문자 2글자","B-H, B-K or B-L + 2 letters"]],
["HA",["HU"],null],
["TF",["IS"],null],
["VT",["IN"],null],
["PK",["ID"],null],
["EP",["IR"],null],
["YI",["IQ"],null],
["EI・EJ",["IE"],
["リースの旅客機が多く登録される","리스 여객기가 많이 등록됨","widely used for leased airliners"]],
["M",["IM"],null],
["4X",["IL"],null],
["I",["IT"],null],
["TU",["CI"],null],
["6Y",["JM"],null],
["JA",["JP"],
["ハイフンなしで4文字（例：JA801A）","하이픈 없이 4글자(예: JA801A)","no hyphen, 4 characters (e.g. JA801A)"]],
["JR",["JP"],
["超軽量動力機・自作機など","초경량 동력기·자작기 등","ultralights and homebuilts"]],
["JY",["JO"],null],
["UP",["KZ"],null],
["5Y",["KE"],null],
["T3",["KI"],null],
["Z6",["XK"],null],
["9K",["KW"],null],
["EX",["KG"],null],
["RDPL",["LA"],null],
["YL",["LV"],null],
["OD",["LB"],null],
["7P",["LS"],null],
["A8",["LR"],null],
["5A",["LY"],null],
["HB",["CH","LI"],
["国の紋章を添える","국가 문장을 함께 표시","shown with the national emblem"]],
["LY",["LT"],null],
["LX",["LU"],null],
["B-M",["MO"],null],
["5R",["MG"],null],
["7Q",["MW"],null],
["9M",["MY"],null],
["8Q",["MV"],null],
["TZ",["ML"],null],
["9H",["MT"],
["リースの機体も多く登録される","리스 기체도 많이 등록됨","many leased aircraft"]],
["V7",["MH"],null],
["5T",["MR"],null],
["3B",["MU"],null],
["XA・XB・XC",["MX"],
["XA＝商業、XB＝自家用、XC＝政府","XA=상업, XB=자가용, XC=정부","XA commercial, XB private, XC government"]],
["V6",["FM"],null],
["ER",["MD"],null],
["3A",["MC"],null],
["JU",["MN"],null],
["4O",["ME"],null],
["VP-M",["MS"],null],
["CN",["MA"],null],
["C9",["MZ"],null],
["XY・XZ",["MM"],null],
["V5",["NA"],null],
["C2",["NR"],null],
["9N",["NP"],null],
["PH",["NL"],null],
["PJ",["CW","SX"],null],
["ZK・ZL・ZM",["NZ"],null],
["YN",["NI"],null],
["5U",["NE"],null],
["5N",["NG"],null],
["P",["KP"],null],
["Z3",["MK"],null],
["LN",["NO"],null],
["A4O",["OM"],null],
["AP",["PK"],null],
["HP",["PA"],null],
["P2",["PG"],null],
["ZP",["PY"],null],
["OB",["PE"],null],
["RP",["PH"],
["旅客機はRP-Cと数字4けた","여객기는 RP-C와 숫자 4자리","airliners: RP-C + 4 digits"]],
["SP",["PL"],null],
["CS",["PT"],null],
["A7",["QA"],null],
["YR",["RO"],null],
["RA",["RU"],null],
["9XR",["RW"],null],
["VQ-H",["SH"],null],
["V4",["KN"],null],
["J6",["LC"],null],
["J8",["VC"],null],
["5W",["WS"],null],
["T7",["SM"],null],
["S9",["ST"],null],
["HZ",["SA"],null],
["6V・6W",["SN"],null],
["YU",["RS"],null],
["S7",["SC"],null],
["9L",["SL"],null],
["9V",["SG"],null],
["OM",["SK"],null],
["S5",["SI"],null],
["H4",["SB"],null],
["6O",["SO"],null],
["ZS・ZT・ZU",["ZA"],null],
["HL",["KR"],
["ハイフンを付けない（HLと数字4けた）","하이픈 없이 HL과 숫자 4자리","no hyphen, HL + 4 digits"]],
["Z8",["SS"],null],
["EC",["ES"],null],
["4R",["LK"],null],
["ST",["SD"],null],
["PZ",["SR"],null],
["SE",["SE"],null],
["YK",["SY"],null],
["B",["TW"],
["台湾：B-と数字5けた（例：B-18901）","대만: B-와 숫자 5자리(예: B-18901)","Taiwan: B- + 5 digits (e.g. B-18901)"]],
["EY",["TJ"],null],
["5H",["TZ"],null],
["HS",["TH"],null],
["5V",["TG"],null],
["A3",["TO"],null],
["9Y",["TT"],null],
["TS",["TN"],null],
["TC",["TR"],null],
["EZ",["TM"],null],
["VQ-T",["TC"],null],
["T2",["TV"],null],
["5X",["UG"],null],
["UR",["UA"],null],
["A6",["AE"],null],
["G",["GB"],null],
["N",["US"],
["ハイフンなし、Nと最大5文字（例：N12345）","하이픈 없이 N과 최대 5글자(예: N12345)","no hyphen, N + up to 5 characters (e.g. N12345)"]],
["CX",["UY"],null],
["UK",["UZ"],null],
["YJ",["VU"],null],
["YV",["VE"],null],
["VN",["VN"],
["ジェット旅客機はVN-Aと数字3けた","제트 여객기는 VN-A와 숫자 3자리","jetliners: VN-A + 3 digits"]],
["7O",["YE"],null],
["9J",["ZM"],null],
["Z",["ZW"],null]];
