/* 航空用語辞典 第3部：貨物／危険物／保安／安全／機体・整備／気象／機関・条約／電報・コード／経営・営業 */
window.DICT=(window.DICT||[]).concat([
["CGO","Air Waybill (AWB)","航空運送状（AWB）","항공화물운송장(AWB)","航空貨物の契約と受取を示す書類。11桁の番号","항공화물의 계약과 수령을 나타내는 서류. 11자리 번호","The air cargo contract and receipt, with an 11-digit number"],
["CGO","House Air Waybill (HAWB)","混載貨物の運送状（HAWB）","혼재화물 운송장(HAWB)","フォワーダーが荷主ごとに発行する運送状","포워더가 화주별로 발행하는 운송장","The waybill a forwarder issues to each shipper in a consolidation"],
["CGO","Freight Forwarder","フォワーダー（利用運送事業者）","포워더(운송주선인)","荷主から貨物を集めて航空会社に運送を頼む事業者","화주에게서 화물을 모아 항공사에 운송을 맡기는 사업자","A company arranging air transport for shippers"],
["CGO","Consolidation","混載","혼재","複数の荷主の貨物を1つにまとめて運ぶこと","여러 화주의 화물을 하나로 묶어 운송하는 것","Combining several shippers’ goods into one shipment"],
["CGO","Chargeable Weight","運賃計算重量","운임 적용 중량","実重量と容積重量の大きい方","실중량과 용적중량 중 큰 쪽","The greater of actual weight and volumetric weight"],
["CGO","Volumetric Weight","容積重量","용적 중량","大きさから計算する重さ（一般に縦×横×高さ（cm）÷6000）","크기로 계산하는 무게(보통 가로×세로×높이(cm)÷6000)","Weight from dimensions, commonly L×W×H in cm divided by 6000"],
["CGO","Cargo Manifest","積荷目録","적하목록","便に積んだ貨物の一覧。税関に提出する","편에 실은 화물 목록. 세관에 제출","The list of cargo on a flight, submitted to customs"],
["CGO","Bonded Area","保税地域","보세구역","輸入の手続きが済むまで貨物を置く税関の管理区域","수입 절차가 끝날 때까지 화물을 두는 세관 관리 구역","A customs-controlled area for goods not yet cleared"],
["CGO","Known Consignor / Regulated Agent","特定荷主・特定航空貨物利用運送事業者","지정 화주·보안 승인 운송업자","保安の基準を満たし、貨物の保安を確保できると認められた荷主・事業者","보안 기준을 충족해 화물 보안을 확보할 수 있다고 인정된 화주·사업자","Shippers and agents approved as meeting cargo security standards"],
["CGO","Perishable Cargo (PER)","生鮮貨物","신선 화물","食品・花など温度と時間に注意が必要な貨物","식품·꽃 등 온도와 시간에 주의가 필요한 화물","Goods such as food and flowers needing temperature and time control"],
["CGO","Live Animals (AVI)","生きた動物（AVI）","살아 있는 동물(AVI)","IATAの規則に沿って運ぶ動物の貨物","IATA 규칙에 따라 운송하는 동물 화물","Animals carried under the IATA Live Animals Regulations"],
["CGO","Human Remains (HUM)","遺体（HUM）","유해(HUM)","棺や遺骨を運ぶ特別な貨物","관이나 유골을 운송하는 특별 화물","Coffins or ashes carried as special cargo"],
["CGO","Valuable Cargo (VAL)","貴重品貨物（VAL）","귀중품 화물(VAL)","現金・貴金属など特別な管理が必要な貨物","현금·귀금속 등 특별 관리가 필요한 화물","Cash, precious metals and other high-value goods"],
["CGO","Belly Cargo","旅客便の貨物室の貨物（ベリー）","여객기 하부 화물(벨리)","旅客便の床下の貨物室で運ぶ貨物","여객기 바닥 아래 화물칸으로 운송하는 화물","Cargo carried in the lower holds of passenger aircraft"],
["CGO","Freighter","貨物専用機","화물 전용기","貨物だけを運ぶ機体","화물만 운송하는 기체","An aircraft that carries only cargo"],
["DG","Dangerous Goods Regulations (DGR)","危険物規則書（DGR）","위험물 규정(DGR)","IATAが発行する危険物輸送の規則書","IATA가 발행하는 위험물 운송 규정","IATA’s manual for carrying dangerous goods by air"],
["DG","ICAO Technical Instructions (TI)","ICAO技術指針","ICAO 기술지침","危険物の航空輸送の国際的な基準","위험물 항공 운송의 국제 기준","The international legal standard for dangerous goods by air"],
["DG","UN Number","国連番号","유엔 번호","危険物を特定する4桁の番号（例：UN3480）","위험물을 특정하는 4자리 번호(예: UN3480)","The four-digit number identifying a dangerous substance"],
["DG","Proper Shipping Name","正式品名","정식 운송품명","危険物を表す決められた名前","위험물을 나타내는 정해진 이름","The standard name used to describe a dangerous good"],
["DG","Packing Group","容器等級","용기 등급","危険の度合いを示す区分（I・II・III）","위험 정도를 나타내는 구분(I·II·III)","Degree of danger: I high, II medium, III low"],
["DG","Shipper’s Declaration for Dangerous Goods","危険物申告書","위험물 신고서","荷主が危険物の内容を申告する書類","화주가 위험물 내용을 신고하는 서류","The shipper’s signed declaration of dangerous goods"],
["DG","Hazard Label","危険性ラベル","위험성 라벨","危険物の分類を示すひし形のラベル","위험물 분류를 나타내는 마름모 라벨","The diamond-shaped label showing the hazard class"],
["DG","Cargo Aircraft Only (CAO)","貨物専用機限定","화물기 전용","旅客便では運べず、貨物専用機でのみ運べる危険物","여객기로는 운송할 수 없고 화물기로만 운송할 수 있는 위험물","Dangerous goods permitted only on freighters"],
["DG","Hidden Dangerous Goods","隠れた危険物","숨은 위험물","申告のない荷物に含まれる危険物","신고 없는 짐에 들어 있는 위험물","Dangerous goods concealed in undeclared items"],
["DG","Watt-hour Rating (Wh)","ワット時定格量","와트시 정격용량","リチウムイオン電池の容量。mAh×V÷1000","리튬이온 배터리 용량. mAh×V÷1000","Lithium-ion battery capacity: mAh × V ÷ 1000"],
["DG","Lithium Metal / Lithium Ion","リチウム金属電池・リチウムイオン電池","리튬 메탈·리튬이온 배터리","使い切り型（金属）と充電式（イオン）。規則が違う","일회용(메탈)과 충전식(이온). 규칙이 다르다","Non-rechargeable (metal) and rechargeable (ion) cells, with different rules"],
["DG","Dangerous Goods Occurrence Report","危険物事故・インシデント報告","위험물 사고·준사고 보고","危険物に関する事故などの当局への報告","위험물 관련 사고 등의 당국 보고","The report to authorities of a dangerous goods occurrence"],
["SEC","ICAO Annex 17","ICAO第17附属書（保安）","ICAO 부속서 17(보안)","国際民間航空の保安の国際基準","국제민간항공 보안의 국제 기준","The international standards for aviation security"],
["SEC","Aviation Security Programme","航空保安計画","항공보안계획","航空会社・空港が作る保安の措置の計画","항공사·공항이 만드는 보안 조치 계획","The security measures an airline or airport must follow"],
["SEC","Screening","保安検査","보안검색","お客様・手荷物・貨物に危険な物がないかを調べること","승객·수하물·화물에 위험물이 없는지 조사하는 것","Checking people, bags and cargo for prohibited items"],
["SEC","Hold Baggage Screening (HBS)","預け手荷物の検査（HBS）","위탁 수하물 검색(HBS)","預けた手荷物をX線などで検査すること","위탁 수하물을 X선 등으로 검사하는 것","Screening checked bags by X-ray and other means"],
["SEC","Explosive Detection System (EDS)","爆発物検知装置（EDS）","폭발물 탐지 장비(EDS)","手荷物の爆発物を自動で見つける装置","수하물 속 폭발물을 자동으로 찾는 장비","Equipment that automatically detects explosives in bags"],
["SEC","Liquids, Aerosols and Gels (LAGs)","液体物の制限（LAGs）","액체류 제한(LAGs)","国際線の機内持ち込みの液体の制限（1容器100ml等）","국제선 기내 반입 액체 제한(1용기 100ml 등)","Limits on liquids in cabin baggage, such as 100 ml per container"],
["SEC","Security Tamper-Evident Bag (STEB)","不正開封防止袋（STEB）","개봉 방지 봉투(STEB)","免税店の液体を入れる、開けると分かる袋","면세점 액체를 넣는, 열면 알 수 있는 봉투","The sealed bag for duty-free liquids"],
["SEC","Restricted Area Pass","制限区域の立入証","보호구역 출입증","制限区域に入る人が身に着ける許可証","보호구역에 들어가는 사람이 착용하는 허가증","The pass worn to enter restricted areas"],
["SEC","Sensitive Security Information (SSI)","保安上の機密情報","보안 민감 정보","外に出すと保安を弱める情報","외부로 나가면 보안을 약하게 하는 정보","Information that would weaken security if disclosed"],
["SEC","Aircraft Security Search","機体の保安捜索","항공기 보안 수색","機内・貨物室に不審物がないかを調べること","기내·화물칸에 수상한 물건이 없는지 조사하는 것","Searching the aircraft for suspicious items"],
["SEC","Unruly Passenger","迷惑・不法行為のお客様","기내 난동 승객","機内で乗務員の指示に従わず安全を損なうお客様","기내에서 승무원 지시에 따르지 않고 안전을 해치는 승객","A passenger whose behaviour threatens safety or good order on board"],
["SAF","ICAO Annex 19","ICAO第19附属書（安全管理）","ICAO 부속서 19(안전관리)","安全管理（SMS）の国際基準","안전관리(SMS)의 국제 기준","The international standards for safety management"],
["SAF","State Safety Programme (SSP)","国家安全プログラム","국가항공안전프로그램","国が定める安全管理の枠組み","국가가 정하는 안전관리 틀","A state’s overall framework for managing aviation safety"],
["SAF","Hazard","ハザード（危険の芽）","위해 요인","事故につながるおそれのある状態・物事","사고로 이어질 수 있는 상태·사물","A condition or object that could cause harm"],
["SAF","Risk Assessment","リスク評価","위험도 평가","起こりやすさと重大さからリスクを評価すること","발생 가능성과 심각도로 위험을 평가하는 것","Evaluating risk by likelihood and severity"],
["SAF","Near Miss","ヒヤリ・ハット","아차 사고","事故にならなかったが危なかった出来事","사고가 되지 않았지만 위험했던 일","An event that could have caused harm but did not"],
["SAF","Just Culture","公正な文化","공정한 문화","正直な報告を責めず、無謀な行為には厳正に対応する考え方","정직한 보고는 비난하지 않고 무모한 행위에는 엄정히 대응하는 사고방식","Not blaming honest mistakes while acting firmly on recklessness"],
["SAF","Human Factors","ヒューマンファクター","인적 요인","人の能力と限界が安全に与える影響","사람의 능력과 한계가 안전에 주는 영향","How human abilities and limits affect safety"],
["SAF","Dirty Dozen","ダーティ・ダズン（12の要因）","더티 더즌(12가지 요인)","整備で知られるヒューマンエラーの12の原因（疲労・慢心など）","정비에서 알려진 휴먼 에러의 12가지 원인(피로·자만 등)","Twelve common causes of human error, such as fatigue and complacency"],
["SAF","IATA Safety Audit for Ground Operations (ISAGO)","ISAGO（地上業務の安全監査）","ISAGO(지상조업 안전 감사)","IATAによるハンドリング会社の安全監査の制度","IATA의 지상조업사 안전 감사 제도","IATA’s safety audit programme for ground handlers"],
["SAF","IATA Operational Safety Audit (IOSA)","IOSA（航空会社の運航安全監査）","IOSA(항공사 운항 안전 감사)","IATAによる航空会社の運航安全の監査","IATA의 항공사 운항 안전 감사","IATA’s safety audit of airline operations"],
["SAF","IATA Ground Operations Manual (IGOM)","IGOM（地上業務の標準手順書）","IGOM(지상조업 표준 매뉴얼)","IATAが定める地上業務の標準の手順","IATA가 정하는 지상조업 표준 절차","IATA’s standard procedures for ground operations"],
["SAF","Airport Handling Manual (AHM)","AHM（空港ハンドリングマニュアル）","AHM(공항 조업 매뉴얼)","IATAの地上業務の方針・様式・規格の手引き","IATA의 지상조업 방침·양식·규격 지침","IATA’s reference on ground handling policies, forms and standards"],
["MX","Aircraft Registration","機体の登録記号","기체 등록 기호","国ごとの接頭記号がある機体の番号（日本はJA、韓国はHL）","나라별 접두 기호가 있는 기체 번호(일본 JA, 한국 HL)","The aircraft’s registration mark, with a national prefix"],
["MX","Narrow-body / Wide-body","単通路機・双通路機","단일 통로기·이중 통로기","客室の通路が1本の機体と2本の機体","객실 통로가 1개인 기체와 2개인 기체","Aircraft with one aisle and with two aisles"],
["MX","Line Maintenance","ライン整備","라인 정비","便と便の間に空港で行う点検・整備","편과 편 사이에 공항에서 하는 점검·정비","Checks and repairs done at the airport between flights"],
["MX","Heavy Maintenance (C-check / D-check)","重整備（C整備・D整備）","중정비(C체크·D체크)","格納庫で機体を長く止めて行う大きな整備","격납고에서 기체를 오래 세워 두고 하는 큰 정비","Major maintenance done in a hangar over days or weeks"],
["MX","Technical Log","技術記録（テックログ）","기술 일지(테크 로그)","機体の不具合と整備の処置を記録する帳票","기체 결함과 정비 조치를 기록하는 장부","The record of defects and the maintenance action taken"],
["MX","Certificate of Release to Service (CRS)","整備完了の確認","정비 완료 확인","整備士が機体を運航に戻してよいと確認すること","정비사가 기체를 운항에 복귀해도 된다고 확인하는 것","The engineer’s certification that an aircraft is fit to fly"],
["MX","Airworthiness","耐空性","감항성","機体が安全に飛べる状態であること","기체가 안전하게 비행할 수 있는 상태","The condition of being safe to fly"],
["MX","Bird Strike","バードストライク","조류 충돌","鳥が機体に衝突すること","새가 기체에 충돌하는 것","A collision between an aircraft and a bird"],
["MX","Emergency Slide","脱出用スライド","비상 탈출 슬라이드","非常時にドアから展開する滑り台","비상시 도어에서 펼쳐지는 미끄럼대","The inflatable slide deployed from a door in an emergency"],
["MX","Armed / Disarmed","アーム・ディスアーム","암드·디스암드","スライドが作動する状態／しない状態","슬라이드가 작동하는 상태/작동하지 않는 상태","Door slide set to deploy, or not"],
["WX","METAR","METAR（定時の空港気象）","METAR(정시 공항 기상)","空港の定時の気象の観測の電文","공항 정시 기상 관측 전문","Routine airport weather observation"],
["WX","TAF","TAF（空港の予報）","TAF(공항 예보)","空港の気象の予報の電文","공항 기상 예보 전문","Terminal aerodrome forecast"],
["WX","SIGMET","SIGMET（重要な気象の情報）","SIGMET(위험 기상 정보)","乱気流・火山灰など航空に危険な気象の情報","난기류·화산재 등 항공에 위험한 기상 정보","Warnings of weather hazardous to aircraft, such as turbulence or ash"],
["WX","Wind Shear","ウインドシア","윈드시어","短い距離で風向・風速が急に変わること","짧은 거리에서 풍향·풍속이 급변하는 것","A sudden change in wind speed or direction over a short distance"],
["WX","Clear Air Turbulence (CAT)","晴天乱気流","청천 난기류","雲のない高い空で起きる乱気流","구름 없는 높은 하늘에서 일어나는 난기류","Turbulence in clear air at high altitude"],
["WX","Volcanic Ash","火山灰","화산재","エンジンに深刻な損傷を与えるため、避けて飛ぶ","엔진에 심각한 손상을 주므로 피해서 비행","Ash that can seriously damage engines, avoided in flight"],
["WX","Visibility / RVR","視程・滑走路視距離（RVR）","시정·활주로 가시거리(RVR)","見通せる距離と、滑走路に沿って見える距離","볼 수 있는 거리와 활주로를 따라 보이는 거리","Visibility, and the visual range along the runway"],
["ORG","International Civil Aviation Organization (ICAO)","国際民間航空機関（ICAO）","국제민간항공기구(ICAO)","国際民間航空の基準を定める国連の専門機関","국제민간항공 기준을 정하는 유엔 전문기구","The UN agency setting international civil aviation standards"],
["ORG","International Air Transport Association (IATA)","国際航空運送協会（IATA）","국제항공운송협회(IATA)","世界の航空会社の業界団体。規格と精算の仕組みを運営","세계 항공사의 업계 단체. 규격과 정산 체계를 운영","The global airline trade association, running standards and settlement"],
["ORG","Chicago Convention","シカゴ条約","시카고 협약","国際民間航空の基本を定めた条約（1944年）","국제민간항공의 기본을 정한 협약(1944년)","The 1944 treaty founding international civil aviation law"],
["ORG","Freedoms of the Air","空の自由","하늘의 자유","他国の上空通過・運航などの権利の区分（第1〜第9）","타국 상공 통과·운항 등 권리의 구분(제1~제9)","The rights to overfly and serve other countries, first to ninth"],
["ORG","Air Services Agreement (ASA)","航空協定","항공협정","2国間で路線・便数・航空会社の数などを決める協定","두 나라 사이에 노선·편수·항공사 수 등을 정하는 협정","A bilateral agreement on routes, frequencies and airlines"],
["ORG","Open Skies","オープンスカイ","오픈스카이","路線・便数の制限をなくす航空自由化の協定","노선·편수 제한을 없애는 항공 자유화 협정","Agreements removing limits on routes and frequencies"],
["ORG","Civil Aviation Bureau (JCAB)","国土交通省航空局（JCAB）","일본 국토교통성 항공국(JCAB)","日本の航空行政を担う国の機関","일본의 항공 행정을 담당하는 국가 기관","Japan’s civil aviation authority"],
["ORG","Airline Alliance","航空連合（アライアンス）","항공 동맹(얼라이언스)","航空会社どうしの提携の連合","항공사끼리의 제휴 연합","A group of airlines cooperating on networks and loyalty"],
["ORG","Low-cost Carrier (LCC) / Full-service Carrier (FSC)","LCC・FSC","저비용항공사·대형항공사","運賃を安くし付帯サービスを有料にする会社と、サービス込みの会社","운임을 낮추고 부가 서비스를 유료로 하는 회사와 서비스 포함 회사","Low-cost airlines charging for extras, and full-service airlines"],
["MSG","Teletype Message (Type B)","航空電報（タイプB）","항공 전보(Type B)","航空会社・空港の間でやり取りする決まった形式の電報","항공사·공항 간 주고받는 정해진 형식의 전보","Standard-format messages exchanged between airlines and airports"],
["MSG","Movement Message (MVT)","運航実績電報（MVT）","운항 실적 전보(MVT)","出発・到着の時刻や遅延を知らせる電報","출발·도착 시각이나 지연을 알리는 전보","Message reporting departure, arrival and delay times"],
["MSG","Load Distribution Message (LDM)","搭載量電報（LDM）","탑재량 전보(LDM)","便の搭載量を到着地へ知らせる電報","편의 탑재량을 도착지에 알리는 전보","Message telling the destination the load on the flight"],
["MSG","Container/Pallet Distribution Message (CPM)","コンテナ搭載電報（CPM）","컨테이너 탑재 전보(CPM)","コンテナ・パレットの搭載位置を知らせる電報","컨테이너·팔레트 탑재 위치를 알리는 전보","Message giving the positions of ULDs on board"],
["MSG","Passenger Transfer Message (PTM)","乗り継ぎ旅客電報（PTM）","환승 여객 전보(PTM)","乗り継ぎのお客様と手荷物の情報を送る電報","환승 승객과 수하물 정보를 보내는 전보","Message listing transfer passengers and bags"],
["MSG","Passenger Service Message (PSM)","特別対応旅客電報（PSM）","특별 여객 전보(PSM)","車いすなど特別対応のお客様の情報を送る電報","휠체어 등 특별 대응 승객 정보를 보내는 전보","Message listing passengers needing special services"],
["MSG","Baggage Source Message (BSM)","手荷物情報電報（BSM）","수하물 정보 전보(BSM)","手荷物のタグ番号と便を仕分け装置に知らせる電報","수하물 태그 번호와 편을 분류 장치에 알리는 전보","Message giving a bag’s tag number and flight to sortation systems"],
["MSG","Airline Designator","航空会社コード","항공사 코드","2文字（IATA）または3文字（ICAO）の航空会社の略号","2자리(IATA) 또는 3자리(ICAO) 항공사 약호","Two-letter IATA or three-letter ICAO airline codes"],
["MSG","IATA Delay Code Groups","遅延コードの区分","지연 코드 구분","旅客・手荷物、貨物、整備、運航、天候、空港・管制などの原因別の区分","여객·수하물, 화물, 정비, 운항, 기상, 공항·관제 등 원인별 구분","Delay causes grouped by passengers, cargo, technical, operations, weather, airport and ATC"],
["BIZ","Available Seat Kilometres (ASK)","有効座席キロ（ASK）","유효좌석킬로미터(ASK)","座席数×飛行距離。供給量を表す","좌석 수×비행거리. 공급량을 나타낸다","Seats offered multiplied by distance flown: capacity"],
["BIZ","Revenue Passenger Kilometres (RPK)","有償旅客キロ（RPK）","유상여객킬로미터(RPK)","有償のお客様の数×飛行距離。需要を表す","유상 승객 수×비행거리. 수요를 나타낸다","Paying passengers multiplied by distance: traffic"],
["BIZ","Yield","イールド（単位収入）","일드(단위 수익)","旅客キロあたりの収入","여객킬로당 수익","Revenue per passenger kilometre"],
["BIZ","RASK / CASK","座席キロあたり収入・費用","좌석킬로당 수익·비용","有効座席キロあたりの収入と費用","유효좌석킬로당 수익과 비용","Revenue and cost per available seat kilometre"],
["BIZ","Break-even Load Factor","損益分岐搭乗率","손익분기 탑승률","費用をちょうど回収できる搭乗率","비용을 딱 회수할 수 있는 탑승률","The load factor at which revenue equals cost"],
["BIZ","Revenue Management","レベニューマネジメント","수익관리","需要に応じて運賃と座席の配分を調整し収入を最大にすること","수요에 따라 운임과 좌석 배분을 조정해 수익을 극대화하는 것","Adjusting prices and seat availability to maximise revenue"],
["BIZ","Point of Sale (POS)","販売地","판매지","航空券を販売した国・地域","항공권을 판매한 나라·지역","The country or market where a ticket is sold"],
["BIZ","Online Travel Agency (OTA)","オンライン旅行会社（OTA）","온라인 여행사(OTA)","インターネットで航空券などを販売する旅行会社","인터넷으로 항공권 등을 판매하는 여행사","A travel agency selling online"]
]);
