/* 航空用語辞典 第1部：予約・発券・運賃／旅客サービス／特別サービスコード／手荷物
   形式：[分類, English, 日本語, 한국어, 説明(ja), 설명(ko), Definition(en)] */
window.DICT=(window.DICT||[]).concat([
["RES","Passenger Name Record (PNR)","予約記録（PNR）","예약 기록(PNR)","予約ごとに作られる記録。氏名・旅程・連絡先・特別な依頼などを含む","예약마다 만들어지는 기록. 이름·여정·연락처·특별 요청 등을 담는다","The booking record holding names, itinerary, contacts and special requests"],
["RES","Record Locator","予約番号","예약 번호","PNRを呼び出すための6文字程度の英数字","PNR을 불러오기 위한 6자리 정도의 영숫자","The short alphanumeric code used to retrieve a PNR"],
["RES","Global Distribution System (GDS)","グローバル流通システム（GDS）","글로벌 유통 시스템(GDS)","旅行会社が多くの航空会社の座席を予約・発券するためのシステム","여행사가 여러 항공사 좌석을 예약·발권하는 시스템","Systems travel agents use to book and ticket many airlines"],
["RES","Computer Reservation System (CRS)","予約システム（CRS）","예약 시스템(CRS)","座席の在庫と予約を管理するコンピューターシステム","좌석 재고와 예약을 관리하는 컴퓨터 시스템","The computer system that manages seat inventory and bookings"],
["RES","Passenger Service System (PSS)","旅客サービスシステム（PSS）","여객 서비스 시스템(PSS)","予約・在庫・発券・チェックインをまとめた航空会社の基幹システム","예약·재고·발권·체크인을 묶은 항공사 기간 시스템","An airline’s core system for reservations, inventory, ticketing and check-in"],
["RES","Departure Control System (DCS)","出発管理システム（DCS）","출발 관리 시스템(DCS)","チェックイン・搭乗・搭載管理を行うシステム","체크인·탑승·탑재관리를 하는 시스템","The system for check-in, boarding and load control"],
["RES","Electronic Ticket (ET)","電子航空券","전자항공권","紙ではなく航空会社のシステムに記録される航空券","종이가 아닌 항공사 시스템에 기록되는 항공권","A ticket held in the airline’s system rather than on paper"],
["RES","Ticket Number","航空券番号","항공권 번호","航空会社コード3桁と10桁の番号からなる13桁の番号","항공사 코드 3자리와 10자리 번호로 된 13자리 번호","The 13-digit number: a 3-digit airline code plus 10 digits"],
["RES","Electronic Miscellaneous Document (EMD)","電子付帯証票（EMD）","전자 부가 증표(EMD)","手荷物料金・座席料金など運賃以外の支払いを記録する電子の証票","수하물·좌석 요금 등 운임 외 지불을 기록하는 전자 증표","An electronic document for charges other than the fare, such as bags or seats"],
["RES","Fare Basis","運賃種別コード","운임 기준 코드","運賃の種類と条件（有効期間・変更の可否など）を示すコード","운임 종류와 조건(유효기간·변경 가부 등)을 나타내는 코드","The code identifying a fare type and its conditions"],
["RES","Reservation Booking Designator (RBD)","予約クラス（RBD）","예약 클래스(RBD)","同じ客室の中で運賃の段階を示す1文字（Y・M・Kなど）","같은 객실 안에서 운임 단계를 나타내는 한 글자(Y·M·K 등)","The one-letter booking class showing the fare level within a cabin"],
["RES","Cabin Class","客室クラス","좌석 등급","ファースト・ビジネス・プレミアムエコノミー・エコノミーなどの区分","퍼스트·비즈니스·프리미엄 이코노미·이코노미 등의 구분","First, business, premium economy, economy and so on"],
["RES","Married Segment","結合区間","결합 구간","乗り継ぎで一体として予約された区間。片方だけの変更は制限される","환승으로 하나로 묶여 예약된 구간. 한쪽만 변경은 제한된다","Connecting segments booked as one unit; changing one alone is restricted"],
["RES","Waitlist (WL)","キャンセル待ち","대기 예약","満席の便で、空きが出たら予約が確定する状態","만석인 편에서 빈자리가 나면 예약이 확정되는 상태","A booking confirmed only if a seat becomes free"],
["RES","Overbooking","超過予約（オーバーブッキング）","초과 예약","不搭乗を見込んで座席数より多く予約を受けること","노쇼를 예상해 좌석 수보다 많이 예약받는 것","Selling more seats than available in anticipation of no-shows"],
["RES","No-show","ノーショー（不搭乗）","노쇼","予約があるのに搭乗手続きに来ないこと","예약이 있는데 탑승수속에 오지 않는 것","A booked passenger who does not turn up"],
["RES","Go-show","ゴーショー","고쇼","予約なしで空港に来て、空席があれば乗ること","예약 없이 공항에 와서 빈자리가 있으면 타는 것","Turning up without a booking and flying if there is a seat"],
["RES","Load Factor (LF)","搭乗率","탑승률","座席数に対する乗客数の割合","좌석 수 대비 승객 수 비율","Passengers carried as a share of seats offered"],
["RES","Interline Agreement","インターライン協定","인터라인 협정","航空会社どうしで航空券や手荷物を受け渡すための協定","항공사끼리 항공권과 수하물을 주고받기 위한 협정","An agreement letting airlines accept each other’s tickets and bags"],
["RES","Codeshare","コードシェア（共同運航）","공동운항(코드셰어)","1つの便に複数の航空会社の便名を付けて販売すること","한 편에 여러 항공사 편명을 붙여 판매하는 것","One flight sold under more than one airline’s flight number"],
["RES","Operating Carrier","運航会社","운항 항공사","実際に機体を運航する航空会社","실제로 기체를 운항하는 항공사","The airline actually flying the aircraft"],
["RES","Marketing Carrier","販売会社","판매 항공사","自社の便名で座席を販売する航空会社","자사 편명으로 좌석을 판매하는 항공사","The airline selling seats under its own flight number"],
["RES","Endorsement","エンドース","엔도스(배서)","航空券を他社の便でも使えるよう認めること","항공권을 타사 편에도 쓸 수 있도록 인정하는 것","Authorising a ticket to be used on another airline"],
["RES","Reissue","再発行","재발행","旅程や運賃の変更で航空券を発行し直すこと","여정·운임 변경으로 항공권을 다시 발행하는 것","Issuing a new ticket after a change of itinerary or fare"],
["RES","Revalidation","再有効化","재유효화","運賃を変えずに便・日付の変更を航空券に反映すること","운임을 바꾸지 않고 편·날짜 변경을 항공권에 반영하는 것","Recording a flight or date change on a ticket without repricing"],
["RES","Involuntary Change","非自発的変更","비자발적 변경","欠航など航空会社の都合による予約の変更","결항 등 항공사 사정에 의한 예약 변경","A change caused by the airline, such as a cancellation"],
["RES","Voluntary Change","自発的変更","자발적 변경","お客様の希望による変更。手数料がかかることが多い","승객 희망에 의한 변경. 수수료가 붙는 경우가 많다","A change the passenger requests, often for a fee"],
["RES","Fuel Surcharge (YQ/YR)","燃油特別付加運賃","유류할증료","燃料の価格に応じて運賃に上乗せする料金","연료 가격에 따라 운임에 더하는 요금","A charge added to the fare in line with fuel prices"],
["RES","Passenger Service Facility Charge (PSFC)","旅客施設使用料","여객시설 사용료","空港ターミナルの利用に対して航空券と一緒に集める料金","공항 터미널 이용에 대해 항공권과 함께 걷는 요금","A terminal use charge collected with the ticket"],
["RES","Billing and Settlement Plan (BSP)","銀行集中決済制度（BSP）","은행 집중 결제 제도(BSP)","IATA公認の旅行会社と航空会社の間の販売代金を精算する仕組み","IATA 공인 여행사와 항공사 간 판매 대금을 정산하는 체계","IATA’s system for settling sales between accredited agents and airlines"],
["RES","New Distribution Capability (NDC)","NDC（新しい流通の規格）","NDC(신유통 표준)","航空会社が商品を旅行会社などへ直接届けるためのIATAの規格","항공사가 상품을 여행사 등에 직접 전달하기 위한 IATA 표준","An IATA standard for airlines to distribute offers directly"],
["RES","Ancillary Revenue","付帯収入","부가 수익","座席指定・手荷物・機内販売など運賃以外の収入","좌석 지정·수하물·기내 판매 등 운임 외 수익","Revenue other than fares, such as seats, bags and onboard sales"],
["RES","Ticketing Time Limit (TTL)","発券期限","발권 기한","この時刻までに発券しないと予約が取り消される期限","이 시각까지 발권하지 않으면 예약이 취소되는 기한","The deadline by which a booking must be ticketed"],
["RES","Open Jaw","オープンジョー","오픈조","往路の到着地と復路の出発地が違う旅程","가는 편 도착지와 오는 편 출발지가 다른 여정","A trip where the outbound destination and return origin differ"],
["RES","Stopover","途中降機（ストップオーバー）","도중 체류(스톱오버)","乗り継ぎ地に一定時間（国際線では一般に24時間）を超えて滞在すること","환승지에 일정 시간(국제선은 보통 24시간)을 넘겨 머무는 것","Staying at an intermediate point beyond the connection time limit"],
["RES","Minimum Connecting Time (MCT)","最低乗り継ぎ時間","최소 연결 시간","空港・ターミナルごとに決められた乗り継ぎに必要な最短時間","공항·터미널별로 정해진 환승에 필요한 최소 시간","The shortest legal connection time set for each airport"],
["RES","Through Check-in","スルーチェックイン","연결 수속","最初の空港で最終目的地までの手続きをすること","첫 공항에서 최종 목적지까지 수속하는 것","Checking in at origin all the way to the final destination"],
["RES","Frequent Flyer Programme (FFP)","マイレージプログラム","마일리지 프로그램","搭乗に応じてマイルが貯まる会員制度","탑승에 따라 마일리지가 쌓이는 회원 제도","A loyalty scheme earning miles or points for flying"],
["PAX","Common Use Self Service (CUSS)","共用自動チェックイン機","공용 자동 체크인기","複数の航空会社が共通で使う自動チェックイン機","여러 항공사가 함께 쓰는 자동 체크인기","Self-service kiosks shared by several airlines"],
["PAX","Common Use Terminal Equipment (CUTE/CUPPS)","共用端末","공용 단말","カウンターやゲートで複数の航空会社が共用する端末","카운터·게이트에서 여러 항공사가 함께 쓰는 단말","Counter and gate terminals shared by several airlines"],
["PAX","Bag Drop","手荷物預け入れ（バゲージドロップ）","수하물 위탁(백 드롭)","手続きを済ませたお客様が手荷物だけを預ける場所","수속을 마친 승객이 수하물만 맡기는 곳","Where checked-in passengers leave their bags"],
["PAX","Bar Coded Boarding Pass (BCBP)","バーコード搭乗券","바코드 탑승권","IATAの規格のバーコードを印刷・表示する搭乗券","IATA 규격 바코드를 인쇄·표시하는 탑승권","A boarding pass carrying an IATA-standard barcode"],
["PAX","Pre-boarding","事前搭乗","사전 탑승","助けが必要なお客様などに先に乗ってもらうこと","도움이 필요한 승객 등을 먼저 태우는 것","Boarding passengers who need assistance first"],
["PAX","Final Call","最終案内","최종 안내","搭乗締め切り前の最後の呼び出し","탑승 마감 전 마지막 호출","The last call before boarding closes"],
["PAX","Gate Closure","搭乗締め切り","탑승 마감","この時刻を過ぎると搭乗できない締め切り","이 시각이 지나면 탑승할 수 없는 마감","The time after which passengers can no longer board"],
["PAX","Denied Boarding (DB)","搭乗拒否","탑승 거절","超過予約などで予約のあるお客様が乗れないこと","초과 예약 등으로 예약 승객이 타지 못하는 것","A booked passenger not carried, for example because of overbooking"],
["PAX","Travel Document","渡航書類","여행 서류","旅券・査証など入国・通過に必要な書類","여권·비자 등 입국·통과에 필요한 서류","Passports, visas and other documents needed for travel"],
["PAX","TIMATIC","TIMATIC（渡航条件データベース）","TIMATIC(여행 조건 데이터베이스)","IATAの旅券・査証・検疫などの条件のデータベース","IATA의 여권·비자·검역 조건 데이터베이스","IATA’s database of passport, visa and health requirements"],
["PAX","Advance Passenger Information (API)","事前旅客情報（API）","사전 승객 정보(API)","出発前に当局へ送る旅券などの情報","출발 전 당국에 보내는 여권 등의 정보","Passport and personal data sent to authorities before travel"],
["PAX","Interactive API (iAPI)","双方向の事前旅客情報","양방향 사전 승객 정보","送った情報に当局が搭乗の可否を返す仕組み","보낸 정보에 당국이 탑승 가부를 회신하는 체계","API where the authority replies with a board or do-not-board message"],
["PAX","Inadmissible Passenger (INAD)","入国拒否のお客様","입국 거부 승객","到着国で入国を認められなかったお客様","도착국에서 입국이 허용되지 않은 승객","A passenger refused entry at the destination"],
["PAX","Deportee (DEPU/DEPA)","強制送還者","강제 송환자","当局の命令で送還されるお客様（付き添いなし／あり）","당국 명령으로 송환되는 승객(비동반/동반)","A person removed by authorities, unescorted or escorted"],
["PAX","Unaccompanied Minor (UM)","一人旅の子ども","비동반 소아","保護者が同行しないで旅行する子ども","보호자 없이 여행하는 아이","A child travelling without a parent or guardian"],
["PAX","Infant (INF)","幼児","유아","一般に2歳未満。座席を使わず大人のひざの上","보통 만 2세 미만. 좌석 없이 성인 무릎 위","Usually under 2, travelling on an adult’s lap"],
["PAX","Child (CHD)","小児","소아","一般に2歳以上12歳未満","보통 만 2세 이상 12세 미만","Usually aged 2 to 11"],
["PAX","Passenger with Reduced Mobility (PRM)","移動に配慮が必要なお客様","교통약자 승객","障がい・けが・高齢などで移動に助けが必要なお客様","장애·부상·고령 등으로 이동에 도움이 필요한 승객","A passenger needing help moving because of disability, injury or age"],
["PAX","Irregular Operations (IRROPS)","イレギュラー運航","비정상 운항","遅延・欠航・ダイバートなど計画どおりでない運航","지연·결항·회항 등 계획대로 되지 않은 운항","Delays, cancellations, diversions and other disruption"],
["PAX","Rebooking","振り替え","재예약","欠航などで別の便に予約を移すこと","결항 등으로 다른 편에 예약을 옮기는 것","Moving a passenger to another flight"],
["PAX","Tarmac Delay","機内長時間待機","기내 장시간 대기","ドアを閉めた後、地上で長く待機すること","도어를 닫은 뒤 지상에서 오래 대기하는 것","A long wait on the ground with passengers on board"],
["PAX","Diversion","ダイバート（目的地変更）","회항(목적지 변경)","目的地以外の空港に着陸すること","목적지 외 공항에 착륙하는 것","Landing at an airport other than the destination"],
["PAX","Ramp Return","ランプリターン","램프 리턴","プッシュバック後に駐機場へ戻ること","푸시백 후 주기장으로 돌아오는 것","Returning to the stand after pushback"],
["PAX","Air Turn Back","エアターンバック","에어턴백","離陸後に出発地へ引き返すこと","이륙 후 출발지로 되돌아오는 것","Returning to the departure airport after take-off"],
["SSR","Special Service Request (SSR)","特別サービス要求（SSR）","특별 서비스 요청(SSR)","特別な対応を予約記録に入れる4文字のコード","특별 대응을 예약 기록에 넣는 4자리 코드","A four-letter code in the booking for a special service"],
["SSR","WCHR","WCHR（車いす：階段・客室内は歩ける）","WCHR(휠체어: 계단·객실 내 보행 가능)","長い距離は歩けないが、階段と機内の移動はできる","긴 거리는 못 걷지만 계단과 기내 이동은 가능","Cannot walk long distances; can manage steps and the cabin"],
["SSR","WCHS","WCHS（車いす：階段は不可）","WCHS(휠체어: 계단 불가)","階段は上り下りできないが、機内の座席までは歩ける","계단은 오르내리지 못하지만 기내 좌석까지는 걸을 수 있다","Cannot manage steps; can walk to the seat"],
["SSR","WCHC","WCHC（車いす：座席まで移動できない）","WCHC(휠체어: 좌석까지 이동 불가)","座席まで自分で移動できず、機内用車いすが必要","좌석까지 스스로 이동하지 못해 기내용 휠체어가 필요","Cannot move to the seat; needs an aisle chair"],
["SSR","WCMP","WCMP（手動車いすを預ける）","WCMP(수동 휠체어 위탁)","お客様自身の手動車いすを預ける","승객 본인의 수동 휠체어를 맡긴다","The passenger’s own manual wheelchair is checked"],
["SSR","WCBD","WCBD（乾電池式の電動車いす）","WCBD(건식 배터리 전동 휠체어)","乾式・密閉式の電池を使う電動車いす","건식·밀폐형 배터리를 쓰는 전동 휠체어","Powered wheelchair with a dry or sealed battery"],
["SSR","WCBW","WCBW（液式電池の電動車いす）","WCBW(액체식 배터리 전동 휠체어)","液式の電池を使う電動車いす","액체식 배터리를 쓰는 전동 휠체어","Powered wheelchair with a spillable wet battery"],
["SSR","WCLB","WCLB（リチウム電池の電動車いす）","WCLB(리튬 배터리 전동 휠체어)","リチウムイオン電池を使う電動車いす","리튬이온 배터리를 쓰는 전동 휠체어","Powered wheelchair with a lithium-ion battery"],
["SSR","BLND","BLND（目の不自由なお客様）","BLND(시각장애 승객)","視覚に障がいのあるお客様","시각장애가 있는 승객","Passenger who is blind or partially sighted"],
["SSR","DEAF","DEAF（耳の不自由なお客様）","DEAF(청각장애 승객)","聴覚に障がいのあるお客様","청각장애가 있는 승객","Passenger who is deaf or hard of hearing"],
["SSR","DPNA","DPNA（知的・発達の障がいで支援が必要なお客様）","DPNA(지적·발달장애로 지원이 필요한 승객)","知的障がい・発達障がいなどで案内や見守りが必要なお客様","지적장애·발달장애 등으로 안내나 보살핌이 필요한 승객","Passenger with an intellectual or developmental disability needing assistance"],
["SSR","MEDA","MEDA（医療上の配慮が必要なお客様）","MEDA(의료적 배려가 필요한 승객)","病気・けがなどで医療の確認（診断書など）が必要なお客様","질병·부상 등으로 의료 확인(소견서 등)이 필요한 승객","Passenger whose medical condition needs clearance"],
["SSR","MEDIF","MEDIF（医療情報の申告書）","MEDIF(의료 정보 신고서)","医療上の搭乗の可否を判断するための様式","의료상 탑승 가부를 판단하기 위한 양식","The form used to assess a passenger’s medical fitness to fly"],
["SSR","STCR","STCR（ストレッチャーのお客様）","STCR(스트레처 승객)","横になったまま運ぶお客様。座席を複数使う","누운 채로 운송하는 승객. 좌석 여러 개를 쓴다","A passenger carried on a stretcher, using several seats"],
["SSR","OXYG","OXYG（機内で酸素を使うお客様）","OXYG(기내 산소 사용 승객)","機内で医療用の酸素が必要なお客様","기내에서 의료용 산소가 필요한 승객","Passenger needing medical oxygen on board"],
["SSR","UMNR","UMNR（一人旅の子ども）","UMNR(비동반 소아)","一人旅の子どもを示すコード","비동반 소아를 나타내는 코드","Code for an unaccompanied minor"],
["SSR","PETC","PETC（機内に持ち込むペット）","PETC(기내 반려동물)","客室に持ち込むペット","객실에 데리고 타는 반려동물","A pet travelling in the cabin"],
["SSR","AVIH","AVIH（貨物室で運ぶ動物）","AVIH(화물칸 동물)","貨物室で運ぶ生きた動物（手荷物として）","화물칸으로 운송하는 살아 있는 동물(수하물로)","A live animal carried in the hold as baggage"],
["SSR","SVAN","SVAN（補助犬を伴うお客様）","SVAN(보조견 동반 승객)","盲導犬・介助犬などの補助犬を伴うお客様","안내견·도우미견 등 보조견을 동반한 승객","Passenger travelling with a service animal"],
["SSR","ESAN","ESAN（精神的な支援の動物）","ESAN(정서 지원 동물)","精神的な支えのための動物。扱いは国・会社で大きく違う","정서적 지지를 위한 동물. 처리는 나라·회사마다 크게 다름","An emotional support animal; treatment varies widely"],
["SSR","CBBG","CBBG（座席を使う手荷物）","CBBG(좌석 점유 수하물)","楽器など、座席を購入して機内に置く手荷物","악기 등 좌석을 사서 기내에 두는 수하물","Baggage such as an instrument occupying a purchased seat"],
["SSR","EXST","EXST（追加の座席）","EXST(추가 좌석)","体格などの理由でお客様が追加で使う座席","체격 등의 이유로 승객이 추가로 쓰는 좌석","An extra seat for the passenger’s comfort"],
["SSR","BSCT","BSCT（バシネット）","BSCT(요람)","機内で乳児を寝かせる簡易ベッド","기내에서 영아를 눕히는 간이 침대","An infant bassinet"],
["SSR","CHML","CHML（子ども向けの食事）","CHML(어린이식)","子ども向けの特別食","어린이용 특별식","Child meal"],
["SSR","BBML","BBML（乳児向けの食事）","BBML(유아식)","乳児向けの特別食","영아용 특별식","Baby meal"],
["SSR","VGML","VGML（ベジタリアン食）","VGML(채식)","肉・魚・乳製品などを使わない食事","고기·생선·유제품 등을 쓰지 않는 식사","Vegetarian (vegan) meal"],
["SSR","MOML","MOML（イスラム教徒向けの食事）","MOML(무슬림식)","イスラム教の戒律に沿った食事","이슬람 율법에 맞춘 식사","Muslim meal"],
["SSR","KSML","KSML（ユダヤ教の戒律に沿った食事）","KSML(코셔식)","ユダヤ教の戒律に沿った食事","유대교 율법에 맞춘 식사","Kosher meal"],
["SSR","DBML","DBML（糖尿病に配慮した食事）","DBML(당뇨식)","糖分などに配慮した食事","당분 등을 배려한 식사","Diabetic meal"],
["SSR","GFML","GFML（グルテンを除いた食事）","GFML(글루텐 프리식)","グルテンを含まない食事","글루텐이 없는 식사","Gluten-free meal"],
["SSR","DOCS","DOCS（旅券情報）","DOCS(여권 정보)","旅券の番号・国籍・生年月日などを予約に入れるSSR","여권 번호·국적·생년월일 등을 예약에 넣는 SSR","SSR carrying passport data for API"],
["SSR","FQTV","FQTV（マイレージ会員番号）","FQTV(마일리지 회원 번호)","マイレージの会員番号を予約に入れるSSR","마일리지 회원 번호를 예약에 넣는 SSR","SSR carrying the frequent flyer number"],
["SSR","TKNE","TKNE（航空券番号）","TKNE(항공권 번호)","電子航空券の番号を予約に結び付けるSSR","전자항공권 번호를 예약에 연결하는 SSR","SSR linking the e-ticket number to the booking"],
["BAG","Checked Baggage","受託手荷物","위탁 수하물","カウンターで預けて貨物室で運ぶ手荷物","카운터에서 맡겨 화물칸으로 운송하는 수하물","Baggage handed over and carried in the hold"],
["BAG","Cabin Baggage","機内持ち込み手荷物","기내 휴대 수하물","お客様が機内に持ち込む手荷物","승객이 기내에 들고 타는 수하물","Baggage passengers take on board"],
["BAG","Free Baggage Allowance (FBA)","無料手荷物許容量","무료 수하물 허용량","料金なしで預けられる手荷物の個数・重さ","요금 없이 맡길 수 있는 수하물의 개수·무게","The bags a passenger may check without charge"],
["BAG","Piece Concept","個数制","개수제","預けられる手荷物を個数で決める方式","맡길 수 있는 수하물을 개수로 정하는 방식","Allowance counted by number of pieces"],
["BAG","Weight Concept","重量制","무게제","預けられる手荷物を合計の重さで決める方式","맡길 수 있는 수하물을 합계 무게로 정하는 방식","Allowance counted by total weight"],
["BAG","Excess Baggage","超過手荷物","초과 수하물","許容量を超えた手荷物。料金がかかる","허용량을 넘은 수하물. 요금이 붙는다","Baggage over the allowance, charged for"],
["BAG","Bag Tag","手荷物タグ","수하물 태그","行き先と10桁の番号を示すタグ","행선지와 10자리 번호를 표시하는 태그","The tag showing destination and a 10-digit number"],
["BAG","Limited Release Tag","免責タグ","면책 태그","壊れやすい物などで、破損の責任を限る同意を示すタグ","파손되기 쉬운 물건 등에서 파손 책임을 제한하는 동의 표시 태그","Tag recording the passenger’s agreement to limited liability"],
["BAG","Priority Tag","優先タグ","우선 태그","到着地で先に出す手荷物に付けるタグ","도착지에서 먼저 내보낼 수하물에 붙이는 태그","Tag for bags delivered first on arrival"],
["BAG","Rush Tag","転送タグ（ラッシュタグ）","러시 태그","持ち主と別の便で送る手荷物に付けるタグ","주인과 다른 편으로 보내는 수하물에 붙이는 태그","Tag for a bag forwarded without its owner"],
["BAG","Baggage Handling System (BHS)","手荷物処理システム（BHS）","수하물 처리 시스템(BHS)","預けた手荷物を検査・仕分けして運ぶ空港の設備","맡긴 수하물을 검사·분류해 옮기는 공항 설비","The airport system that screens, sorts and conveys bags"],
["BAG","Baggage Reconciliation System (BRS)","手荷物照合システム（BRS）","수하물 대조 시스템(BRS)","手荷物と搭乗したお客様を照合するシステム","수하물과 탑승 승객을 대조하는 시스템","The system matching bags to boarded passengers"],
["BAG","Mishandled Baggage","手荷物事故","수하물 사고","未着・破損・中身の不足・紛失などの総称","미착·파손·내용물 부족·분실 등의 총칭","Delayed, damaged, pilfered or lost baggage"],
["BAG","Property Irregularity Report (PIR)","手荷物事故報告書（PIR）","수하물 사고 보고서(PIR)","手荷物事故の申し出を受けて作る報告書","수하물 사고 신고를 받아 만드는 보고서","The report raised for a baggage irregularity"],
["BAG","WorldTracer","WorldTracer（手荷物追跡システム）","WorldTracer(수하물 추적 시스템)","世界の多くの航空会社が使う手荷物の追跡システム","세계 많은 항공사가 쓰는 수하물 추적 시스템","The baggage tracing system used by most airlines"],
["BAG","AHL","AHL（未着手荷物の記録）","AHL(미착 수하물 기록)","探している手荷物の記録","찾고 있는 수하물 기록","Record of a delayed bag being searched for"],
["BAG","OHD","OHD（持ち主のいない手荷物の記録）","OHD(주인 없는 수하물 기록)","空港に残った持ち主のいない手荷物の記録","공항에 남은 주인 없는 수하물 기록","Record of a bag found without its owner"],
["BAG","DPR","DPR（破損・中身の不足の記録）","DPR(파손·내용물 부족 기록)","破損や抜き取りの記録","파손이나 내용물 분실 기록","Record of damage or pilferage"],
["BAG","Short-shipped Baggage","積み残し","미탑재 수하물","載せるはずの便に載らなかった手荷物","실어야 할 편에 실리지 않은 수하물","A bag that missed its intended flight"],
["BAG","Delivery at Aircraft (DAA)","機側渡し","기측 인도","ベビーカーなどを機体の近くで預かり、到着時にそこで返すこと","유모차 등을 기체 근처에서 맡아 도착 시 그곳에서 돌려주는 것","Items taken at the aircraft door and returned there on arrival"],
["BAG","Montreal Convention","モントリオール条約","몬트리올 협약","国際線の航空会社の責任（手荷物・遅延など）を定めた条約","국제선 항공사 책임(수하물·지연 등)을 정한 협약","The treaty setting airline liability on international flights"],
["BAG","Special Drawing Rights (SDR)","特別引出権（SDR）","특별인출권(SDR)","国際線の補償の上限を表す単位","국제선 보상 한도를 나타내는 단위","The unit in which international liability limits are expressed"]
]);
