/* 航空用語辞典 第4部：CIQ・日韓の機関／A-CDMの時刻／IATA遅延コード（主なもの）／客室・乗務員
   ※ 遅延コードはIATA AHM730にもとづく代表例。版や会社の運用で細部が違う（★） */
window.DICT=(window.DICT||[]).concat([
["ORG","CIQ","CIQ（税関・出入国管理・検疫）","CIQ(세관·출입국·검역)","Customs・Immigration・Quarantineの略。国境での3つの手続き","Customs·Immigration·Quarantine의 약자. 국경에서의 세 가지 절차","Customs, immigration and quarantine: the three border controls"],
["ORG","Immigration Services Agency of Japan","出入国在留管理庁","일본 출입국재류관리청","日本の出入国の審査と在留の管理を行う機関","일본의 출입국 심사와 재류 관리를 하는 기관","Japan’s immigration and residence authority"],
["ORG","Japan Customs","税関（日本）","일본 세관","貨物・手荷物の輸出入を管理する機関","화물·수하물의 수출입을 관리하는 기관","The Japanese customs authority"],
["ORG","Quarantine Station","検疫所","검역소","感染症の侵入を防ぐための人の検疫を行う機関","감염병 유입을 막기 위한 사람 검역 기관","The body carrying out health checks on arriving people"],
["ORG","Animal Quarantine Service","動物検疫所","동물검역소","動物・肉製品などの輸入の検査を行う機関","동물·육류 제품 등의 수입 검사를 하는 기관","The body inspecting imported animals and animal products"],
["ORG","Plant Protection Station","植物防疫所","식물방역소","植物・果物などの輸入の検査を行う機関","식물·과일 등의 수입 검사를 하는 기관","The body inspecting imported plants and fruit"],
["ORG","Ministry of Land, Infrastructure and Transport (Korea)","国土交通部（韓国）","국토교통부(한국)","韓国の航空行政を担う省","한국의 항공 행정을 담당하는 부처","Korea’s ministry responsible for civil aviation"],
["ORG","Korea Immigration Service","出入国・外国人政策本部（韓国）","출입국·외국인정책본부","韓国法務部の出入国の管理を担う組織","한국 법무부의 출입국 관리를 담당하는 조직","The immigration arm of Korea’s Ministry of Justice"],
["ORG","Korea Customs Service","関税庁（韓国）","관세청","韓国の税関の機関","한국의 세관 기관","Korea’s customs authority"],
["ORG","Pre-boarding Passenger Check (Korea)","搭乗者の事前確認制度（韓国）","탑승자 사전확인제도","韓国に関わる便で、搭乗前に当局が乗客の可否を確認する制度","한국 관련 편에서 탑승 전에 당국이 승객 가부를 확인하는 제도","Korea’s system for clearing passengers before boarding"],
["ORG","Landing Permission","上陸許可","상륙 허가","日本に入国を認める許可","일본 입국을 인정하는 허가","Permission to land (enter) in Japan"],
["ORG","Crew Landing Permit","乗員上陸許可","승무원 상륙 허가","乗務員が一時的に上陸するための許可","승무원이 일시적으로 상륙하기 위한 허가","Permission for crew to go ashore temporarily"],
["ORG","Transit Without Visa (TWOV)","ビザなし通過","무비자 통과","条件を満たせば査証なしで乗り継げること","조건을 충족하면 비자 없이 환승할 수 있는 것","Transiting without a visa where conditions are met"],
["ORG","General Declaration (GD)","一般申告書（GD）","일반 신고서(GD)","便・乗員・到着地などを当局に申告する書類","편·승무원·도착지 등을 당국에 신고하는 서류","The document declaring a flight and its crew to the authorities"],
["ORG","NACCS","NACCS（輸出入・港湾関連情報処理システム）","NACCS(일본 수출입 통관 시스템)","日本の税関などの手続きを電子で行うシステム","일본 세관 등의 절차를 전자로 처리하는 시스템","Japan’s electronic system for customs and related procedures"],
["OPS","Airport Collaborative Decision Making (A-CDM)","A-CDM（空港の協調的意思決定）","A-CDM(공항 협력적 의사결정)","空港・航空会社・管制が時刻を共有して出発を効率化する仕組み","공항·항공사·관제가 시각을 공유해 출발을 효율화하는 체계","Airports, airlines and ATC sharing times to streamline departures"],
["OPS","Target Off-Block Time (TOBT)","出発準備完了の目標時刻（TOBT）","출발 준비 완료 목표 시각(TOBT)","航空会社・ハンドリング会社が約束するドアを閉めて出られる時刻","항공사·조업사가 약속하는 도어를 닫고 출발할 수 있는 시각","The time the airline commits to being ready to leave the stand"],
["OPS","Target Start-up Approval Time (TSAT)","始動承認の目標時刻（TSAT）","시동 승인 목표 시각(TSAT)","管制が出発の順番を踏まえて示すエンジン始動の時刻","관제가 출발 순서를 반영해 제시하는 엔진 시동 시각","The start-up time issued taking the departure sequence into account"],
["OPS","Target Take-off Time (TTOT)","離陸の目標時刻（TTOT）","이륙 목표 시각(TTOT)","A-CDMで計算される離陸の目標時刻","A-CDM으로 계산되는 이륙 목표 시각","The target take-off time calculated in A-CDM"],
["OPS","Estimated Off-Block Time (EOBT)","出発見込み時刻（EOBT）","출발 예상 시각(EOBT)","飛行計画に記載するブロックアウトの見込み時刻","비행계획에 기재하는 블록 아웃 예상 시각","The estimated off-block time filed in the flight plan"],
["OPS","Taxi Time (EXOT / EXIT)","地上走行の時間","지상 활주 시간","出発時（EXOT）・到着時（EXIT）の地上走行の見込み時間","출발 시(EXOT)·도착 시(EXIT)의 지상 활주 예상 시간","Expected taxi-out and taxi-in times"],
["OPS","Delay Code 11","遅延コード11（締め切り後の受付）","지연 코드 11(마감 후 접수)","チェックインの締め切り後にお客様を受け付けたための遅延","체크인 마감 후 승객을 접수해서 생긴 지연","Late acceptance after the check-in deadline"],
["OPS","Delay Code 12","遅延コード12（チェックインの混雑）","지연 코드 12(체크인 혼잡)","チェックインの混雑による遅延","체크인 혼잡에 의한 지연","Congestion in the check-in area"],
["OPS","Delay Code 13","遅延コード13（チェックインの誤り）","지연 코드 13(체크인 오류)","チェックインの手続きの誤りによる遅延","체크인 절차 오류에 의한 지연","Check-in error"],
["OPS","Delay Code 14","遅延コード14（超過予約）","지연 코드 14(초과 예약)","超過予約の処理による遅延","초과 예약 처리에 의한 지연","Oversales and booking errors"],
["OPS","Delay Code 15","遅延コード15（搭乗）","지연 코드 15(탑승)","搭乗時の人数の不一致・呼び出し・未搭乗の手荷物の処理などによる遅延","탑승 시 인원 불일치·호출·미탑승 수하물 처리 등에 의한 지연","Boarding: discrepancies, paging, missing checked-in passengers"],
["OPS","Delay Code 17","遅延コード17（機内食の注文）","지연 코드 17(기내식 주문)","機内食の注文の遅れ・誤りによる遅延","기내식 주문 지연·오류에 의한 지연","Catering order late or incorrect"],
["OPS","Delay Code 18","遅延コード18（手荷物の処理）","지연 코드 18(수하물 처리)","手荷物の仕分け・処理による遅延","수하물 분류·처리에 의한 지연","Baggage processing"],
["OPS","Delay Code 19","遅延コード19（移動に配慮が必要なお客様）","지연 코드 19(교통약자 승객)","車いすなど移動の支援が必要なお客様の対応による遅延","휠체어 등 이동 지원이 필요한 승객 대응에 의한 지연","Passengers with reduced mobility"],
["OPS","Delay Codes 31–39","遅延コード31〜39（機体・ランプの作業）","지연 코드 31~39(기체·램프 작업)","書類・積み下ろし・機材・清掃・給油・機内食・ULDなどによる遅延","서류·하역·장비·청소·급유·기내식·ULD 등에 의한 지연","Aircraft and ramp handling: documents, loading, equipment, cleaning, fuel, catering, ULDs"],
["OPS","Delay Code 32","遅延コード32（積み下ろし）","지연 코드 32(하역)","特別な搭載物・人手不足などの積み下ろしによる遅延","특수 탑재물·인력 부족 등 하역에 의한 지연","Loading and unloading, including special loads and lack of staff"],
["OPS","Delay Code 36","遅延コード36（給油）","지연 코드 36(급유)","給油・燃料の抜き取りによる遅延","급유·연료 배출에 의한 지연","Fuelling and defuelling"],
["OPS","Delay Codes 81–89","遅延コード81〜89（管制・空港・当局）","지연 코드 81~89(관제·공항·당국)","流れの管理、保安、出入国・税関・検疫、空港の設備・制限による遅延","흐름 관리, 보안, 출입국·세관·검역, 공항 설비·제한에 의한 지연","ATFM, security, border agencies, airport facilities and restrictions"],
["OPS","Delay Codes 91–96","遅延コード91〜96（波及遅延）","지연 코드 91~96(연쇄 지연)","乗り継ぎの接続、前の便の到着遅れ、乗務員の乗り継ぎなどによる遅延","연결 편 대기, 앞 편 도착 지연, 승무원 연결 등에 의한 지연","Reactionary delays: connections, late inbound aircraft, crew rotation"],
["OPS","Delay Code 93","遅延コード93（機体の到着遅れ）","지연 코드 93(기체 도착 지연)","前の区間の到着遅れが次の出発に波及した遅延","앞 구간 도착 지연이 다음 출발로 이어진 지연","Late arrival of the aircraft from the previous sector"],
["OPS","Reactionary Delay","波及遅延","연쇄 지연","前の遅れが後の便に次々と広がる遅延","앞의 지연이 뒤 편으로 차례로 번지는 지연","Delay passed on from an earlier delay"],
["PAX","Cabin Crew","客室乗務員","객실 승무원","機内の安全とサービスを担う乗務員","기내 안전과 서비스를 담당하는 승무원","Crew responsible for cabin safety and service"],
["PAX","Flight Crew / Flight Deck Crew","運航乗務員","운항 승무원","機長・副操縦士など操縦を担う乗務員","기장·부기장 등 조종을 담당하는 승무원","The pilots"],
["PAX","Purser / Cabin Manager","客室責任者（パーサー）","객실사무장","客室乗務員をまとめる責任者","객실 승무원을 이끄는 책임자","The senior cabin crew member"],
["OPS","First Officer (FO)","副操縦士","부기장","機長を補佐する操縦士","기장을 보좌하는 조종사","The co-pilot"],
["OPS","Deadhead Crew (DHC)","便乗乗務員","편승 승무원","勤務のため乗客として移動する乗務員","근무를 위해 승객으로 이동하는 승무원","Crew travelling as passengers to position for duty"],
["OPS","Jump Seat","ジャンプシート（補助席）","점프 시트(보조석)","操縦室・客室にある乗務員用の補助席","조종실·객실에 있는 승무원용 보조석","Auxiliary seat for crew in the cockpit or cabin"],
["SAF","Crew Resource Management (CRM)","CRM（乗務員の協力の手法）","CRM(승무원 자원 관리)","乗務員どうしの意思疎通・協力でエラーを防ぐ考え方","승무원 간 의사소통·협력으로 에러를 막는 사고방식","Using communication and teamwork among crew to prevent error"],
["SAF","Sterile Flight Deck","ステライル・コックピット","스테라일 콕핏","離着陸など重要な段階で業務外の会話をしない決まり","이착륙 등 중요 단계에서 업무 외 대화를 하지 않는 규칙","No non-essential talk in the cockpit during critical phases"],
["PAX","Galley","ギャレー","갤리","機内の調理・準備の場所","기내 조리·준비 공간","The aircraft kitchen area"],
["PAX","Overhead Bin","手荷物収納棚","머리 위 선반","座席の上の手荷物を入れる棚","좌석 위 수하물 선반","The overhead baggage locker"],
["PAX","Safety Demonstration","安全のご案内（デモ）","안전 시범","出発前に非常口・酸素マスクなどを案内すること","출발 전에 비상구·산소마스크 등을 안내하는 것","The pre-departure safety briefing"],
["PAX","Cabin Secure","客室の安全確認","객실 안전 확인","離着陸に向けて客室の安全が整った状態","이착륙을 위해 객실 안전이 갖춰진 상태","The cabin made safe for take-off or landing"],
["PAX","Cross-check","クロスチェック","크로스 체크","ドアのスライドの状態などを乗務員どうしで確認し合うこと","도어 슬라이드 상태 등을 승무원끼리 서로 확인하는 것","Crew confirming each other’s door slide settings"],
["PAX","Public Address (PA)","機内・空港の放送（PA）","기내·공항 방송(PA)","機内や空港の案内放送","기내나 공항의 안내 방송","Announcements in the cabin or terminal"],
["PAX","Duty-free","免税品","면세품","出国者などが税金なしで買える商品","출국자 등이 세금 없이 살 수 있는 상품","Goods sold free of certain taxes to departing travellers"],
["PAX","Inflight Entertainment (IFE)","機内エンターテインメント","기내 엔터테인먼트","機内の映像・音楽などのサービス","기내 영상·음악 등의 서비스","Onboard video, audio and other entertainment"],
["PAX","Special Meal (SPML)","特別食","특별식","宗教・健康・年齢などに応じた機内食","종교·건강·나이 등에 맞춘 기내식","Meals ordered for religious, medical or age reasons"],
["APT","Lost and Found","遺失物の取り扱い","유실물 처리","機内・空港の忘れ物を保管し返す業務","기내·공항 분실물을 보관하고 돌려주는 업무","Handling items left behind in aircraft or terminals"],
["APT","Aviation Fuel (Jet A-1)","航空燃料（ジェットA-1）","항공유(Jet A-1)","ジェット機が使う灯油系の燃料","제트기가 쓰는 등유계 연료","The kerosene-type fuel used by jet aircraft"],
["APT","Hydrant Refuelling","ハイドラント給油","하이드런트 급유","地下の配管からディスペンサー車で給油する方式","지하 배관에서 디스펜서 차량으로 급유하는 방식","Refuelling from underground pipes via a dispenser"],
["APT","Bowser","給油車（レフューラー）","급유차(바우저)","タンクに燃料を積んだ給油車","탱크에 연료를 실은 급유차","A tanker truck carrying fuel"],
["APT","Sustainable Aviation Fuel (SAF)","持続可能な航空燃料（SAF）","지속가능항공유(SAF)","廃油・植物などから作る、CO2の少ない航空燃料","폐유·식물 등으로 만드는 CO2가 적은 항공유","Aviation fuel made from waste oils and other sources with lower lifecycle CO2"],
["BIZ","CORSIA","CORSIA（国際航空の炭素の相殺制度）","CORSIA(국제항공 탄소상쇄제도)","国際線のCO2の増加分を相殺するICAOの制度","국제선 CO2 증가분을 상쇄하는 ICAO 제도","ICAO’s scheme to offset growth in international aviation CO2"],
["BIZ","Ground Handling Charges","地上業務の料金","지상조업 요금","ハンドリング会社に払う作業の料金","조업사에 지불하는 작업 요금","Fees paid to the handler for services"],
["BIZ","Landing Fee","着陸料","착륙료","着陸ごとに空港に払う料金。重さや騒音で変わる","착륙마다 공항에 내는 요금. 무게와 소음에 따라 달라진다","Airport charge per landing, varying with weight and noise"],
["BIZ","Navigation Charges","航行援助施設利用料","항행안전시설 사용료","管制・航法の施設の利用に対する料金","관제·항법 시설 이용에 대한 요금","Charges for air navigation services"],
["BIZ","Block Hours / Utilisation","稼働時間・機材稼働率","가동 시간·기재 가동률","1機あたり1日に飛んだ時間","기체 1대당 하루 비행 시간","Hours flown per aircraft per day"]
]);
