/* 航空用語辞典 第6部：販売・流通（NDC・運賃）／客室・乗務員／出入国・本人確認の新しい制度／カスハラ（2026-09）
   ※ 制度は2026年9月時点の公開情報。変わることがあるため最新の公式情報を確認（★） */
window.DICT=(window.DICT||[]).concat([
["BIZ","Metasearch","メタサーチ（価格比較サイト）","메타서치(가격 비교 사이트)","複数のサイトの価格を比べ、予約先へお客様を送るサービス","여러 사이트 가격을 비교해 예약처로 고객을 보내는 서비스","A service comparing prices across sites and referring customers to book"],
["BIZ","Dynamic Package","ダイナミックパッケージ","다이내믹 패키지","航空券とホテルをその時の価格で自由に組み合わせる旅行商品","항공권과 호텔을 그때 가격으로 자유롭게 조합하는 여행 상품","A travel product combining flights and hotels at live prices"],
["BIZ","Free Independent Travel (FIT)","個人旅行（FIT）","개별 여행(FIT)","団体でなく、個人が自由に日程を組む旅行","단체가 아니라 개인이 자유롭게 일정을 짜는 여행","Travel arranged individually rather than in a group"],
["BIZ","Offers and Orders","オファーとオーダー","오퍼와 오더","航空会社がその場で提案（オファー）を作り、一つの注文（オーダー）で管理する新しい販売の考え方","항공사가 그 자리에서 제안(오퍼)을 만들고 하나의 주문(오더)으로 관리하는 새 판매 개념","Modern airline retailing: dynamic offers managed as single orders"],
["BIZ","ONE Order","ワンオーダー","원 오더","予約記録・eチケット・EMDを一つの注文記録にまとめるIATAの標準","예약 기록·전자항공권·EMD를 하나의 주문 기록으로 묶는 IATA 표준","IATA standard replacing PNR, e-ticket and EMD with one order record"],
["BIZ","Aggregator (NDC)","アグリゲーター（NDC）","애그리게이터(NDC)","複数の航空会社のNDCをまとめて旅行会社につなぐ事業者","여러 항공사 NDC를 모아 여행사에 연결하는 사업자","A provider connecting sellers to many airlines’ NDC content"],
["BIZ","Distribution Cost Charge (GDS Surcharge)","GDSの追加料金","GDS 추가 요금","GDS経由の予約に航空会社が課す料金。2015年にルフトハンザ・グループが初めて導入","GDS 경유 예약에 항공사가 부과하는 요금. 2015년 루프트한자 그룹이 처음 도입","A charge airlines add to GDS bookings; first introduced by Lufthansa Group in 2015"],
["BIZ","Published Excursion Fare (PEX)","PEX運賃（特別運賃）","PEX 운임(특별 운임)","航空会社が設定する割引運賃。航空券だけで個人に売れる","항공사가 설정하는 할인 운임. 항공권만으로 개인에게 팔 수 있다","An airline-set discounted fare that can be sold as a ticket alone"],
["BIZ","Inclusive Tour Fare (IT)","IT運賃（包括旅行運賃）","IT 운임(포괄 여행 운임)","ホテルなど地上の手配と組み合わせて旅行会社が売る運賃","호텔 등 지상 수배와 조합해 여행사가 파는 운임","A fare sold by agencies only as part of a package with ground arrangements"],
["BIZ","Group Inclusive Tour Fare (GV)","GV運賃（グループ包括旅行運賃）","GV 운임(그룹 포괄 여행 운임)","グループの形のIT運賃。日本では1名から使えるGV1が多い","그룹 형태의 IT 운임. 일본에서는 1명부터 쓰는 GV1이 많다","A group-form IT fare; in Japan GV1, applicable from one passenger, is common"],
["BIZ","Tour Code","ツアーコード","투어 코드","IT運賃・特別な条件の発券で入れる識別の番号","IT 운임·특별 조건 발권 때 넣는 식별 번호","An identifier entered when ticketing IT or special fares"],
["BIZ","Void","VOID（発券の取り消し）","VOID(발권 취소)","発券の直後、決められた時間内に航空券を無効にすること","발권 직후 정해진 시간 안에 항공권을 무효로 하는 것","Cancelling a ticket within a set time after issue"],
["BIZ","Involuntary Refund","会社都合の払い戻し","비자발적 환불","欠航・大幅な時刻の変更など、航空会社の都合による払い戻し","결항·큰 시각 변경 등 항공사 사정에 의한 환불","A refund caused by the airline, such as a cancellation"],
["BIZ","Refund Application (RA)","払い戻しの申請（RA）","환불 신청(RA)","BSPLinkで航空会社に払い戻しを申請する手続き","BSPLink로 항공사에 환불을 신청하는 절차","Applying to the airline for a refund through BSPlink"],
["BIZ","Agency Debit Memo (ADM)","ADM（旅行会社への追加の請求）","ADM(여행사 추가 청구)","旅行会社の発券の誤りなどに対して航空会社が差額を請求する書類","여행사 발권 오류 등에 대해 항공사가 차액을 청구하는 서류","A memo charging an agency for ticketing errors"],
["BIZ","Agency Credit Memo (ACM)","ACM（旅行会社への返金）","ACM(여행사 반환)","航空会社から旅行会社へ金額を返すときの書類","항공사가 여행사에 금액을 돌려줄 때의 서류","A memo crediting an agency"],
["BIZ","Pseudo City Code (PCC)","PCC（GDSの事務所番号）","PCC(GDS 사무소 번호)","旅行会社がGDSで使う事務所の番号。販売の登録に使う","여행사가 GDS에서 쓰는 사무소 번호. 판매 등록에 쓴다","An agency’s office code in a GDS"],
["BIZ","Minimum Selling Price (MSP)","販売の最低価格（MSP）","최저 판매 가격(MSP)","団体などで下回ってはいけない価格の線","단체 등에서 밑돌면 안 되는 가격선","A floor price that sales must not go below"],
["BIZ","Volume Incentive (VI)","ボリュームインセンティブ（報奨金）","볼륨 인센티브(장려금)","販売の実績に応じて旅行会社に払う報奨","판매 실적에 따라 여행사에 지급하는 장려금","A reward paid to agencies based on sales volume"],
["BIZ","Override Commission","オーバーライド（追加の手数料）","오버라이드(추가 수수료)","基本の手数料に上乗せする手数料","기본 수수료에 얹는 수수료","Commission paid on top of the base rate"],
["BIZ","Wholesaler","ホールセラー","홀세일러","航空券・旅行商品をほかの旅行会社に卸す会社","항공권·여행 상품을 다른 여행사에 도매하는 회사","A company supplying tickets and products to other agencies"],
["BIZ","Free of Charge Ticket (FOC)","無償航空券（FOC）","무상 항공권(FOC)","団体の条件などで無償で出す航空券（例：15名ごとに1名）","단체 조건 등으로 무상 발행하는 항공권(예: 15명마다 1명)","A free ticket, e.g. one per 15 group passengers"],
["BIZ","Spot Fare","スポット運賃","스폿 운임","短い期間だけ出す思い切った運賃","짧은 기간만 내는 과감한 운임","A bold fare offered for a short window"],
["OPS","Able-Bodied Passenger (ABP)","非常口の座席のお客様（ABP）","비상구 좌석 승객(ABP)","緊急時に乗務員を手伝える条件を満たすお客様","비상시 승무원을 도울 조건을 갖춘 승객","A passenger able to assist crew in an emergency"],
["OPS","Crew Rest Period","乗務員の休息","승무원 휴식","次の勤務までに必要な最低の休息の時間","다음 근무까지 필요한 최소 휴식 시간","The minimum rest required before the next duty"],
["OPS","Standby Crew","スタンバイの乗務員","대기 승무원","欠員や遅れに備えて待機する乗務員","결원이나 지연에 대비해 대기하는 승무원","Crew on standby to cover absences or delays"],
["OPS","Crew Control","乗務員の管理（クルー・コントロール）","승무원 관리(크루 컨트롤)","乗務員の勤務・交代・残り時間を管理する部署","승무원 근무·교대·남은 시간을 관리하는 부서","The department managing crew duty, swaps and remaining hours"],
["OPS","Crew Alcohol Testing","乗務員のアルコール検査","승무원 알코올 검사","日本では操縦士・客室乗務員に乗務の前後の検査を義務付け","일본은 조종사·객실승무원에게 승무 전후 검사를 의무화","In Japan, pilots and cabin crew must be tested before and after duty"],
["OPS","Refusal to Carry","搭乗の拒否","탑승 거절","安全を害するおそれがあるときに運送約款にもとづき搭乗を断ること","안전을 해칠 우려가 있을 때 운송약관에 따라 탑승을 거절하는 것","Declining carriage under the conditions of carriage for safety reasons"],
["PAX","One ID","ワンアイディー（One ID）","원 아이디(One ID)","一度登録した顔などで、空港の手続きを続けて進めるIATAの考え方","한 번 등록한 얼굴 등으로 공항 절차를 이어서 진행하는 IATA 개념","IATA’s concept of enrolling once and using biometrics throughout"],
["PAX","Digital Travel Credential (DTC)","デジタルの渡航書類（DTC）","디지털 여행 서류(DTC)","旅券の情報をスマートフォンなどで使う仕組み","여권 정보를 스마트폰 등으로 쓰는 체계","Passport data held and presented digitally"],
["PAX","Entry/Exit System (EES)","EES（EUの出入国システム）","EES(EU 출입국 시스템)","EU以外の短期滞在者の出入国を顔・指紋で電子的に記録。2026年4月10日に完全運用","EU 외 단기 체류자의 출입국을 얼굴·지문으로 전자 기록. 2026년 4월 10일 완전 가동","EU system recording non-EU short-stay entries and exits biometrically; fully live 10 April 2026"],
["PAX","ETIAS","ETIAS（欧州の渡航認証）","ETIAS(유럽 여행 허가)","査証なしで欧州に入る人の事前の電子認証。開始日は未定（2026年9月時点）","무비자로 유럽에 들어가는 사람의 사전 전자 허가. 시작일 미정(2026년 9월 기준)","Pre-travel authorisation for visa-exempt visitors to Europe; start date not confirmed (Sept 2026)"],
["PAX","UK ETA","イギリスの電子渡航認証（ETA）","영국 전자여행허가(ETA)","査証なしでイギリスに入る人の事前の電子認証","무비자로 영국에 들어가는 사람의 사전 전자 허가","UK electronic travel authorisation for visa-exempt visitors"],
["PAX","REAL ID","REAL ID（アメリカ）","리얼 아이디(미국)","アメリカ国内線で必要な連邦の基準に合った身分証。2025年5月7日から完全実施","미국 국내선에 필요한 연방 기준 신분증. 2025년 5월 7일부터 완전 시행","US federal ID standard for domestic flights; enforced from 7 May 2025"],
["PAX","TSA ConfirmID","TSA ConfirmID","TSA ConfirmID","REAL IDなどがない人向けの45ドルの本人確認の手続き（2026年2月1日から）","REAL ID 등이 없는 사람용 45달러 신원 확인 절차(2026년 2월 1일부터)","A $45 identity verification for travellers without REAL ID (from 1 Feb 2026)"],
["PAX","Customer Harassment","カスタマーハラスメント（カスハラ）","고객 괴롭힘(갑질)","お客様からの行き過ぎた要求・暴言・暴力などで、働く人の心身を傷つける行為","고객의 지나친 요구·폭언·폭력 등으로 일하는 사람의 심신을 해치는 행위","Excessive demands, abuse or violence from customers that harm workers"],
["PAX","Emotional Labour","感情労働","감정노동","自分の感情を抑えて接客する仕事の負担","자기 감정을 억누르고 고객을 응대하는 일의 부담","The strain of managing one’s emotions in customer-facing work"]
]);
