/* 航空用語辞典 第2部：空港・施設／運航・運航管理／航空管制・航法／重量・搭載 */
window.DICT=(window.DICT||[]).concat([
["APT","IATA Airport Code","IATA空港コード","IATA 공항 코드","NRT・HNDのような3文字の空港コード。予約・手荷物で使う","NRT·HND 같은 3자리 공항 코드. 예약·수하물에 쓴다","Three-letter airport codes such as NRT, used in bookings and bags"],
["APT","ICAO Airport Code","ICAO空港コード","ICAO 공항 코드","RJAA・RJTTのような4文字の空港コード。運航・管制で使う","RJAA·RJTT 같은 4자리 공항 코드. 운항·관제에 쓴다","Four-letter codes such as RJAA, used in operations and ATC"],
["APT","Terminal","旅客ターミナル","여객 터미널","チェックイン・保安検査・出入国・搭乗の施設","체크인·보안검색·출입국·탑승 시설","The building for check-in, security, border control and boarding"],
["APT","Apron","エプロン（駐機場のある区域）","에이프런(계류장)","航空機が駐機・乗降・給油などをする区域","항공기가 주기·승하기·급유 등을 하는 구역","The area where aircraft park, load and refuel"],
["APT","Stand / Spot","スポット（駐機場所）","주기장(스폿)","1機が駐機する決められた場所","한 대가 주기하는 정해진 자리","The allocated parking position for one aircraft"],
["APT","Contact Stand","搭乗橋のあるスポット","탑승교 스폿","ターミナルに接して搭乗橋で乗り降りできるスポット","터미널에 붙어 탑승교로 승하기할 수 있는 주기장","A stand served by a boarding bridge"],
["APT","Remote Stand","沖止めスポット","원격 주기장","ターミナルから離れ、バスとステップで乗り降りするスポット","터미널에서 떨어져 버스와 스텝으로 승하기하는 주기장","A stand away from the terminal, reached by bus and steps"],
["APT","Passenger Boarding Bridge (PBB)","搭乗橋（ボーディングブリッジ）","탑승교","ターミナルと機体のドアをつなぐ通路","터미널과 기체 도어를 잇는 통로","The bridge connecting the terminal to the aircraft door"],
["APT","Taxiway","誘導路","유도로","滑走路とエプロンを結ぶ航空機の通り道","활주로와 계류장을 잇는 항공기 통로","The route connecting runways and aprons"],
["APT","Runway","滑走路","활주로","離陸・着陸に使う舗装された帯状の区域","이착륙에 쓰는 포장된 띠 모양 구역","The paved strip for take-off and landing"],
["APT","Airside","エアサイド（制限区域側）","에어사이드(보호구역 쪽)","保安検査・出国審査の後ろ側の区域","보안검색·출국심사 뒤쪽 구역","The area beyond security and passport control"],
["APT","Landside","ランドサイド（一般区域側）","랜드사이드(일반구역 쪽)","誰でも入れる保安検査前の区域","누구나 들어갈 수 있는 보안검색 전 구역","The public area before security"],
["APT","Slot","発着枠（スロット）","슬롯(발착 시각)","混雑空港で離陸・着陸できる時刻の枠","혼잡 공항에서 이착륙할 수 있는 시각의 틀","A permission to land or take off at a congested airport at a given time"],
["APT","Curfew","運用時間の制限（カーフュー）","운용 시간 제한(커퓨)","騒音対策などで夜間に離着陸できない時間","소음 대책 등으로 야간에 이착륙할 수 없는 시간","Hours when flights are banned, usually at night for noise"],
["APT","Airport Operations Committee (AOC)","空港運営委員会（AOC）","공항운영위원회(AOC)","空港の航空会社がつくる協議体","공항의 항공사들이 만드는 협의체","The committee of airlines operating at an airport"],
["APT","Ground Handling Agent (GHA)","ハンドリング会社","지상조업사","航空会社から委託されて地上の業務を行う会社","항공사 위탁을 받아 지상 업무를 하는 회사","A company providing ground services under contract to airlines"],
["APT","Standard Ground Handling Agreement (SGHA)","標準地上業務委託契約（SGHA）","표준 지상조업 계약(SGHA)","IATAのひな形にもとづく地上業務の委託契約","IATA 서식에 따른 지상조업 위탁 계약","The IATA-model contract for ground handling"],
["APT","Service Level Agreement (SLA)","サービス水準の合意（SLA）","서비스 수준 합의(SLA)","品質の基準と測り方を決めた合意","품질 기준과 측정법을 정한 합의","The agreed quality standards and how they are measured"],
["APT","Ground Support Equipment (GSE)","地上支援器材（GSE）","지상조업 장비(GSE)","ランプで使う車両・機材の総称","램프에서 쓰는 차량·장비의 총칭","Vehicles and equipment used on the ramp"],
["APT","Ground Power Unit (GPU)","地上電源車（GPU）","지상 전원 장치(GPU)","駐機中の機体に電気を送る装置","주기 중인 기체에 전기를 보내는 장치","Supplies electrical power to a parked aircraft"],
["APT","Pre-conditioned Air (PCA)","空調車（PCA）","공조 장치(PCA)","駐機中の客室に冷暖房の空気を送る装置","주기 중인 객실에 냉난방 공기를 보내는 장치","Supplies heated or cooled air to a parked aircraft"],
["APT","Auxiliary Power Unit (APU)","補助動力装置（APU）","보조동력장치(APU)","機体の尾部にある小さなエンジン。電気と空気をつくる","기체 꼬리의 작은 엔진. 전기와 공기를 만든다","The small engine in the tail providing power and air"],
["APT","Pushback","プッシュバック","푸시백","トーイングトラクターで機体を後ろへ押し出すこと","토잉 트랙터로 기체를 뒤로 밀어내는 것","Pushing the aircraft backwards off the stand with a tug"],
["APT","Chocks","車輪止め","고임목","駐機中の車輪の前後に置く止め","주기 중 바퀴 앞뒤에 두는 고임","Blocks placed against the wheels of a parked aircraft"],
["APT","Marshaller","マーシャラー（誘導員）","마셜러(유도원)","手信号で機体をスポットに誘導する係員","수신호로 기체를 주기장에 유도하는 직원","The person guiding the aircraft onto the stand by hand signals"],
["APT","Visual Docking Guidance System (VDGS)","自動駐機誘導装置","자동 주기 유도 장치","表示板で機体の停止位置を案内する装置","표시판으로 기체 정지 위치를 안내하는 장치","A display guiding the pilot to the stopping position"],
["APT","Foreign Object Debris (FOD)","異物（FOD）","이물질(FOD)","エンジンやタイヤを傷つけるおそれのある地上の落下物","엔진이나 타이어를 손상시킬 수 있는 지상의 떨어진 물건","Loose items on the ground that can damage aircraft"],
["APT","De-icing / Anti-icing","除氷・防氷","제빙·방빙","機体の雪・氷を取り除き、再び付かないようにする作業","기체의 눈·얼음을 제거하고 다시 붙지 않게 하는 작업","Removing ice and snow and preventing it returning"],
["APT","Holdover Time (HOT)","ホールドオーバータイム","홀드오버 타임","防氷液が効果を保つ目安の時間","방빙액이 효과를 유지하는 기준 시간","How long the anti-icing fluid is expected to protect"],
["OPS","Scheduled Time of Departure (STD)","出発予定時刻（STD）","출발 예정 시각(STD)","時刻表上の出発時刻（ブロックアウト）","시간표상 출발 시각(블록 아웃)","The timetabled departure (off-block) time"],
["OPS","Scheduled Time of Arrival (STA)","到着予定時刻（STA）","도착 예정 시각(STA)","時刻表上の到着時刻（ブロックイン）","시간표상 도착 시각(블록 인)","The timetabled arrival (on-block) time"],
["OPS","Estimated Time (ETD/ETA)","見込み時刻（ETD・ETA）","예상 시각(ETD·ETA)","現在の見込みの出発・到着時刻","현재 예상되는 출발·도착 시각","The currently expected departure or arrival time"],
["OPS","Actual Time (ATD/ATA)","実際の時刻（ATD・ATA）","실제 시각(ATD·ATA)","実際に出発・到着した時刻","실제로 출발·도착한 시각","The actual departure or arrival time"],
["OPS","Off-block / On-block","ブロックアウト・ブロックイン","블록 아웃·블록 인","車輪止めを外して動き出す／スポットに止まる時刻","고임목을 빼고 움직이기 시작한/주기장에 선 시각","When the aircraft leaves or reaches the stand"],
["OPS","Block Time","ブロックタイム","블록 타임","ブロックアウトからブロックインまでの時間","블록 아웃부터 블록 인까지의 시간","Time from off-block to on-block"],
["OPS","On-time Performance (OTP)","定時運航率","정시 운항률","決められた分数以内に出発・到着した便の割合","정해진 분 이내에 출발·도착한 편의 비율","The share of flights departing or arriving within a set margin"],
["OPS","Delay Code","遅延コード","지연 코드","遅延の原因を示すIATAの2桁の数字","지연 원인을 나타내는 IATA 두 자리 숫자","IATA’s two-digit codes for delay causes"],
["OPS","Turnaround","ターンアラウンド","턴어라운드","到着から次の出発までの地上での作業","도착부터 다음 출발까지의 지상 작업","All ground activity between arrival and the next departure"],
["OPS","Minimum Ground Time (MGT)","最小地上時間","최소 지상 시간","ターンアラウンドに必要な最短の時間","턴어라운드에 필요한 최소 시간","The shortest time needed to turn an aircraft round"],
["OPS","Operations Control Centre (OCC)","運航管理センター（OCC）","종합통제센터(OCC)","運航の状況を一元的に管理する部署","운항 상황을 일원적으로 관리하는 부서","The centre that runs the airline’s daily operation"],
["OPS","Flight Dispatcher","運航管理者（ディスパッチャー）","운항관리사","飛行計画・燃料・気象などを検討して出発を判断する担当","비행계획·연료·기상 등을 검토해 출발을 판단하는 담당","The person who plans flights and shares release decisions with the captain"],
["OPS","Flight Plan","飛行計画","비행계획","経路・高度・燃料などを定めた計画。管制へ提出する","경로·고도·연료 등을 정한 계획. 관제에 제출","The plan of route, levels and fuel, filed with ATC"],
["OPS","Pilot in Command (PIC)","機長","기장","便の安全に最終的な責任を持つ操縦士","편의 안전에 최종 책임을 지는 조종사","The pilot with final responsibility for the flight"],
["OPS","Flight Duty Period (FDP)","乗務時間の上限（FDP）","비행 근무 시간(FDP)","乗務員が勤務できる時間の上限の規則","승무원이 근무할 수 있는 시간의 상한 규칙","Rules limiting how long crew may work"],
["OPS","Minimum Equipment List (MEL)","最低装備品目録（MEL）","최소장비목록(MEL)","一部の装備が使えなくても運航できる条件を定めた目録","일부 장비를 못 써도 운항할 수 있는 조건을 정한 목록","The list of equipment that may be inoperative for dispatch"],
["OPS","Aircraft on Ground (AOG)","AOG（整備で飛べない状態）","AOG(정비로 운항 불가)","部品の不具合などで機体が飛べない状態","부품 결함 등으로 기체가 운항할 수 없는 상태","An aircraft unable to fly until a part or repair arrives"],
["OPS","Extended Operations (ETOPS/EDTO)","双発機の長距離運航（ETOPS）","쌍발기 장거리 운항(ETOPS)","双発機が代替空港から遠い経路を飛ぶための承認","쌍발기가 대체 공항에서 먼 경로를 비행하기 위한 승인","Approval for twin-engine aircraft to fly far from diversion airports"],
["OPS","Alternate Airport","代替空港","교체 공항","目的地に降りられないときに向かう空港","목적지에 내리지 못할 때 향하는 공항","The airport to divert to if the destination cannot be used"],
["OPS","Tankering","燃料の持ち運び（タンカリング）","연료 탱커링","出発地で燃料を多めに積み、先の空港での給油を減らすこと","출발지에서 연료를 넉넉히 싣고 다음 공항 급유를 줄이는 것","Carrying extra fuel to reduce refuelling at the next stop"],
["OPS","Wet Lease / Dry Lease","ウェットリース・ドライリース","웻리스·드라이리스","乗務員付きで借りる／機体だけ借りるリース","승무원 포함 임차/기체만 임차","Leasing an aircraft with crew, or the aircraft alone"],
["OPS","ACMI","ACMI（機体・乗員・整備・保険付きのリース）","ACMI(기체·승무원·정비·보험 포함 리스)","機体・乗員・整備・保険をまとめて借りる形","기체·승무원·정비·보험을 묶어 빌리는 형태","Aircraft, crew, maintenance and insurance leased together"],
["OPS","Charter Flight","チャーター便","전세편","特定の団体・目的のために借り切った便","특정 단체·목적을 위해 전세 낸 편","A flight hired for a particular group or purpose"],
["OPS","Ferry Flight","回航（フェリー）","페리 비행","お客様を乗せずに機体を移動させる飛行","승객 없이 기체를 이동시키는 비행","A flight moving an aircraft without passengers"],
["ATC","Air Traffic Control (ATC)","航空管制（ATC）","항공교통관제(ATC)","航空機の安全な間隔を保つための指示・許可","항공기의 안전 간격을 유지하기 위한 지시·허가","Instructions and clearances keeping aircraft safely separated"],
["ATC","Air Traffic Flow Management (ATFM)","航空交通流管理（ATFM）","항공교통흐름관리(ATFM)","混雑を防ぐために出発の時刻などを調整する仕組み","혼잡을 막기 위해 출발 시각 등을 조정하는 체계","Managing traffic flow by adjusting departure times"],
["ATC","Calculated Take-off Time (CTOT)","離陸の指定時刻（CTOT）","지정 이륙 시각(CTOT)","流れの管理で指定された離陸の時刻","흐름 관리로 지정된 이륙 시각","The take-off time allocated by flow management"],
["ATC","NOTAM","NOTAM（航空情報）","NOTAM(항공고시보)","空港・航空路の変更や制限を知らせる情報","공항·항로의 변경이나 제한을 알리는 정보","Notices about changes and restrictions at airports and on routes"],
["ATC","AIP","AIP（航空路誌）","AIP(항공정보간행물)","各国が発行する空港・航空路の公式の情報","각국이 발행하는 공항·항로의 공식 정보","Each country’s official publication of aeronautical information"],
["ATC","Instrument Landing System (ILS)","計器着陸装置（ILS）","계기착륙장치(ILS)","電波で機体を滑走路へ導く着陸の装置","전파로 기체를 활주로로 유도하는 착륙 장치","A radio system guiding aircraft to the runway"],
["ATC","Visual Flight Rules / Instrument Flight Rules","有視界飛行方式・計器飛行方式","시계비행·계기비행","目で見て飛ぶ方式と、計器と管制に従って飛ぶ方式","눈으로 보고 나는 방식과 계기·관제에 따라 나는 방식","Flying by visual reference or by instruments under ATC"],
["ATC","Squawk / Transponder Code","トランスポンダーのコード","트랜스폰더 코드","管制のレーダーで機体を見分ける4桁の番号","관제 레이더에서 기체를 식별하는 4자리 번호","The four-digit code identifying an aircraft on radar"],
["ATC","Squawk 7500 / 7600 / 7700","緊急のコード（7500・7600・7700）","비상 코드(7500·7600·7700)","7500は不法な妨害、7600は無線の故障、7700は緊急","7500은 불법 방해, 7600은 무선 고장, 7700은 비상","7500 unlawful interference, 7600 radio failure, 7700 emergency"],
["ATC","Mayday / Pan-Pan","メーデー・パンパン","메이데이·팬팬","遭難の緊急通報／緊急だが遭難ではない通報","조난 긴급 통보/긴급하지만 조난은 아닌 통보","Distress call, and urgency call short of distress"],
["ATC","Phonetic Alphabet","フォネティックコード","음성 문자","Alpha・Bravo・Charlieなど文字を聞き間違えないための読み方","Alpha·Bravo·Charlie 등 글자를 잘못 듣지 않기 위한 읽는 법","Alpha, Bravo, Charlie: the spelling alphabet"],
["ATC","Coordinated Universal Time (UTC)","協定世界時（UTC）","협정 세계시(UTC)","航空で共通に使う時刻。日本時間はUTC＋9","항공에서 공통으로 쓰는 시각. 일본·한국은 UTC+9","The common time reference in aviation; Japan and Korea are UTC+9"],
["ATC","Flight Level (FL)","フライトレベル","비행 고도(FL)","標準気圧で表す高度。FL350は約35,000フィート","표준기압으로 나타내는 고도. FL350은 약 35,000피트","Altitude on standard pressure; FL350 is about 35,000 ft"],
["ATC","Nautical Mile (NM) / Knot (kt)","海里・ノット","해리·노트","距離の単位（1海里＝1,852m）と速さの単位","거리 단위(1해리=1,852m)와 속도 단위","Distance unit of 1,852 m, and speed in nautical miles per hour"],
["WB","Load Control","搭載管理（ロードコントロール）","탑재관리","重さと重心を計算し、安全に積むよう管理する仕事","무게와 무게중심을 계산해 안전하게 싣도록 관리하는 일","Planning and checking weight and balance for safe loading"],
["WB","Weight and Balance (W&B)","重量重心","중량 및 균형","機体の重さと重心の位置","기체의 무게와 무게중심 위치","The aircraft’s weights and centre of gravity"],
["WB","Loadsheet","ロードシート","로드시트","重さと重心が範囲内であることを示す書類","무게와 무게중심이 범위 안임을 보여 주는 서류","The document showing weights and balance are within limits"],
["WB","Loading Instruction/Report (LIR)","搭載指示書（LIR）","탑재 지시서(LIR)","どの貨物室に何を積むかの指示と、その結果の報告","어느 화물칸에 무엇을 실을지의 지시와 그 결과 보고","Instructions on what goes in which hold, and the loaders’ report"],
["WB","Notification to Captain (NOTOC)","機長への通知書（NOTOC）","기장 통보서(NOTOC)","危険物や特別な搭載物を機長に知らせる書類","위험물이나 특수 탑재물을 기장에게 알리는 서류","The document informing the captain of dangerous goods and special loads"],
["WB","Last Minute Change (LMC)","最後の変更（LMC）","최종 변경(LMC)","ロードシートを渡した後の小さな変更","로드시트를 건넨 뒤의 작은 변경","A small change after the loadsheet is issued"],
["WB","Dry Operating Weight (DOW)","乾燥運航重量（DOW）","건조 운항 중량(DOW)","機体・乗務員・備品を含み、燃料と搭載物を除いた重さ","기체·승무원·비품을 포함하고 연료와 탑재물을 뺀 무게","Aircraft, crew and equipment, without fuel or payload"],
["WB","Zero Fuel Weight (ZFW)","無燃料重量（ZFW）","무연료 중량(ZFW)","DOWに搭載物を足した重さ","DOW에 탑재물을 더한 무게","DOW plus traffic load"],
["WB","Take-off Weight (TOW)","離陸重量（TOW）","이륙 중량(TOW)","ZFWに離陸燃料を足した重さ","ZFW에 이륙 연료를 더한 무게","ZFW plus take-off fuel"],
["WB","Landing Weight (LAW)","着陸重量（LAW）","착륙 중량(LAW)","TOWから飛行燃料を引いた重さ","TOW에서 비행 연료를 뺀 무게","TOW minus trip fuel"],
["WB","Maximum Take-off Weight (MTOW)","最大離陸重量（MTOW）","최대 이륙 중량(MTOW)","離陸できる重さの上限","이륙할 수 있는 무게의 상한","The highest weight permitted for take-off"],
["WB","Underload","余裕（アンダーロード）","여유 중량(언더로드)","あと何kg積めるか","앞으로 몇 kg 더 실을 수 있는지","How much more load can be added"],
["WB","Payload","有償搭載量（ペイロード）","유상 탑재량(페이로드)","お客様・手荷物・貨物・郵便の重さ","승객·수하물·화물·우편의 무게","The weight of passengers, bags, cargo and mail"],
["WB","Centre of Gravity (CG)","重心（CG）","무게중심(CG)","機体の重さがつり合う点。前後の範囲が決まっている","기체 무게가 균형을 이루는 점. 앞뒤 범위가 정해져 있다","The balance point, which must stay within set limits"],
["WB","Mean Aerodynamic Chord (MAC)","平均空力翼弦（MAC）","평균 공력 시위(MAC)","重心の位置を%で表すための主翼の基準の長さ","무게중심 위치를 %로 나타내기 위한 주익의 기준 길이","The wing reference length used to express CG as a percentage"],
["WB","Balance Index","重心の指数（インデックス）","무게중심 지수(인덱스)","重心の計算を簡単にするための数値","무게중심 계산을 간단히 하기 위한 수치","A number simplifying centre of gravity calculations"],
["WB","Stabiliser Trim","水平安定板の設定（スタビ・トリム）","수평안정판 설정(스태브 트림)","離陸時の重心に合わせた水平尾翼の設定","이륙 시 무게중심에 맞춘 수평꼬리날개 설정","The tailplane setting matched to the take-off centre of gravity"],
["WB","Standard Weights","標準重量","표준 중량","お客様・手荷物の重さを計算に使う決まった値","승객·수하물 무게 계산에 쓰는 정해진 값","Fixed weights used for passengers and bags in calculations"],
["WB","Unit Load Device (ULD)","ULD（コンテナ・パレット）","ULD(컨테이너·팔레트)","手荷物・貨物をまとめて積むコンテナやパレット","수하물·화물을 묶어 싣는 컨테이너나 팔레트","Containers and pallets for loading bags and cargo"],
["WB","Bulk Hold","バルク貨物室","벌크 화물칸","コンテナを使わずにばらで積む貨物室","컨테이너 없이 낱개로 싣는 화물칸","A hold loaded loose rather than with containers"],
["WB","Tail Tipping","尻もち（テールティッピング）","꼬리 내려앉음(테일 티핑)","積み下ろしの順番の誤りで機体の後ろが沈むこと","싣고 내리는 순서 잘못으로 기체 뒤가 내려앉는 것","The tail sinking to the ground from loading in the wrong order"]
]);
