/* 航空用語辞典 第5部：ランプ・GSE・ULD／出入国の新しい仕組み（日本）／特別サービスの追加コード／法令・制度（日韓）
   ※ ULDの記号はIATA ULD規則の考え方、Visit Japan Web・共同キオスク・免税のリファンド方式はデジタル庁などの公開情報（2026年時点）による。制度は変わるため最新の公式情報を確認（★） */
window.DICT=(window.DICT||[]).concat([
["WB","ULD Type Code","ULDの形式記号","ULD 형식 기호","3文字の記号。1文字目は種類（A＝認定コンテナ、P＝認定パレット）、2文字目は底板の大きさ、3文字目は形・扉","3자리 기호. 첫째는 종류(A=인증 컨테이너, P=인증 팔레트), 둘째는 바닥판 크기, 셋째는 모양·문","Three letters: category (A certified container, P certified pallet), base size, then contour and door"],
["WB","AKE (LD3)","AKE（LD3コンテナ）","AKE(LD3 컨테이너)","双通路機の床下で最も多く使われる片側が斜めのコンテナ","이중 통로기 하부에서 가장 많이 쓰는 한쪽이 비스듬한 컨테이너","The most common lower-deck container on wide-bodies, with one angled side"],
["WB","AKH (LD3-45)","AKH（LD3-45コンテナ）","AKH(LD3-45 컨테이너)","A320系列など単通路機の床下用の背の低いコンテナ","A320 계열 등 단일 통로기 하부용 낮은 컨테이너","A lower-height container for narrow-body holds such as the A320 family"],
["WB","PMC / PAG / PLA","PMC・PAG・PLA（パレット）","PMC·PAG·PLA(팔레트)","PMCは125×96インチ、PAGは125×88インチの平らなパレット。PLAは床下用の半分の大きさ","PMC는 125×96인치, PAG는 125×88인치 평판 팔레트. PLA는 하부용 절반 크기","Flat pallets: PMC 125×96 in, PAG 125×88 in; PLA is a half-size lower-deck pallet"],
["WB","ULD Serviceability","ULDの使用可否の点検","ULD 사용 가부 점검","破損・変形がないかを確かめ、使えないULDは搭載しない","파손·변형이 없는지 확인하고 못 쓰는 ULD는 싣지 않는다","Checking ULDs for damage; unserviceable units must not be loaded"],
["WB","Net and Strap","ネット・ストラップ","네트·스트랩","パレットの荷物を固定する網とベルト","팔레트 짐을 고정하는 그물과 벨트","Nets and straps securing loads on pallets"],
["APT","Belt Loader","ベルトローダー","벨트 로더","手荷物をベルトで貨物室へ運ぶ車両","수하물을 벨트로 화물칸에 옮기는 차량","A vehicle with a conveyor belt for loading loose bags"],
["APT","High Loader (Main Deck / Lower Deck Loader)","ハイリフトローダー","하이 로더","ULDを持ち上げて貨物室へ入れる車両","ULD를 들어 올려 화물칸에 넣는 차량","A lift platform loading ULDs into the hold"],
["APT","Dolly","ドーリー","돌리","ULDを載せて牽引する台車","ULD를 실어 견인하는 대차","A trailer carrying a ULD"],
["APT","Baggage Cart","手荷物カート（バゲージカート）","수하물 카트","ばらの手荷物を運ぶ荷台付きの台車","낱개 수하물을 옮기는 적재함 대차","A trailer carrying loose bags"],
["APT","Tug / Tractor","トーイングトラクター（牽引車）","견인차(터그)","カート・ドーリーを牽引する車両","카트·돌리를 끄는 차량","The vehicle towing carts and dollies"],
["APT","Towbarless Tractor","トーバーレス牽引車","토바리스 견인차","前輪を持ち上げて機体を押す・引く車両","앞바퀴를 들어 올려 기체를 밀고 당기는 차량","A tug that lifts the nose wheel to push or tow the aircraft"],
["APT","Passenger Steps","パッセンジャーステップ（タラップ）","승객용 스텝(트랩)","沖止めで乗り降りに使う階段車","원격 주기장에서 승하기에 쓰는 계단 차량","Mobile stairs for boarding at remote stands"],
["APT","Ambulift","アンビュリフト（リフト付き車両）","앰뷸리프트","車いすのお客様を機体のドアの高さまで運ぶ車両","휠체어 승객을 기체 도어 높이까지 옮기는 차량","A high-lift vehicle for passengers who cannot use stairs"],
["APT","Catering Truck (Hi-lift)","機内食の搬入車（ハイリフト）","기내식 차량(하이리프트)","荷台を持ち上げて機内食をギャレーへ運ぶ車両","적재함을 올려 기내식을 갤리로 옮기는 차량","A lift truck delivering catering to the galley"],
["APT","Lavatory / Water Service","汚水処理・給水","오수 처리·급수","化粧室の汚水を抜き、飲料水を補給する作業","화장실 오수를 빼고 음용수를 보충하는 작업","Emptying toilets and replenishing potable water"],
["APT","Wing Walker","ウィングウォーカー","윙워커","機体の移動のときに翼の先の安全を見る係員","기체 이동 때 날개 끝 안전을 살피는 직원","The person watching wingtip clearance while the aircraft moves"],
["APT","Headset Operator","ヘッドセット担当（プッシュバック時）","헤드셋 담당(푸시백 시)","有線・無線で操縦室と話しながらプッシュバックを進める係員","유선·무선으로 조종실과 교신하며 푸시백을 진행하는 직원","The ground crew member talking to the flight deck during pushback"],
["APT","Anti-collision Beacon","衝突防止灯（ビーコン）","충돌 방지등(비컨)","点灯中はエンジンの始動や移動が近いので機体に近づかない","켜져 있으면 엔진 시동·이동이 임박했으므로 기체에 다가가지 않는다","A red flashing light meaning engines are about to start or are running"],
["APT","Jet Blast","ジェットブラスト（排気流）","제트 블라스트(배기류)","エンジンの後ろの強い排気。人や車両を吹き飛ばす危険","엔진 뒤의 강한 배기. 사람·차량을 날려 버릴 위험","The powerful exhaust behind a running engine"],
["APT","Engine Danger Zone","エンジンの危険区域","엔진 위험 구역","吸い込みと排気の危険がある前後の区域","흡입과 배기 위험이 있는 앞뒤 구역","The areas in front of and behind engines where ingestion or blast can injure"],
["APT","Equipment Restraint Area (ERA)","器材の待機区域（ERA）","장비 대기 구역(ERA)","機体が入るまでGSEが待つ区域。線の外で待つ","기체가 들어올 때까지 GSE가 기다리는 구역. 선 밖에서 대기","The marked area where GSE must wait until the aircraft is parked"],
["APT","FOD Walk","FODウォーク（異物の点検）","FOD 워크(이물질 점검)","スポットを歩いて落下物を拾う点検","주기장을 걸으며 떨어진 물건을 줍는 점검","Walking the stand to pick up debris"],
["APT","Stand Allocation","スポットの割り当て","주기장 배정","空港・航空会社がどの便をどのスポットに入れるかを決めること","공항·항공사가 어느 편을 어느 주기장에 넣을지 정하는 것","Assigning flights to parking stands"],
["APT","Baggage Reclaim / Carousel","手荷物受取所・ターンテーブル","수하물 수취대·턴테이블","到着のお客様が手荷物を受け取る場所と回転台","도착 승객이 수하물을 찾는 곳과 회전대","Where arriving passengers collect bags"],
["APT","Transfer Desk","乗り継ぎカウンター","환승 카운터","乗り継ぎのお客様の搭乗券の発行・案内をする窓口","환승 승객의 탑승권 발급·안내를 하는 창구","The counter serving connecting passengers"],
["PAX","Visit Japan Web (VJW)","Visit Japan Web（入国手続のオンラインサービス）","Visit Japan Web(입국 절차 온라인 서비스)","日本の入国審査・税関申告の情報を事前に登録するデジタル庁のサービス。現在は1つのQRコードで両方の手続きができる","일본 입국 심사·세관 신고 정보를 미리 등록하는 디지털청 서비스. 현재는 QR 코드 하나로 두 절차 모두 가능","Japan’s online service for immigration and customs; one QR code now covers both"],
["PAX","Joint Kiosk (Japan)","共同キオスク（入管・税関）","공동 키오스크(입국·세관)","QRコードと旅券を読み取り、入国審査と税関の情報を一度に提供する端末。成田・羽田・関西・福岡などで導入","QR 코드와 여권을 읽어 입국 심사와 세관 정보를 한 번에 제공하는 단말. 나리타·하네다·간사이·후쿠오카 등에 도입","Kiosks reading the QR code and passport for immigration and customs together"],
["PAX","Automated Border Gate","自動化ゲート（顔認証ゲート）","자동 출입국 심사대(안면 인식)","旅券と顔の照合で出入国の審査を行うゲート","여권과 얼굴 대조로 출입국 심사를 하는 게이트","Gates checking passport and face for border control"],
["PAX","Biometric Boarding","顔認証による搭乗（例：Face Express）","안면 인식 탑승","チェックインで登録した顔で、保安検査・搭乗を手ぶらで通る仕組み","체크인 때 등록한 얼굴로 보안검색·탑승을 통과하는 체계","Using a face registered at check-in to pass security and boarding"],
["PAX","Tax-free Refund Scheme (Japan)","免税のリファンド方式（日本）","면세 환급 방식(일본)","2026年11月から、購入時に消費税を払い、出国時に払い戻しを受ける方式へ移行","2026년 11월부터 구입 시 소비세를 내고 출국 시 환급받는 방식으로 이행","From November 2026, Japan moves to charging consumption tax at purchase and refunding it on departure"],
["PAX","K-ETA","K-ETA（韓国の電子渡航認証）","K-ETA(전자여행허가)","査証なしで韓国に入国する人が事前に受ける電子の許可。対象・免除の国は変わる","무비자로 한국에 입국하는 사람이 사전에 받는 전자 허가. 대상·면제 국가는 바뀐다","Korea’s electronic travel authorisation for visa-free visitors; coverage changes"],
["PAX","Gate Change","搭乗口の変更","탑승구 변경","機材・スポットの都合で搭乗口が変わること。案内・放送・表示をすべて更新する","기재·주기장 사정으로 탑승구가 바뀌는 것. 안내·방송·표시를 모두 갱신","A change of departure gate; update displays, announcements and staff"],
["PAX","No Record (NOREC)","予約の記録がないお客様（NOREC）","예약 기록 없는 승객(NOREC)","航空券はあるが予約の記録が見つからないお客様","항공권은 있지만 예약 기록을 찾을 수 없는 승객","A passenger holding a ticket with no matching booking"],
["PAX","VIP / CIP","VIP・CIP（重要なお客様）","VIP·CIP(주요 승객)","政府要人・企業の重要なお客様。案内と情報の扱いに注意","정부 요인·기업 주요 고객. 안내와 정보 취급에 주의","Very important or commercially important passengers"],
["PAX","Staff Travel (ID / NRSA)","社員の優待搭乗（空席利用）","직원 우대 탑승(공석 이용)","社員が空席を利用して搭乗する制度。一般のお客様が優先","직원이 빈 좌석을 이용해 탑승하는 제도. 일반 승객이 우선","Airline staff travelling standby on spare seats"],
["SSR","WCOB","WCOB（機内用車いす）","WCOB(기내용 휠체어)","機内で使う車いすが必要なお客様","기내에서 쓸 휠체어가 필요한 승객","Passenger needing an on-board wheelchair"],
["SSR","MAAS","MAAS（案内・見守りの依頼）","MAAS(안내·보살핌 요청)","乗り継ぎや移動の案内・見守りが必要なお客様（特別な理由のない支援）","환승이나 이동 안내·보살핌이 필요한 승객","Meet and assist: passenger needing escort or guidance"],
["SSR","LANG","LANG（言語の支援）","LANG(언어 지원)","特定の言語しか話せないお客様","특정 언어만 할 수 있는 승객","Passenger who speaks only a specific language"],
["SSR","SEMN","SEMN（船員）","SEMN(선원)","船に乗り継ぐ船員のお客様。書類の条件が違うことがある","배로 갈아타는 선원 승객. 서류 조건이 다를 수 있다","A seafarer joining or leaving a ship"],
["SSR","XBAG","XBAG（追加の手荷物）","XBAG(추가 수하물)","事前購入した追加の手荷物","사전 구매한 추가 수하물","Pre-paid excess baggage"],
["SSR","SPEQ","SPEQ（スポーツ用品）","SPEQ(스포츠 용품)","ゴルフ・スキーなどのスポーツ用品","골프·스키 등 스포츠 용품","Sports equipment"],
["ORG","Civil Aeronautics Act (Japan)","航空法（日本）","항공법(일본)","日本の航空の安全・運航・事業の基本の法律","일본의 항공 안전·운항·사업의 기본 법률","Japan’s basic law on aviation safety, operations and business"],
["ORG","Immigration Control and Refugee Recognition Act","出入国管理及び難民認定法（入管法）","출입국관리 및 난민인정법(일본)","日本の出入国・在留の基本の法律","일본의 출입국·재류 기본 법률","Japan’s law on immigration and residence"],
["ORG","Customs Act / Quarantine Act (Japan)","関税法・検疫法（日本）","관세법·검역법(일본)","税関の手続きと、感染症の検疫の基本の法律","세관 절차와 감염병 검역의 기본 법률","Japan’s laws on customs and quarantine"],
["ORG","Aviation Safety Act (Korea)","航空安全法（韓国）","항공안전법","韓国の航空の安全・運航の基本の法律","한국의 항공 안전·운항 기본 법률","Korea’s basic law on aviation safety"],
["ORG","Aviation Security Act (Korea)","航空保安法（韓国）","항공보안법","韓国の航空保安の基本の法律。保安計画・教育などを定める","한국 항공보안의 기본 법률. 보안계획·교육 등을 정함","Korea’s aviation security law, covering programmes and training"],
["ORG","Aviation Business Act (Korea)","航空事業法（韓国）","항공사업법","韓国の航空事業の法律。利用者の保護（案内の義務など）も定める","한국 항공사업 법률. 이용자 보호(안내 의무 등)도 정함","Korea’s aviation business law, including passenger protection duties"],
["ORG","Airport Facilities Act (Korea)","空港施設法（韓国）","공항시설법","韓国の空港・航行の施設の法律","한국 공항·항행 시설 법률","Korea’s law on airports and navigation facilities"],
["ORG","EU261","EU261（欧州の旅客の権利の規則）","EU261(유럽 승객 권리 규정)","欧州発着などの遅延・欠航・搭乗拒否の補償と世話を定めた規則","유럽 출발 등의 지연·결항·탑승 거절 보상과 돌봄을 정한 규정","The EU rules on compensation and care for delays, cancellations and denied boarding"],
["ORG","Tokyo Convention","東京条約","도쿄 협약","機内での犯罪・不法な行為と機長の権限を定めた条約","기내 범죄·불법 행위와 기장 권한을 정한 협약","The treaty on offences on board and the captain’s powers"],
["MSG","SITA","SITA（航空の通信会社）","SITA(항공 통신 회사)","航空会社・空港の電報・システムを支える業界の通信会社","항공사·공항 전보·시스템을 지원하는 업계 통신 회사","The industry-owned provider of airline communications and IT"],
["MSG","Teletype Address","電報のアドレス","전보 주소","空港3文字＋部署2文字＋航空会社2文字の7文字の宛先（例：NRTKLXX）","공항 3자리+부서 2자리+항공사 2자리의 7자리 수신처","A seven-letter address: airport, department and airline codes"],
["MSG","Estimated Time Message (ETM/EA/ED)","見込み時刻の電報","예상 시각 전보","出発・到着の見込みの変更を知らせる電報の要素","출발·도착 예상 변경을 알리는 전보 요소","Message elements giving revised estimated times"],
["MSG","Divert Message (DIV)","ダイバートの電報","회항 전보","目的地を変更したことを知らせる電報","목적지 변경을 알리는 전보","Message reporting a diversion"],
["OPS","Crew Briefing","乗務員のブリーフィング","승무원 브리핑","出発前に運航・客室の乗務員が情報を共有する打ち合わせ","출발 전 운항·객실 승무원이 정보를 공유하는 협의","The pre-flight meeting where crew share information"],
["OPS","Special Handling (SPHL)","特別な取り扱い","특별 취급","動物・遺体・貴重品・危険物など、手順が決まった搭載物","동물·유해·귀중품·위험물 등 절차가 정해진 탑재물","Loads needing defined procedures, such as animals or valuables"],
["OPS","Security Seal","保安シール","보안 봉인","扉や機内食のカートが開けられていないことを示す封印","문이나 기내식 카트가 열리지 않았음을 보여 주는 봉인","A seal showing a door or cart has not been opened"],
["WX","Typhoon","台風","태풍","北西太平洋の強い熱帯低気圧。欠航・振り替えの計画が必要","북서태평양의 강한 열대저기압. 결항·대체 계획이 필요","A strong tropical cyclone in the north-west Pacific"],
["WX","Snow Removal Plan","除雪計画","제설 계획","空港が滑走路・誘導路・エプロンの除雪の順番と時間を決めた計画","공항이 활주로·유도로·계류장 제설 순서와 시간을 정한 계획","The airport’s plan for clearing runways, taxiways and aprons"],
["BIZ","Slot Conference","スロット調整会議","슬롯 조정 회의","IATAの世界会議。季節ごとに混雑空港の発着枠を調整する","IATA 세계 회의. 계절마다 혼잡 공항의 발착 시각을 조정","IATA’s twice-yearly conference allocating slots at congested airports"],
["BIZ","Use It or Lose It (80/20 Rule)","80/20ルール","80/20 규칙","割り当てられた発着枠を一定の割合以上使わないと翌年に失う規則","배정받은 슬롯을 일정 비율 이상 쓰지 않으면 다음 해에 잃는 규칙","Slots must be used at least 80% of the time to be kept"]
]);
