/* 空港で使う書類と様式 — 英語の画面用データ（分類名・説明と各書類の解説） */
window.FORMS_EN={
f1:{name:"Passengers Needing Special Assistance",desc:"Forms used to confirm the information the airline needs for the safety of the passenger.",items:[
{n:"Unaccompanied Minor Request Form",w:"When a child travels alone (age ranges are set by each airline)",y:"To confirm who hands the child over at departure and who collects the child on arrival, so the handover is certain",f:["Child’s name, date of birth and age","Flight number, date and sector","Name, contact details and ID of the guardian at departure","Name, contact details and ID of the person collecting the child","Child’s language, health and any special notes","Guardian’s signature"],c:"Do not hand the child over if the collecting person cannot be identified. Check the airline’s rules on connecting flights (Ground Staff 1-7)",r:"With the handover record, for the period set by the airline"},
{n:"Pregnancy Confirmation Form",w:"When the stage of pregnancy falls within the range set by the airline",y:"For the safety of the passenger and the baby, and to prepare for any sudden change in condition on board",f:["Passenger name, flight number and date","Due date and weeks of pregnancy","Whether a doctor’s certificate is held, and its date","Statement of current condition","Passenger’s signature"],c:"The week limits and the validity of the certificate are set by the airline. Travel may not be possible, for example from 37 weeks (Ground Staff 1-6)",r:"For the period set by the airline"},
{n:"Medical Information Form (MEDIF)",w:"When a passenger with an illness or injury travels, or uses medical equipment or oxygen on board",y:"So the airline’s medical department can decide whether the passenger can fly and what support is needed",f:["Passenger and flight details","Diagnosis and symptoms (completed by a doctor)","Equipment, oxygen or escort required","Doctor’s name, contact details and signature","Passenger’s consent"],c:"This is medical personal information. Restrict access to those who need it. The decision is made by the airline’s medical department",r:"Stored and disposed of as personal information under the airline’s rules"},
{n:"Power Wheelchair Declaration",w:"When a power wheelchair is checked in",y:"To confirm the battery type and capacity and load it safely under the dangerous goods rules",f:["Passenger name and flight number","Wheelchair model, weight and dimensions","Battery type (lithium-ion and so on) and capacity (Wh)","Whether the battery can be removed, and terminal protection","Notes on folding and operation"],c:"Handling depends on the battery type and capacity. The captain may need to be notified (Ground Staff 1-13) ★",r:"Kept with the loading record"}]},
f2:{name:"Baggage",desc:"Forms used to confirm the conditions and the limits of liability with the passenger when accepting special baggage.",items:[
{n:"Limited Release (Damage Waiver) Form",w:"When accepting baggage that is already damaged, poorly packed or fragile",y:"To record the condition at the time of acceptance and make the limits of liability clear afterwards",f:["Passenger name, flight number and baggage tag number","Condition of the bag (existing damage, packing)","Explanation of the limits of liability","Signature of the passenger and of the staff member"],c:"Liability for damage caused by the airline’s own negligence cannot be waived. Also record the condition with photographs",r:"For the period set by the airline"},
{n:"Musical Instrument / Extra Seat Form",w:"When an instrument is carried into the cabin or on a purchased seat",y:"To confirm the size, how it will be secured and the limits of liability",f:["Passenger name and flight number","Type, dimensions and weight of the instrument","How it is carried (extra seat or overhead bin)","How it is secured","Passenger’s signature"],c:"When carried on a seat there are conditions for securing it and limits on which seats may be used (Ground Staff 1-10)",r:"For the period set by the airline"},
{n:"Live Animal Acceptance Form",w:"When a pet travels as checked baggage or in the cabin",y:"To confirm the animal’s condition, the risks of transport and the quarantine requirements of the arrival country",f:["Passenger name and flight number","Species, breed, age and weight (including the container)","Health condition and whether sedatives have been used","Confirmation that the container meets the conditions","Check of quarantine documents","Passenger’s signature"],c:"Some airlines do not accept short-nosed breeds. Also check restrictions in hot weather (Ground Staff 1-8) ★",r:"For the period set by the airline"},
{n:"Firearms and Bladed Items Handover Record",w:"When accepting hunting or sporting firearms, swords and similar items",y:"To record custody from acceptance to handover in line with the law",f:["Passenger name and flight number","Item, quantity and serial number","Check of the permit to possess","Whether ammunition is carried, and how much","Date, time and signatures for acceptance and handover"],c:"Follow the law and the airport’s procedures. Ammunition is also subject to the dangerous goods rules",r:"For the period required by law and by the airline"}]},
f3:{name:"Irregular Operations and Compensation",desc:"Forms used when a flight is disrupted or a passenger asks for compensation.",items:[
{n:"Delay / Cancellation Certificate",w:"When a passenger needs proof for their employer or insurer",y:"To certify the fact of the delay or cancellation",f:["Passenger name","Flight number, date and sector","Scheduled time and actual time","The fact of the delay or cancellation","Date of issue and issuer"],c:"Do not write the detailed cause or promise compensation. State the facts only (Ground Staff 5-4)",r:"Keep a record of issuance"},
{n:"Bank Transfer Form for Compensation",w:"When compensation is paid by transfer rather than in cash",y:"To receive the transfer details accurately",f:["Passenger name and contact details","Flight number, date and the case concerned","Bank, branch, account type and account name","Passenger’s signature"],c:"Treat account details as sensitive personal information and handle them under the rules after payment. Never send account numbers by email or chat",r:"As accounting evidence, for the period set by the airline"},
{n:"Refund Confirmation Form",w:"When a refund or a cancelled departure is processed at the airport",y:"To confirm the content of the refund with the passenger and record it",f:["Passenger name","Ticket number and flight number","What is refunded and how","Whether a service charge applies","Passenger’s signature"],c:"Refund conditions follow the fare rules. Tickets issued by a travel agency may have to be refunded through the agency",r:"Kept as accounting evidence"},
{n:"Passenger Claim Form",w:"When a passenger makes a claim about a delay, cancellation or baggage",y:"To record the claim accurately and pass it to the department that handles it",f:["Passenger name and contact details","Flight number and date","What happened and what the passenger is asking for","Attached documents (receipts and so on)","Date, time and name of the person receiving the claim"],c:"Some countries and airlines require the claim procedure to be displayed at the counter (Ground Staff 7-4)",r:"Managed until the case is closed, then kept for the period set by the airline"}]},
f4:{name:"Baggage Irregularities and Lost Property",desc:"Forms used when baggage does not arrive or is damaged, and when property is found.",items:[
{n:"Property Irregularity Report (PIR)",w:"When arriving baggage is missing, damaged or has items missing",y:"To record the case and start the search and claim process in the worldwide tracing system",f:["Passenger name, contact details and address during the stay","Flight number, sector and baggage tag number","Type, color, features and contents of the bag","Type of irregularity (missing, damaged, pilferage)","Date, time and name of the person taking the report"],c:"Under international convention, damage must be reported in writing within 7 days of receipt and delay within 21 days (Ground Staff 4-1, 4-2)",r:"Managed until the case is closed, then kept for the period set by the airline"},
{n:"Lost Property Receipt",w:"When property left on board or at the airport is returned to its owner",y:"To record that the item was returned to the right person",f:["Item name and features","Date, time and place it was found","Name of the person collecting it and how they were identified","Date, time and signature of collection","For postal return, the address and costs"],c:"Always verify identity. Items held beyond the storage period are dealt with under the law and airport procedures (Ground Staff 4-4)",r:"For the period set by the airline"}]},
f5:{name:"Station Operations",desc:"Records the station keeps for daily operations and for regulatory audits.",items:[
{n:"Training Record (Training Log)",w:"When training is given to your own staff or to ground handling staff",y:"To prove to the authorities in an audit that the training took place (Station Setup 5-3)",f:["Title, date, time and place of the training","Instructor","Names and companies of participants","Content and duration","Assessment results","Signatures of the instructor and participants"],c:"This is the record auditors look at most closely. Complete it on the day and keep it for the required period (for example, 3 years or more)",r:"For example, 3 years or more (check the airline and regulator’s rules) ★"},
{n:"Counter Briefing Sheet",w:"At the briefing before the counter opens",y:"To share the day’s flight-specific information with the whole team",f:["Flight number, date, aircraft type and gate","Booked numbers, premium cabins and passengers needing assistance","Special baggage and dangerous goods notes","Changes to procedures and notices from the authorities","Allocation of duties","Signatures of participants"],c:"The content of briefings is sometimes checked in audits (Ground Staff 2-1)",r:"For the period set by the airline"}]}
};
