/* よくある質問のデータ（日本語・한국어・English）— s:1 は航空会社・時期で違う項目、l はシリーズ1の関連記事 */
var DATA=[
{id:"q1",ja:"予約・チェックイン",ko:"예약·체크인",en:"Check-in",items:[
{ja:["チェックインは何時間前までに行けばいいですか？","国際線は出発の2〜3時間前にはカウンターへ。締め切りの時刻（例：出発の1時間前など）は航空会社・空港で違うので、予約の案内を確認してください。"],ko:["체크인은 몇 시간 전까지 가면 되나요?","국제선은 출발 2~3시간 전에는 카운터로. 마감 시각(예: 출발 1시간 전 등)은 항공사·공항마다 다르니 예약 안내를 확인하세요."],en:["How early should I arrive for check-in?","For international flights, be at the counter 2 to 3 hours before departure. Check-in closing times (for example, 1 hour before departure) differ by airline and airport, so check your booking information."],s:1},
{ja:["オンラインチェックインをすれば、空港のカウンターに行かなくてもいいですか？","預ける荷物がなく、搭乗券をスマートフォンなどで受け取れれば、直接保安検査場へ行ける場合があります。国際線ではパスポートの確認のためカウンターに寄る必要があることもあります。"],ko:["온라인 체크인을 하면 공항 카운터에 안 가도 되나요?","부칠 짐이 없고 탑승권을 스마트폰 등으로 받을 수 있으면 바로 보안검색장으로 갈 수 있는 경우가 있습니다. 국제선은 여권 확인을 위해 카운터에 들러야 할 때도 있습니다."],en:["If I check in online, do I still need to go to the counter?","If you have no bags to check and can get your boarding pass on your phone, you may be able to go straight to security. On international flights you may still need to stop at the counter for a passport check."]},
{ja:["名前のつづりがパスポートと違っていたら？","航空券の名前はパスポートと同じである必要があります。違いに気づいたら、すぐに予約した会社（航空会社・旅行会社）に連絡してください。訂正できる範囲は会社の規則によります。"],ko:["이름 철자가 여권과 다르면?","항공권 이름은 여권과 같아야 합니다. 차이를 발견하면 바로 예약한 곳(항공사·여행사)에 연락하세요. 정정 가능한 범위는 회사 규정에 따릅니다."],en:["What if the spelling of my name differs from my passport?","The name on your ticket must match your passport. Contact whoever issued your booking (the airline or travel agency) as soon as you notice. How much can be corrected depends on their rules."],s:1},
{ja:["座席は選べますか？","予約時・オンラインチェックイン時・カウンターで選べます。運賃によっては座席の指定が有料のこともあります。非常口の座席には条件があります。"],ko:["좌석을 고를 수 있나요?","예약 시·온라인 체크인 시·카운터에서 고를 수 있습니다. 운임에 따라 좌석 지정이 유료이기도 합니다. 비상구 좌석에는 조건이 있습니다."],en:["Can I choose my seat?","Yes, when booking, during online check-in or at the counter. Some fares charge for seat selection. Exit row seats have conditions."],l:"1-5"},
{ja:["非常口の座席に座る条件は？","緊急時に乗務員を手伝えること（一定の年齢以上、言葉が通じる、体の条件など）が求められます。条件を満たさない場合は座席を変更します。"],ko:["비상구 좌석에 앉는 조건은?","비상시 승무원을 도울 수 있을 것(일정 연령 이상, 언어 소통, 신체 조건 등)이 요구됩니다. 조건을 충족하지 못하면 좌석을 변경합니다."],en:["What are the conditions for sitting in an exit row?","You must be able to help the crew in an emergency (for example, above a certain age, able to understand instructions, and physically able). If you do not meet the conditions, your seat will be changed."],l:"1-5"},
{ja:["チェックインの締め切りに遅れたら乗れませんか？","締め切りを過ぎると、原則として搭乗手続きはできません。まず航空会社の係員に相談してください。次の便への変更の条件は運賃の規則によります。"],ko:["체크인 마감에 늦으면 못 타나요?","마감이 지나면 원칙적으로 탑승수속을 할 수 없습니다. 먼저 항공사 직원과 상의하세요. 다음 편 변경 조건은 운임 규정에 따릅니다."],en:["Can I still fly if I miss the check-in deadline?","After the deadline, check-in is normally closed. Speak to the airline staff first. Whether you can change to a later flight depends on your fare rules."]}]},
{id:"q2",ja:"手荷物",ko:"수하물",en:"Baggage",items:[
{ja:["預けられる荷物の重さと数は？","運賃・路線・航空会社で違います（例：1個23kgまで、など）。予約の確認の画面や航空会社のサイトで確認してください。超えると追加の料金がかかります。"],ko:["부칠 수 있는 짐의 무게와 개수는?","운임·노선·항공사마다 다릅니다(예: 1개 23kg까지 등). 예약 확인 화면이나 항공사 사이트에서 확인하세요. 초과하면 추가 요금이 듭니다."],en:["How much checked baggage can I take?","It depends on your fare, route and airline (for example, up to 23 kg per bag). Check your booking details or the airline’s website. Extra charges apply above the allowance."],s:1,l:"1-10"},
{ja:["モバイルバッテリーは預けられますか？","預けられません。機内に持ち込む必要があります。容量・個数の制限があり、機内での使用・充電が禁止されることもあります。"],ko:["보조배터리를 부칠 수 있나요?","부칠 수 없습니다. 기내에 가지고 타야 합니다. 용량·개수 제한이 있고 기내 사용·충전이 금지되기도 합니다."],en:["Can I check in a power bank?","No. Power banks must be carried in the cabin. There are limits on capacity and quantity, and using or charging them on board may be prohibited."],s:1,l:"1-13"},
{ja:["液体は機内に持ち込めますか？","国際線では、100ml以下の容器に入れ、1リットル以下の透明な袋にまとめれば持ち込めます。出国後の免税店で買った物は、条件付きで持ち込めます。"],ko:["액체를 기내에 반입할 수 있나요?","국제선은 100ml 이하 용기에 담아 1리터 이하 투명 봉투에 모으면 반입 가능합니다. 출국 후 면세점에서 산 것은 조건부로 반입 가능합니다."],en:["Can I take liquids on board?","On international flights, liquids must be in containers of 100 ml or less, packed in a clear bag of up to 1 liter. Duty-free items bought after departure immigration can be carried under certain conditions."],s:1},
{ja:["ゴルフバッグやスキーは預けられますか？","預けられます。無料の手荷物に含まれるか、追加の料金かは航空会社の規則によります。事前の連絡が必要なこともあります。"],ko:["골프백이나 스키를 부칠 수 있나요?","부칠 수 있습니다. 무료 수하물에 포함되는지, 추가 요금인지는 항공사 규정에 따릅니다. 사전 연락이 필요하기도 합니다."],en:["Can I check golf bags or skis?","Yes. Whether they are included in your free allowance or charged extra depends on the airline. You may need to notify the airline in advance."],s:1,l:"1-11"},
{ja:["楽器は機内に持ち込めますか？","大きさによります。収納棚に入らない場合は、座席を購入して持ち込む方法や、預ける方法があります。事前に航空会社に相談してください。"],ko:["악기를 기내에 반입할 수 있나요?","크기에 따라 다릅니다. 선반에 안 들어가면 좌석을 구매해 반입하거나 부치는 방법이 있습니다. 미리 항공사와 상의하세요."],en:["Can I bring a musical instrument into the cabin?","It depends on its size. If it does not fit in the overhead bin, you can buy an extra seat for it or check it in. Contact the airline in advance."],l:"1-11"},
{ja:["壊れやすい物を預けるときの注意は？","しっかり梱包してください。梱包が不十分な場合や既に傷がある場合は、破損の責任の範囲を確認する書類に署名をお願いすることがあります。"],ko:["깨지기 쉬운 물건을 부칠 때 주의점은?","단단히 포장하세요. 포장이 불충분하거나 이미 흠집이 있으면 파손 책임 범위를 확인하는 서류에 서명을 부탁하기도 합니다."],en:["What should I know when checking fragile items?","Pack them securely. If the packing is weak or the item is already damaged, you may be asked to sign a form confirming the limits of liability."]},
{ja:["電子たばこ・ライターは？","電子たばこは預けられず、機内に持ち込みます（機内での使用は禁止）。ライターは1人1個まで身につけて持ち込めるのが一般的です。"],ko:["전자담배·라이터는?","전자담배는 부칠 수 없고 기내에 가지고 탑니다(기내 사용 금지). 라이터는 1인 1개까지 몸에 지니고 반입하는 것이 일반적입니다."],en:["What about e-cigarettes and lighters?","E-cigarettes cannot be checked; carry them in the cabin (using them on board is prohibited). Usually one lighter per person may be carried on your person."],s:1}]},
{id:"q3",ja:"特別な対応が必要なお客様",ko:"특별 대응이 필요한 승객",en:"Special Assistance",items:[
{ja:["妊娠中でも飛行機に乗れますか？","多くの場合乗れますが、出産予定日が近い場合は医師の診断書が必要になったり、搭乗できなかったりします。週数の基準は航空会社で違います。"],ko:["임신 중에도 비행기를 탈 수 있나요?","대부분 탈 수 있지만 출산 예정일이 가까우면 의사 소견서가 필요하거나 탑승할 수 없기도 합니다. 주수 기준은 항공사마다 다릅니다."],en:["Can I fly while pregnant?","In most cases, yes. Close to your due date you may need a doctor’s certificate, or you may not be allowed to fly. The limits differ by airline."],s:1,l:"1-6"},
{ja:["子どもだけで飛行機に乗れますか？","航空会社によって、一定の年齢の子どもが一人で旅行するサービスがあります。申込書、出発地と到着地の保護者の情報が必要です。"],ko:["아이 혼자 비행기를 탈 수 있나요?","항공사에 따라 일정 연령 아이가 혼자 여행하는 서비스가 있습니다. 신청서, 출발지와 도착지 보호자 정보가 필요합니다."],en:["Can a child fly alone?","Many airlines offer a service for children of a certain age traveling alone. You will need an application form and details of the adults at departure and arrival."],s:1,l:"1-7"},
{ja:["赤ちゃんは何歳から乗れますか？","生後の日数の条件（例：生後8日以降など）があります。2歳未満は大人の膝の上に座る運賃があり、ベビーベッド（バシネット）は事前の予約が必要なことが多いです。"],ko:["아기는 몇 살부터 탈 수 있나요?","생후 일수 조건(예: 생후 8일 이후 등)이 있습니다. 2세 미만은 어른 무릎에 앉는 운임이 있고 아기 침대(배시넷)는 사전 예약이 필요한 경우가 많습니다."],en:["How old must a baby be to fly?","There is a minimum age in days (for example, from 8 days old). Children under 2 can travel on an adult’s lap, and a bassinet usually needs to be booked in advance."],s:1},
{ja:["車いすを使っています。どうすればいいですか？","予約時または出発の48時間前までに航空会社に連絡してください。空港での移動の手伝い、機内への搭乗の手伝いを用意します。電動車いすは電池の情報が必要です。"],ko:["휠체어를 사용합니다. 어떻게 하면 되나요?","예약 시 또는 출발 48시간 전까지 항공사에 연락하세요. 공항 이동 도움, 기내 탑승 도움을 준비합니다. 전동 휠체어는 배터리 정보가 필요합니다."],en:["I use a wheelchair. What should I do?","Contact the airline when booking or at least 48 hours before departure. Staff will help you through the airport and onto the aircraft. For power wheelchairs, battery details are needed."],s:1,l:"1-7"},
{ja:["病気があっても乗れますか？","多くの場合乗れますが、病状によっては医師の書類（医療情報の申告）が必要です。酸素の使用・医療機器の持ち込みは事前に相談してください。"],ko:["병이 있어도 탈 수 있나요?","대부분 탈 수 있지만 병세에 따라 의사 서류(의료 정보 신고)가 필요합니다. 산소 사용·의료기기 반입은 미리 상의하세요."],en:["Can I fly if I have a medical condition?","In most cases, yes, but some conditions require a medical form from your doctor. Contact the airline in advance about using oxygen or bringing medical devices."],l:"1-6"},
{ja:["目や耳の不自由な方への手伝いはありますか？","はい。予約時にお知らせいただければ、空港での案内、搭乗の手伝い、機内での案内を用意します。補助犬も条件付きで同伴できます。"],ko:["시각·청각 장애인을 위한 도움이 있나요?","네. 예약 시 알려 주시면 공항 안내, 탑승 도움, 기내 안내를 준비합니다. 보조견도 조건부로 동반 가능합니다."],en:["Is help available for passengers with visual or hearing impairments?","Yes. Tell the airline when you book, and staff will guide you at the airport, help you board and assist on board. Assistance dogs can travel with you under certain conditions."]}]},
{id:"q4",ja:"ペット",ko:"반려동물",en:"Pets",items:[
{ja:["ペットを機内に連れて行けますか？","小型の犬・猫を機内に持ち込めるサービスがある航空会社と、貨物室で預かる航空会社があります。容器と重さの条件、頭数の制限があります。"],ko:["반려동물을 기내에 데려갈 수 있나요?","소형 개·고양이를 기내에 반입하는 서비스가 있는 항공사와 화물칸에 맡는 항공사가 있습니다. 용기와 무게 조건, 마릿수 제한이 있습니다."],en:["Can I bring my pet into the cabin?","Some airlines let small dogs and cats travel in the cabin; others carry pets in the hold. There are rules on the carrier, weight and number of animals."],s:1,l:"1-8"},
{ja:["日本に犬・猫を連れて入るには？","マイクロチップ、狂犬病の予防注射、抗体の検査、到着の前の届け出など、日本の動物検疫の条件があります。準備に長い期間がかかるので、早めに動物検疫所の案内を確認してください。"],ko:["일본에 개·고양이를 데리고 들어가려면?","마이크로칩, 광견병 예방접종, 항체 검사, 도착 전 신고 등 일본 동물 검역 조건이 있습니다. 준비에 오랜 기간이 걸리니 일찍 동물검역소 안내를 확인하세요."],en:["How do I bring a dog or cat into Japan?","Japan’s animal quarantine requires a microchip, rabies vaccinations, an antibody test and advance notification, among other things. Preparation takes a long time, so check the Animal Quarantine Service early."],s:1},
{ja:["暑い時期にペットを預けられますか？","夏の暑い時期は、健康への配慮から受け付けを制限する航空会社や犬種があります。特に鼻の短い犬種は注意が必要です。"],ko:["더운 시기에 반려동물을 맡길 수 있나요?","여름 더운 시기에는 건강 배려로 접수를 제한하는 항공사나 견종이 있습니다. 특히 코가 짧은 견종은 주의가 필요합니다."],en:["Can I send my pet in hot weather?","In summer some airlines restrict pets, or certain breeds, for health reasons. Short-nosed breeds need particular care."],s:1},
{ja:["補助犬は？","盲導犬・介助犬・聴導犬などの補助犬は、条件を満たせば客室に同伴できます。事前に航空会社に連絡してください。"],ko:["보조견은?","안내견·도우미견·청각장애인 보조견 등 보조견은 조건을 충족하면 객실에 동반할 수 있습니다. 미리 항공사에 연락하세요."],en:["What about assistance dogs?","Guide dogs, service dogs and hearing dogs can travel in the cabin if the conditions are met. Contact the airline in advance."]}]},
{id:"q5",ja:"遅延・欠航",ko:"지연·결항",en:"Delays and Cancellations",items:[
{ja:["便が欠航したらどうなりますか？","次の便への振り替え、他社の便への振り替え、払い戻しなどの選択肢があります。条件は欠航の理由・航空会社の規則によります。空港の係員・航空会社からの案内に従ってください。"],ko:["편이 결항되면 어떻게 되나요?","다음 편 변경, 타사편 전환, 환불 등 선택지가 있습니다. 조건은 결항 이유·항공사 규정에 따릅니다. 공항 직원·항공사 안내를 따라 주세요."],en:["What happens if my flight is cancelled?","Options include rebooking on a later flight, transferring to another airline, or a refund. The conditions depend on the reason for the cancellation and the airline’s rules. Follow the instructions from airport staff and the airline."],l:"5-6"},
{ja:["遅延したら補償はありますか？","遅延の理由（天候・整備など）や時間、航空会社の規則・国の制度によって違います。食事券やホテルの提供がある場合もあります。"],ko:["지연되면 보상이 있나요?","지연 이유(기상·정비 등)나 시간, 항공사 규정·국가 제도에 따라 다릅니다. 식사 쿠폰이나 호텔 제공이 있는 경우도 있습니다."],en:["Is there compensation for a delay?","It depends on the cause (weather, maintenance and so on), the length of the delay, the airline’s rules and national regulations. Meal vouchers or hotel rooms may be offered."],s:1,l:"5-4"},
{ja:["遅延・欠航の証明書はもらえますか？","はい。会社・保険の手続きのための証明書を、航空会社の窓口で発行してもらえます。"],ko:["지연·결항 증명서를 받을 수 있나요?","네. 회사·보험 절차용 증명서를 항공사 창구에서 발급받을 수 있습니다."],en:["Can I get a delay or cancellation certificate?","Yes. The airline counter can issue a certificate for your employer or insurance company."]},
{ja:["乗り継ぎの便に間に合わなかったら？","同じ予約（通し）の航空券なら、航空会社が次の便を手配します。別々に買った航空券の場合は扱いが違うので注意が必要です。"],ko:["환승편에 늦으면?","같은 예약(연결) 항공권이면 항공사가 다음 편을 수배합니다. 따로 산 항공권이면 처리가 다르니 주의가 필요합니다."],en:["What if I miss my connecting flight?","If both flights are on the same booking, the airline will arrange the next flight. If you bought separate tickets, the rules are different, so take care."]},
{ja:["飛行機の中で長く待たされることはありますか？","滑走路の混雑や天候などで、出発前・到着後に機内で待つことがあります。長時間になる場合の基準（水・トイレ・降機の機会など）が国・会社で決められています。"],ko:["비행기 안에서 오래 기다리는 경우가 있나요?","활주로 혼잡이나 기상 등으로 출발 전·도착 후 기내에서 기다리기도 합니다. 장시간이 될 때 기준(물·화장실·하기 기회 등)이 국가·회사별로 정해져 있습니다."],en:["Could I be kept waiting on the aircraft for a long time?","Runway congestion or weather can mean waiting on board before departure or after arrival. Countries and airlines set rules for long waits (water, toilets and the chance to leave the aircraft)."],l:"5-7"},
{ja:["台風のとき、欠航は前日に分かりますか？","前日に決まることもあれば、当日の天候を見て決まることもあります。航空会社のサイト・アプリの運航情報を確認し、連絡先を予約に登録しておくと安心です。"],ko:["태풍 때 결항은 전날 알 수 있나요?","전날 정해지기도 하고 당일 날씨를 보고 정해지기도 합니다. 항공사 사이트·앱 운항 정보를 확인하고 연락처를 예약에 등록해 두면 안심입니다."],en:["Will I know the day before if a flight is cancelled because of a typhoon?","Sometimes the decision is made the day before, and sometimes on the day depending on the weather. Check the airline’s website or app, and register your contact details in your booking."]}]},
{id:"q6",ja:"出入国",ko:"출입국",en:"Entry and Departure",items:[
{ja:["パスポートの残りの期間はどれくらい必要ですか？","行き先の国によって違います。短期の旅行では、滞在の期間より長く有効であれば入れる国が多いですが、乗り継ぎの国の条件も含めて事前に確認してください。"],ko:["여권 남은 기간은 얼마나 필요한가요?","행선지 국가마다 다릅니다. 단기 여행은 체류 기간보다 길게 유효하면 입국 가능한 나라가 많지만 환승국 조건까지 포함해 미리 확인하세요."],en:["How much validity must my passport have?","It depends on the destination. For short trips, many countries only require it to be valid for your stay, but check the rules in advance, including those of any transit country."],s:1,l:"1-3"},
{ja:["入国の手続きはオンラインでできますか？","日本への入国では、入国審査・税関の情報を事前にオンラインで登録できる仕組みがあります。ほかの多くの国にも電子の入国の手続きがあります。最新の案内を確認してください。"],ko:["입국 절차를 온라인으로 할 수 있나요?","일본 입국은 입국 심사·세관 정보를 미리 온라인 등록하는 구조가 있습니다. 다른 많은 나라에도 전자 입국 절차가 있습니다. 최신 안내를 확인하세요."],en:["Can I do entry procedures online?","For entry into Japan, you can register immigration and customs information online in advance. Many other countries also have electronic entry procedures. Check the latest information."],s:1},
{ja:["出国した後に搭乗をやめたいときは？","出国の手続きを取り消す必要があります。一人で戻らず、航空会社の係員に申し出てください。"],ko:["출국한 뒤에 탑승을 그만두고 싶으면?","출국 절차를 취소해야 합니다. 혼자 돌아가지 말고 항공사 직원에게 말씀하세요."],en:["What if I want to cancel my trip after clearing departure immigration?","Your departure record must be cancelled. Do not go back on your own; tell the airline staff."],l:"2-6"},
{ja:["日本の免税の制度が変わると聞きました。","外国人旅行者向けの消費税の免税の制度が、2026年11月から、いったん税込みで買い、出国時の確認の後に返金する方式に変わります。出国の手続きに時間がかかる可能性があります。"],ko:["일본 면세 제도가 바뀐다고 들었습니다.","외국인 여행자 소비세 면세 제도가 2026년 11월부터 일단 세금 포함으로 사고 출국 시 확인 후 환급하는 방식으로 바뀝니다. 출국 절차에 시간이 걸릴 수 있습니다."],en:["I heard Japan’s tax-free system is changing.","From November 1, 2026, visitors will pay tax at the time of purchase and receive a refund after the goods are confirmed at departure. Departure procedures may take longer."],s:1}]},
{id:"q7",ja:"手荷物の事故・忘れ物",ko:"수하물 사고·분실물",en:"Baggage Problems and Lost Property",items:[
{ja:["荷物が出てこなかったら？","空港を出る前に、手荷物の受取所の近くの航空会社のカウンターで届け出てください。手荷物のタグの控えを見せると手続きがスムーズです。"],ko:["짐이 나오지 않으면?","공항을 나가기 전에 수하물 수취대 근처 항공사 카운터에 신고하세요. 수하물 태그 사본을 보여 주면 절차가 원활합니다."],en:["What if my bag does not arrive?","Before leaving the airport, report it at the airline counter near baggage claim. Showing your baggage tag receipt makes the process smoother."],l:"4-1"},
{ja:["荷物が壊れていたら？","できるだけ空港で届け出てください。後から気づいた場合も、条約で決められた期限内に書面で申し出る必要があります。"],ko:["짐이 파손돼 있으면?","가능하면 공항에서 신고하세요. 나중에 알았더라도 조약에서 정한 기한 내에 서면으로 신청해야 합니다."],en:["What if my bag is damaged?","Report it at the airport if possible. If you notice later, you must still report it in writing within the time limit set by international convention."],s:1,l:"4-1"},
{ja:["機内に忘れ物をしたら？","到着した空港の航空会社のカウンター、または空港の遺失物の窓口に連絡してください。品名と特徴、座席の番号を伝えると見つかりやすくなります。"],ko:["기내에 물건을 두고 내렸으면?","도착 공항 항공사 카운터 또는 공항 분실물 창구에 연락하세요. 품명과 특징, 좌석 번호를 전하면 찾기 쉬워집니다."],en:["What if I left something on the aircraft?","Contact the airline counter or the lost and found office at your arrival airport. Giving the item name, features and your seat number helps."],l:"4-4"},
{ja:["荷物が遅れて届いたとき、必要な物を買ってもいいですか？","航空会社によって、当面の日用品の費用を補償する規則があります。領収書を必ず保管し、事前に航空会社に確認してください。"],ko:["짐이 늦게 도착할 때 필요한 물건을 사도 되나요?","항공사에 따라 당분간 일용품 비용을 보상하는 규정이 있습니다. 영수증을 꼭 보관하고 미리 항공사에 확인하세요."],en:["If my bag is delayed, can I buy what I need?","Some airlines cover the cost of essential items for a limited time. Keep your receipts and check with the airline first."],s:1}]},
{id:"q8",ja:"国際線の旅行",ko:"국제선 여행",en:"International Travel via Japan",items:[
{ja:["日本の空港と海外の空港のいちばんの違いは？","日本の空港では、航空会社に代わってハンドリング会社が多くの作業を担い、接客が細やかな傾向があります。案内の雰囲気や手順が、ほかの国と少し違うと感じることがあります。"],ko:["일본 공항과 해외 공항의 가장 큰 차이는?","일본 공항에서는 항공사를 대신해 조업사가 많은 작업을 맡고 접객이 섬세한 편입니다. 안내 분위기나 절차가 다른 나라와 조금 다르게 느껴질 수 있습니다."],en:["How are Japanese airports different from airports elsewhere?","At Japanese airports, ground handling companies do much of the work on behalf of airlines, and service tends to be very detailed. Procedures and the style of announcements may feel a little different from other countries."]},
{ja:["日本の空港に何時間前に着けばいいですか？","繁忙期は保安検査場・出国審査が混みます。国際線は出発の2〜3時間前の到着がおすすめです。"],ko:["일본 공항에 몇 시간 전에 도착하면 되나요?","성수기에는 보안검색장·출국 심사가 붐빕니다. 국제선은 출발 2~3시간 전 도착을 권합니다."],en:["How early should I get to a Japanese airport?","Security and departure immigration get crowded in peak seasons. For international flights, arrive 2 to 3 hours before departure."]},
{ja:["空港で日本語以外の案内はありますか？","主な空港では英語の案内があります。国際線の多い空港や航空会社では、中国語・韓国語などの案内・放送・係員の対応がある場合も多いです。"],ko:["공항에 일본어 외 안내가 있나요?","주요 공항에는 영어 안내가 있습니다. 국제선이 많은 공항이나 항공사에서는 중국어·한국어 등의 안내·방송·직원 대응이 있는 경우도 많습니다."],en:["Are announcements available in languages other than Japanese?","English is used at all major airports. Airports and airlines with many international flights often also offer announcements and staff support in Chinese, Korean and other languages."]},
{ja:["日本で乗り継ぐときの注意は？","入国せずに乗り継げるか、手荷物が最終の目的地まで通しで預けられるかを確認してください。別々の航空券の場合は、いったん入国が必要なこともあります。"],ko:["일본에서 환승할 때 주의점은?","입국하지 않고 환승할 수 있는지, 수하물이 최종 목적지까지 연결 위탁되는지 확인하세요. 따로 산 항공권이면 일단 입국이 필요할 수도 있습니다."],en:["What should I know when connecting in Japan?","Check whether you can connect without entering the country and whether your bags are checked through to your final destination. With separate tickets you may need to enter Japan first."],l:"1-4"}]}
];
