/* 空港アナウンス文例集 — 英語の画面用データ（カテゴリ名・説明・基本・場面名・タイミング・ポイント） */
window.ANN_EN={
c1:{name:"Announcement Basics",desc:"Common basics for every situation: the order of languages, speaking speed, and how to read flight numbers and times.",
guide:[["Language order","At Japanese airports the usual order is Japanese, then English, then other languages (such as Korean or Chinese). Follow your airline and airport rules."],
["Speaking speed","Slower than normal conversation. Take a short pause between sentences."],
["Flight numbers","Airline name plus the digits one by one (for example, 【Airline】 flight one two three)."],
["Times","Say “3:15 p.m.” rather than using the 24-hour clock; it is easier to catch over a loudspeaker."],
["Gate numbers","Say “Gate 【12】” clearly. In some situations, repeat the number."],
["Opening and closing","Start with a clear opening, and end with an action (“please proceed to…”). Repeating the key point briefly at the end helps listeners."],
["Irregular operations","Apology first, then the facts (reason and outlook), what passengers should do, and the time of the next update. Do not add promotional phrases."],
["Voice","Bright, calm and steady. Keep the same distance between your mouth and the microphone."]]},
c2:{name:"Check-in Counter",desc:"Announcements around the counter, from the opening of check-in to the close.",items:[
["Check-in opens","About 2–3 hours before departure","Repeating the counter location twice is helpful."],
["During check-in","About 20–30 minutes before check-in closes",null],
["Last call for check-in","About 5–10 minutes before check-in closes","Use “immediately” only just before the close."],
["Check-in closed","At the closing time","Late passengers are handled under the airline’s rules. Do not say they can still board."],
["Power banks and dangerous goods","To the queue during check-in","Quantity and capacity limits differ by time and airline. ★ Always use the latest rules."],
["Baggage weight reminder","When the queue is long",null],
["Passengers checked in online","During check-in",null],
["Overbooking: asking for volunteers","During check-in, when the flight is overbooked","Decide the next flight and the compensation beforehand and explain them at the counter to those who come forward. Do not announce amounts."],
["Self bag drop","During check-in, when the queue is long","Repeating the location twice helps."],
["Liquids at security","To the queue during check-in","Some airports change the rules as they install new screening equipment. ★ Follow the airport's latest guidance."]]},
c3:{name:"Boarding Gate",desc:"Gate announcements from before boarding to the final call.",items:[
["Pre-boarding announcement","About 10–15 minutes before boarding",null],
["Priority boarding","At the start of boarding","Priority groups and order follow the airline’s rules."],
["Boarding by row","After priority boarding","Boarding from the rear reduces congestion in the aisle."],
["All passengers","After row boarding",null],
["Final boarding call","About 15–20 minutes before departure",null],
["Gate change","When the change is decided","Repeat the new gate number at the end."],
["Cabin baggage limits","Before boarding on a full flight",null],
["Boarding delayed","When the planned boarding time has passed",null],
["Aircraft change and new seats","Before boarding, after an aircraft change","Seat families and travel companions together first. Explain individually to anyone moved out of a higher class."],
["Boarding by group number","After priority boarding","Use the group numbers exactly as printed on the boarding pass, and move on to the next group instead of repeating the same call."],
["Strollers at the gate","Before boarding","Where strollers are returned (aircraft door or baggage claim) differs by airport and aircraft. Say it clearly."],
["Power banks on board","At the gate before boarding","★ Japan: from 24 April 2026, up to two power banks (160 Wh or less) per person and no charging on board (MLIT). Major Korean airlines have banned in-flight use since January 2026. Follow your airline's latest rules."],
["Boarding by bus","When the aircraft is parked away from the terminal","Before the last bus leaves, check that no one is left at the gate."],
["Early-morning gate announcement","Early-morning flights, before boarding","Early in the morning or late at night, keep announcements short and quieter. Some airports limit announcements at these times."]]},
c4:{name:"Paging Passengers",desc:"Calling a specific passenger. Protect privacy and do not give more information than necessary.",items:[
["Paging to the counter","When something needs checking after check-in","Do not give the reason over the PA."],
["Paging to the gate","After the final call","Once the closing time has passed, prepare to offload the baggage at the same time."],
["Checked baggage inspection","When a bag needs to be opened","Do not name the contents (such as batteries) over the PA."],
["Paging for a travel companion","When someone is separated from their party","For a lost child, check the airport’s procedure for not announcing the child’s name."],
["Lost property","When an item has been found","Do not describe the item in too much detail, so the owner can be verified."],
["Paging a passenger with a foreign name","After the final call","The name is a fictional example. Check the pronunciation in the booking record, use given name then family name in English, and leave out Mr or Ms if you are unsure."],
["Lost child","When staff are looking after a child","Do not announce the child's name; describe only their appearance. Confirm that the adult is the guardian before handing the child over."],
["Meeting a child traveling alone","In the arrivals hall","Hand the child over only after checking the adult matches the registration (see the Ground Staff series)."]]},
c5:{name:"Delays",desc:"Delay announcements follow this order: apology, reason, outlook, request, and the time of the next update. Keep updating at fixed intervals even when nothing has changed.",items:[
["Delay due to weather","When the delay is decided",null],
["Delay due to maintenance","When the delay is decided","Do not describe the maintenance in detail."],
["Delay due to a late inbound aircraft","When the delay is decided",null],
["Follow-up update (no change)","At fixed intervals","Keep to the promised time of the next update even without news (for example, every 15–30 minutes)."],
["New departure time","When the time is confirmed",null],
["Meal vouchers","For longer delays","Also print the eligible shops, hours and value on the handout."],
["Boarding after a delay","At the start of boarding",null],
["Delay for de-icing","On snowy days, before or after boarding","Waiting in line for de-icing can add time. Update passengers as soon as the estimate changes."],
["Waiting for the weather at the destination","Before boarding","If the flight may turn back or be cancelled, say so before boarding (see \"Flight may return or divert\" in chapter 6)."],
["Waiting due to air traffic congestion","Before or after boarding","Air traffic control delays can change suddenly. Give times as estimates."],
["Delay and onward connections","At the gate after a delay is confirmed","Connections on separate tickets are handled differently. Do not make promises on the spot."]]},
c6:{name:"Cancellations and Diversions",desc:"For cancellations and diversions, tell passengers exactly what to do next.",items:[
["Cancellation notice","When the cancellation is decided",null],
["Rebooking and hotels","After the cancellation","Give the conditions for each option (rebooking, other airlines, refund) on a handout."],
["Passengers who have cleared immigration","In the departure area after a cancellation","Staff escort passengers through the cancellation of their departure record."],
["For those meeting a diverted flight","In the arrivals hall",null],
["Flight may return or divert","Before boarding","Always announce conditional operations before boarding."],
["After landing at an alternate airport","After arriving at the alternate airport","On international flights, the process depends heavily on whether immigration can be cleared at that airport."],
["Returning checked bags after a cancellation","After a cancellation is confirmed","If bags will go straight onto the rebooked flight, say clearly that they will not be returned."]]},
c7:{name:"Arrivals",desc:"Information for arriving passengers. Keep baggage, connections and immigration short and clear.",items:[
["Baggage claim","After arrival",null],
["Baggage delivery delayed","At baggage claim",null],
["Connecting passengers","Near the aircraft exit after arrival",null],
["Delayed arrival (for those meeting)","In the arrivals hall",null],
["Baggage not arrived","At the end of delivery","See the baggage irregularity procedures in the Ground Staff series."],
["Passengers who have missed a connection","Near the aircraft exit after arrival","Also explain whether checked bags will be transferred to the new flight."],
["Immigration and customs","On the way to immigration after arrival","★ Each country has its own system, such as Visit Japan Web in Japan and the e-Arrival Card for foreign visitors to Korea."]]},
c8:{name:"Special Situations",desc:"Requests for medical help, congestion, and passengers who need special assistance.",items:[
["Request for medical professionals","When a passenger is unwell","Call the airport first aid or emergency services at the same time."],
["Security checkpoint congestion","When it is crowded",null],
["Pre-boarding for wheelchair users","Before priority boarding",null],
["Lost property storage","In the arrivals hall","Storage periods and handover procedures are covered in the Ground Staff series."],
["Long wait on board (from the gate)","For those meeting or waiting","Long tarmac delay rules are covered in the Ground Staff series."],
["Earthquake (at the gate)","During and right after the shaking","Repeat short sentences. After the shaking stops, follow the airport's emergency instructions and do not start boarding until the flight status is confirmed."],
["Keep your belongings with you","At regular intervals in the terminal",null]]}
};
